### ISSUE TITLE
Getting http status 401 before  connection

### ISSUE THREAD

**Issue by kecksk0enig** [erickok/transdroid#105]
Hi!
I am using transdroid with transmission behind apache2 (ssl) proxy.
Today i looked at the logs and found something like this:

```
xx.156.xx.218 - - [11/Feb/2014:19:28:30 +0100] "POST /transmission/rpc HTTP/1.1" 401 6078 "-" "Transdroid Torrent Connect"
xx.156.xx.218 - - [11/Feb/2014:19:28:30 +0100] "POST /transmission/rpc HTTP/1.1" 200 1962 "-" "Transdroid Torrent Connect"
xx.156.xx.218 - - [11/Feb/2014:19:28:30 +0100] "POST /transmission/rpc HTTP/1.1" 401 426 "-" "Transdroid Torrent Connect"
xx.156.xx.218 - - [11/Feb/2014:19:28:30 +0100] "POST /transmission/rpc HTTP/1.1" 200 18830 "-" "Transdroid Torrent Connect"
xx.156.xx.218 - - [11/Feb/2014:19:28:31 +0100] "POST /transmission/rpc HTTP/1.1" 401 426 "-" "Transdroid Torrent Connect"
xx.156.xx.218 - - [11/Feb/2014:19:28:31 +0100] "POST /transmission/rpc HTTP/1.1" 200 1962 "-" "Transdroid Torrent Connect"
xx.156.xx.218 - - [11/Feb/2014:19:28:31 +0100] "POST /transmission/rpc HTTP/1.1" 401 426 "-" "Transdroid Torrent Connect"
```

every refresh on transdroid results in those lines. it looks like it first tries to connect withoud required user.
Is there a way to fix this?

**Comment by Self-Perfection** [comment]
One more vote for this issue.  I have transmission behind nginx as a proxy, and I see that each request Transdroid sends without auth data, gets 401 and then retries.

**Comment by PaulW** [comment]
Have you enabled SNI on nginx/lighttpd?  I had a similar issue with haproxy to begin with, however making sure haproxy uses SNI for identification solved it for me.

I changed:

```
frontend public
  bind *:443 ssl crt /etc/.......
  reqadd X-Forwarded-Proto:\ https
  redirect scheme https code 301 if !{ ssl_fc }
  # 16000000 seconds: a bit more than 6 months
  http-response set-header Strict-Transport-Security max-age=16000000;\ includeSubDomains;\ preload;
  acl deluge01 hdr(host) -i deluge01.myhost.com
  use_backend deluge01_server if deluge01
```

to:

```
frontend public
  bind *:443 ssl crt /etc/.......
  reqadd X-Forwarded-Proto:\ https
  redirect scheme https code 301 if !{ ssl_fc }
  # 16000000 seconds: a bit more than 6 months
  http-response set-header Strict-Transport-Security max-age=16000000;\ includeSubDomains;\ preload;
  use_backend deluge01_server if { ssl_fc_sni deluge01.myhost.com }```

Not sure if this may be the same issue you are experiencing...

**Comment by skorokithakis** [comment]
I have the same problem now with Caddy, except I can't connect at all. It always gives me a 401, it doesn't send the auth header at all.

**Comment by Tetsumaki** [comment]
Hi, same problem with nginx and transmission-cli.

I do not have this problem with other clients but they are less sexy.

Tested with authentication requested by nginx or transmission-cli and the problem is the same.

Exemple output from my access.log nginx :

```
XX.XX.XX.XX - - [03/May/2017:01:36:00 +0200] "POST /transmission/rpc HTTP/1.1" 401 188 "-" "Transdroid Torrent Connect"
XX.XX.XX.XX - mylogin [03/May/2017:01:36:00 +0200] "POST /transmission/rpc HTTP/1.1" 200 10711 "-" "Transdroid Torrent Connect"
XX.XX.XX.XX - - [03/May/2017:01:36:00 +0200] "POST /transmission/rpc HTTP/1.1" 401 188 "-" "Transdroid Torrent Connect"
XX.XX.XX.XX - mylogin [03/May/2017:01:36:00 +0200] "POST /transmission/rpc HTTP/1.1" 200 1585 "-" "Transdroid Torrent Connect"
XX.XX.XX.XX - - [03/May/2017:01:36:03 +0200] "POST /transmission/rpc HTTP/1.1" 401 188 "-" "Transdroid Torrent Connect"
XX.XX.XX.XX - mylogin [03/May/2017:01:36:03 +0200] "POST /transmission/rpc HTTP/1.1" 200 1585 "-" "Transdroid Torrent Connect"
XX.XX.XX.XX - - [03/May/2017:01:36:03 +0200] "POST /transmission/rpc HTTP/1.1" 401 188 "-" "Transdroid Torrent Connect"
XX.XX.XX.XX - mylogin [03/May/2017:01:36:03 +0200] "POST /transmission/rpc HTTP/1.1" 200 1585 "-" "Transdroid Torrent Connect"
XX.XX.XX.XX - - [03/May/2017:01:36:03 +0200] "POST /transmission/rpc HTTP/1.1" 401 188 "-" "Transdroid Torrent Connect"
```

I usually use the https but I prefer to simplify the configuration of the file to better understand the problem :

```
server {
    listen 80;
    server_name my.url.net;

    auth_basic "Restricted";
    auth_basic_user_file /path/to/my/file;

    location / {
        return 301 https://$server_name/transmission/web/;
    }

    location ^~ /transmission {
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header Connection "";
        proxy_pass_header X-Transmission-Session-Id;
    }

    location /transmission/web/ {
        proxy_pass http://XX.XX.XX.XX:9091/transmission/web/;
    }

    location /transmission/rpc {
        proxy_pass http://XX.XX.XX.XX:9091/transmission/rpc;
    }
}
```

**Comment by HorlogeSkynet** [comment]
Exactly same problem as the OP here... Any news on this ?

(Thanks for this wonderful app btw)

Bye ! 👋

**Comment by erickok** [comment]
I am looking into preemptive authorization (like than with the old Vuze adapter).

**Comment by HorlogeSkynet** [comment]
Perfect ! Keep us posted, I'd be personally glad to test some things if needed :ok_hand:

**Comment by erickok** [comment]
@HorlogeSkynet Could you try to install https://github.com/erickok/transdroid/releases/download/v2.5.10-dev/transdroid-2.5.10-dev.apk and test your connection?

**Comment by HorlogeSkynet** [comment]
Yes, let me finish something, and I'll set up the reverse proxy again :crossed_fingers:

**Comment by erickok** [comment]
Excellent! I'll merge and let's hope we did not break any other people's auth (like digest auth)... 😬

**Comment by HorlogeSkynet** [comment]
:rofl:

I hope too :crossed_fingers:

If I manage to fix my issue, I'll post the solution here (it looks like an issue when reverse proxy-ing with Apache 2.4 ...)

Bye, thanks again :wave:

**Comment by gtsmnf** [comment]
This change seems likely to have broken digest authentication.

**Comment by skorokithakis** [comment]
Plus the problem isn't fixed. I keep getting the same every time, and trying to add a new torrent gives me an error in the UI (because of the 401). I have to refresh or retry (not sure which, I do both) before it will work. This bug is five years old at this point :(
