### ISSUE TITLE
Torrents opened with transdroid wont be added

### ISSUE THREAD

**Issue by kecksk0enig** [erickok/transdroid#108]
Hi!
If I download a torrent throug a site it trys to add it with transdroid to my transmissions erver. after a refresh the message that the torrent was sucessfully added is displayed.
However the torrent is not really added @ transmission server. A refresh on torrentlist shows nothing also.

If i open the URL fto the torrent from within Transdroid the torrent is added sucessfully,

**Comment by doctorlard** [comment]
I am getting this behaviour from all search results (public/anonymous, no logins etc.) on Transdroid "2312 development" to Transmission. Tapping a search result says "[torrent name] added, refreshing" but doesn't actually add it.
