### ISSUE TITLE
RSS Feed Improvement

### ISSUE THREAD

**Issue by hugorosario** [erickok/transdroid#126]
Hi there. 
First of all let me thank you for this great project you have here. 
I am using transdroid with Transmission and I find it really useful for managing my torrent downloads. I have a few RSS feeds to see the latest releases of movies but it lacks a very important feature which is a fast way to retrieve the rating and the plot for the movie (this could also be useful for series). 
Currently there is the ability to "Open website" from the context menu after you long-click the feed entry but sometimes this websites don´t have any useful content about the movie, like the plot and rating and you are forced to use your browser and make a Google search for the movie to find what it is about, than decide if you want to download it and get back to transdroid and add the entry to your torrent client. 
This is a very tedious task for a movie junkie that checks every new release out there.

My suggestion would be to integrate transdroid with some external information providers like IMDB, The Movie Database and The TV Database websites to fetch information about the torrent and present it in a user friendly layout inside transdroid without much effort from the user. It could be a new option on the context menu like "Show Movie information" or "Show Series Information".

Of course not every torrent is a movie or a tv show and that new option should only be available according to the type of content selected. It would be good to have a new setting defined in every RSS feed that would indicate which type of content would be delivered. I believe most people have separate feeds for each content type so this would be a nice approach to the problem.

You guys probably gonna call me lazy and I am, but I also think transdroid was created for lazy people who have the need to manage their torrent queue from anywhere. 

I think integration with The Movie Database and The TV Database would be fairly straightforward since they provide REST API´s and there would be no need for scraping any HTML content.

**Comment by gorantornqvist** [comment]
Sharing my simple yet effective imdb redirect script, put it on a web server with php support and set custom search site to http://yourserver/yourscriptname.php?%s
You probably need to keep the ArrRemoveWords list up-to-date.

<?php
$ArrRemoveWords = array("DVDRip","720p","1080p","1080i","BluRay","PROPER","Extended","x264","HDTV","HDDVD","UNRATED","REPACK","LIMITED","DTS","xvid","divx","mkv","avi","mpg","mp4","1999","2000","2001","2002","2003","2004","2005","2006","2007","2008","2009","2010", "2011", "2012", "2013", "2014", "2015","SiNNERS","SEPTiC","REFiNED","HALCYON","Chakra","CiNEFiLE","METiS","iNFAMOUS","Felony","MHD","CROSSBOW","LEVERAGE","HD4U","KaKa","LCHD","PROFiLE","aAF","AMIABLE","iMSORNY","Japhson","BRMP","METH","DIMENSION","CiNEFiLE","HiGHTiMES","CLASSiC","DEPRAViTY","CDDHD","SMOKEY","MACHD","CBGB","MELiTE","TREBLE","TiTANS","TWiZTED","7SinS","HAiDEAF","aBD","LzY","SEMTEX","KYR","OEM", "BestHD", "MOOVEE", "SPARKS", "ROVERS", "SceneHD", "FLHD", "PSYCHD", "GECKOS");

  if ($_SERVER['QUERY_STRING'] != '') {
    $search = $_SERVER['QUERY_STRING'];
    foreach ($ArrRemoveWords as $word) {
      $search = str_replace($word,"", $search);
    }
    $search = str_replace("."," ", $search);
    $search = str_replace("-"," ", $search);
    $search = str_replace(" ","+", $search);
    header("Location: http://www.imdb.com/find?q=" . $search);
  }
?>
