### ISSUE TITLE
socks proxy / tor onion address

### ISSUE THREAD

**Issue by d3x7ro** [erickok/transdroid#151]
Trying to connect to a onion address not sure what's wrong I had to force all apps on system through Tor because TD has no proxy settings but it still doesn't work

**Comment by eighthave** [comment]
Tor Onion Services provide a private way to securely connect to network services. They are also easier to setup and run than HTTPS. It would be great if tremotesf supported .onion addresses. Then someone can install Transmission on a home server, enable the .onion address for it, then privately and securely reach Transmission from anywhere on the Internet.

The easy way to do this is just add support for HTTP CONNECT and/or SOCKS proxy settings. Then the Orbot app will provide Tor to Tremotesf when the user sets the proxy settings. There are somethings that can be added to make that easier to do, like an "Orbot" or "Tor" proxy setting that sets the proxy to SOCKS on localhost on port 9050.

I can contribute Java code to make this happen, if that's something that would be merged.
