### ISSUE TITLE
Doesn't add torrent

### ISSUE THREAD

**Issue by ghost** [erickok/transdroid#153]
I can access my torrent list with transdroid, but when I try to add a torrent, I have a message from transdroid saying that the torrent have been added, be the torrent isn't added ...

Transdroid 2.1.4 from Fdroid on N7100
Server Transmission on a Freebox (box from a French internet provider)

**Comment by haayman** [comment]
I have the exact same issue. Will send a log. I don't see anything strange. Adding via the web interface works fine.

Looked into the transdroid log and found this:

259853 -- Fri Apr 26 18:31:50 GMT+02:00 2019 -- 3 -- Schedule server checker job
259854 -- Fri Apr 26 18:31:50 GMT+02:00 2019 -- 3 -- Execute session-get request to http://localhost:9091/transmission/rpc
259855 -- Fri Apr 26 18:31:50 GMT+02:00 2019 -- 3 -- Found pending job request{id=97, tag=server_checker, transient=false}, canceling
259856 -- Fri Apr 26 18:31:50 GMT+02:00 2019 -- 3 -- Receive HTTP 409 with new session code; now try again for the actual request
259857 -- Fri Apr 26 18:31:50 GMT+02:00 2019 -- 3 -- Retry to execute session-get request, now with X-Transmission-Session-Id: HuE55y3OPiMKLrYQxlU1yq5Q9WB7WZD8kWC5j19ctYBApgW3
259858 -- Fri Apr 26 18:31:50 GMT+02:00 2019 -- 3 -- Received content response starting with <h1>409: Conflict</h1><p>Your request had an invalid session-id header.</p><p>To fix this, follow th...
259859 -- Fri Apr 26 18:31:50 GMT+02:00 2019 -- 3 -- Schedule periodic jobInfo success, request{id=99, tag=server_checker, transient=false}, interval 00:15:00, flex 00:15:00
259860 -- Fri Apr 26 18:31:50 GMT+02:00 2019 -- 3 -- Schedule app update checker job
259861 -- Fri Apr 26 18:31:50 GMT+02:00 2019 -- 3 -- Error: org.json.JSONException: Value <h1>409 of type java.lang.String cannot be converted to JSONObject

**Comment by erickok** [comment]
@haayman your issue seems more linked to #499

**Comment by haayman** [comment]
> @haayman your issue seems more linked to #499

I'm sorry, but I don't understand. What's the solution now? I haven't set up any reverse proxy afaik.

**Comment by erickok** [comment]
@haayman For some reason your server keeps on returning 409 http codes, which means it is not accepting hte session token that Transdroid is sending. This seems to happen for certain custom configurations such as when using a reverse proxy. But you say you are connecting directly to Transmission? What version? Can you add a torrent via the web interface of Transmission? Can you add magnet links? What about .torrent files that you upload using Transmission?

**Comment by haayman** [comment]
I've got version 2.92-3ubuntu2
Yes, I can add torrent files to the web interface. 
I don't know what magnet links are 😳
And the last question? You mean from the command line? Never use that

**Comment by erickok** [comment]
No I mean if you have a torrent file (not jsut a link to it) on the phone,
and you 'open' it with Transdroid (which will uplaod it to you r server).

A magnet link is a link like this:
magnet:?xt=urn:btih:f42055fd45cf195cac68f242d1177c5a5b6162d5&dn=archlinux-2019.05.02-x86_64.iso&tr=udp://tracker.archlinux.org:6969
&tr=http://tracker.archlinux.org:6969/announce Can you try that?

**Comment by haayman** [comment]
uploading a .torrent works just fine
the magnet link also works

**Comment by haayman** [comment]
for the record: this works in the web interface.
Just tried the magnet link in transdroid: works
Downloaded a .torrent on my mobile and added it using transdroid: works

So: only adding it through search doesn't work

**Comment by erickok** [comment]
Do you have an example search/site or ideally link that doesn't work? Sounds much more like a specific issue with a certain site.

**Comment by erickok** [comment]
Feel free to send via transdroid@2312.nl if that's mroe comfortable for you.

**Comment by haayman** [comment]
Nope, none of the searches on all of the servers

**Comment by erickok** [comment]
What if you go to one of the sites directly instead of using the in-app
search, and try to add a torrent? Or just click a torrent at
http://torrent.ubuntu.com:6969/ ?

**Comment by haayman** [comment]
I tried the link in transdroid. It says successfully: / toegevoegd, but
nothing happens

Op vr 10 mei 2019 16:19 schreef Eric Kok <notifications@github.com>:

> What if you go to one of the sites directly instead of using the in-app
> search, and try to add a torrent? Or just click a torrent at
> http://torrent.ubuntu.com:6969/ ?
>
