### ISSUE TITLE
VPN feature request

### ISSUE THREAD

**Issue by sbaconnais** [erickok/transdroid#163]
Problem : Some seedboxes have to be use with a VPN. If you have two different seedboxes, you have to enable, disable, re-enable the VPN each time you want to connect your seedbox from outside the local network.

Request : It would be useful to be able to define a VPN for each seedbox.

How to : include a VPN client to transmission (or use one, like open VPN) and add an option in the advanced menu of servers configuration section.

**Comment by erickok** [comment]
I decided to not act on this. I cannot see a reliable and compatible way to implement this without major testing work. Sorry for any inconvenience. The platform should really solve this problem, IMHO.
