### ISSUE TITLE
Transdroid v2.3.0-RC1 Force Closes with Deluge v1.2+

### ISSUE THREAD

**Issue by baggar11** [erickok/transdroid#174]
Here's my log file.

Connection and error log:
1 -- Tue Oct 28 10:07:11 PDT 2014 -- 3 -- Deluge daemon: Error: java.lang.IllegalArgumentException: Host name may not be null
2 -- Tue Oct 28 10:07:12 PDT 2014 -- 4 -- ConnectionError exception: java.lang.IllegalArgumentException: Host name may not be null
3 -- Tue Oct 28 10:07:27 PDT 2014 -- 3 -- Deluge daemon: Success: {"id": 2, "result": {"stats": {"upload_protocol_rate": 5392, "max_upload": -1.0, "download_protocol_rate": 4047, "download_rate": 0, "has_incoming_connections": true, "num_connections": 8, "max_download": -1.0, "upload_rate": 0, "dht_nodes": 0, "free_space": 52064444416, "max_num_connections": 500},... (5549 chars)
4 -- Tue Oct 28 10:07:33 PDT 2014 -- 3 -- Deluge daemon: Uploading a file to the Deluge daemon: http://127.0.0.1:8112/upload
5 -- Tue Oct 28 10:07:58 PDT 2014 -- 3 -- Boot signal received, starting server and rss checker background services
6 -- Tue Oct 28 10:07:58 PDT 2014 -- 3 -- Boot signal received, starting app update checker service
7 -- Tue Oct 28 10:07:58 PDT 2014 -- 3 -- Deluge daemon: Success: {"id": 2, "result": {"stats": {"upload_protocol_rate": 5194, "max_upload": -1.0, "download_protocol_rate": 3800, "download_rate": 0, "has_incoming_connections": true, "num_connections": 9, "max_download": -1.0, "upload_rate": 0, "dht_nodes": 0, "free_space": 52064448512, "max_num_connections": 500},... (5549 chars)
8 -- Tue Oct 28 10:08:05 PDT 2014 -- 3 -- Deluge daemon: Uploading a file to the Deluge daemon: http://127.0.0.1:8112/upload
9 -- Tue Oct 28 10:08:08 PDT 2014 -- 3 -- Boot signal received, starting server and rss checker background services
10 -- Tue Oct 28 10:08:08 PDT 2014 -- 3 -- Boot signal received, starting app update checker service
11 -- Tue Oct 28 10:08:08 PDT 2014 -- 3 -- Deluge daemon: Success: {"id": 2, "result": {"stats": {"upload_protocol_rate": 4923, "max_upload": -1.0, "download_protocol_rate": 4143, "download_rate": 0, "has_incoming_connections": true, "num_connections": 22, "max_download": -1.0, "upload_rate": 0, "dht_nodes": 0, "free_space": 52064448512, "max_num_connections": 500}... (5550 chars)
12 -- Tue Oct 28 10:08:08 PDT 2014 -- 3 -- Deluge daemon: Success: {"id": 2, "result": {"stats": {"upload_protocol_rate": 4923, "max_upload": -1.0, "download_protocol_rate": 4143, "download_rate": 0, "has_incoming_connections": true, "num_connections": 10, "max_download": -1.0, "upload_rate": 0, "dht_nodes": 0, "free_space": 52064448512, "max_num_connections": 500}... (5550 chars)
13 -- Tue Oct 28 10:08:08 PDT 2014 -- 3 -- tunnel: Retrieved torrent listing
14 -- Tue Oct 28 10:08:08 PDT 2014 -- 3 -- tunnel: 0 new torrents, 0 newly finished torrents.
15 -- Tue Oct 28 10:08:09 PDT 2014 -- 3 -- Local Transdroid is at 216 and the reported latest version is 215

**Comment by erickok** [comment]
Fixed in a3a595d, see also #190.
