### ISSUE TITLE
Build failed

### ISSUE THREAD

**Issue by vliux** [erickok/transdroid#189]
I cloned the code today and fixed some Gradle configs as you are still using an older version of Gradle (I’m using 1.0.0). Now everything seems OK but except one thing which may be related to Android Annotation:

Build error:
~/vliux/transdroid/app/src/main/java/org/transdroid/core/gui/search/SearchActivity.java
error: cannot find symbol variable PACKAGE_NAME

I searched the whole build log (attached also) but didn’t find any information useful.

Seems your mail account transdroid.org@gmail.com has been disabled, so I can't send you full build log.

**Comment by erickok** [comment]
The latest build tools will not work with the master branch. The dev branch does compile so you will probably want to check that out. I will merged to master on the net stable release.
