### ISSUE TITLE
Transdroid And Rtorrent 0.9.4

### ISSUE THREAD

**Issue by Pingblue** [erickok/transdroid#193]
I connect to Transdroid through the HTTPRPC rutorrent plugin but after upgraded to rtorrent 0.9.4 I can no longer connect to Transdroid.

Downgrading to rtorrent 0.9.3 does resolve the issue.

**Comment by apsco** [comment]
Ever get this to work? I too am having issues. I've tried both with and without SSL. Works on 0.9.3 and broken with 0.9.4
Apache logs show it connecting with no errors, but transdroid just errors out.

**Comment by erickok** [comment]
Technically it is already fixed in https://github.com/erickok/transdroid/pull/194 but I need to merge it and release a new version, for which I hope to have time very soon.

**Comment by apsco** [comment]
Great thanks.... Looking forward to trying it out!
