### ISSUE TITLE
Suggestion: Preset URL paths

### ISSUE THREAD

**Issue by pjg-pigeon** [erickok/transdroid#195]
Add a number of preset RSS URL paths. Given that you might have a long list of RSS feeds and     your ISP keeps blocking the websites. If you had say 5 fixed URL options, you could substitute the main RSS feed URL1/my show.........

Meaning when ISP blocks your main source of RSS feeds you only have to edit one setting rather than changing multiple individual feeds.

**Comment by erickok** [comment]
I understand your issue but I don't think Transdroid needs to jump around the blocking of websites in this was. I can think of better solutions (use private sites, set up your private redirect proxy, use a single combined RSS feed) and regardless this is such a custom feature that it would clutter the app for 99.9% of the users. I am sorry and hope you understand.
