### ISSUE TITLE
Connection issue with Deluge

### ISSUE THREAD

**Issue by skorokithakis** [erickok/transdroid#197]
I'm getting the dreaded connection error with the latest version of Transdrone. The log shows connection denied for https://myhost.com:443, even though the connection works from the phone's browser, and I have Transdrone set to accept all certificates. What could be wrong?

**Comment by phaseburn** [comment]
Also getting this same thing. http and https fails when connecting to my deluge 1.3.11 web ui under Lollipop. Phone web browser and desktop browser work just fine. Transdroid just says "Error during communication; check your connection". This happens on local WiFi, and my phone's data connection. Please note I'm not using any of the local WiFi settings, as the deluge web server is not on my LAN. I've of course ensured that all ports are forwarded properly, as I said, it works fine via browser on the phone and desktop from multiple locations.

**Comment by erickok** [comment]
I have just tested again different versions of Deluge, including 1.3.11, and can connect without issue. Can you, via the Help menu in Settings, send me an error/help report? You might have a problem with a time difference between the server and your phone.

**Comment by skorokithakis** [comment]
I did, and you couldn't find anything wrong. I'm still getting the errors, time on both the computer and the phone seems right (I'll retest), and it works fine without SSL.

**Comment by skorokithakis** [comment]
Yep, the two are within two seconds of each other, and the browser loads the web UI fine. The error log just says HttpHostConnectException, and I haven't been able to build the apk so I can debug it.

**Comment by erickok** [comment]
Could you copy/paste the connection log here?

**Comment by skorokithakis** [comment]
You mean what I get when I press the "send error report" button?

**Comment by erickok** [comment]
Yes. Wait for Transdroid to try to connect and then copy/paste the output fo the connection log.

**Comment by skorokithakis** [comment]
Sure, here:

~~~
Transdrone 2.3.0 (217)
Deluge settings: https://username@deluge.host.me:443

Connection and error log:
505 -- Mon Jun 01 15:42:09 EEST 2015 -- 3 -- Error: org.apache.http.conn.HttpHostConnectException: Connection to https://deluge.host.me:443 refused
506 -- Mon Jun 01 15:42:09 EEST 2015 -- 3 -- ConnectionError exception: org.apache.http.conn.HttpHostConnectException: Connection to https://deluge.host.me:443 refused
507 -- Mon Jun 01 15:43:02 EEST 2015 -- 3 -- Error: org.apache.http.conn.HttpHostConnectException: Connection to https://deluge.host.me:443 refused
508 -- Mon Jun 01 15:43:02 EEST 2015 -- 3 -- ConnectionError exception: org.apache.http.conn.HttpHostConnectException: Connection to https://deluge.host.me:443 refused
509 -- Mon Jun 01 15:54:12 EEST 2015 -- 3 -- Error: org.apache.http.conn.HttpHostConnectException: Connection to https://deluge.host.me:443 refused
510 -- Mon Jun 01 15:54:12 EEST 2015 -- 3 -- ConnectionError exception: org.apache.http.conn.HttpHostConnectException: Connection to https://deluge.host.me:443 refused
~~~

**Comment by erickok** [comment]
You are using Deluge with SSL. Are you sure you are using port 443 and not the default 8112?

**Comment by skorokithakis** [comment]
Yeah, I have nginx reverse proxying it. The specific URL works fine in the browser, so I don't think that's the problem. I'm trying to build it, but I haven't used gradle before and `gradlew build` is complaining about `signing.gradle`, do you know how I can build the APK? I could add some logging calls if I can get a debug version on the phone.

**Comment by erickok** [comment]
Okay the proxy might be the issue. I do not have such a setup so I cannot test against it directly. (If you wish you may mail me (temporary) credentials so I can test directly against your system. But even cooler if you could debug it yourself! Make sure to grab the dev branch from github, the master branch is not compatible with the latest Android Gradle plugin version. You can simple build using ./gradlew build

**Comment by skorokithakis** [comment]
I have emailed you, thanks!

**Comment by skorokithakis** [comment]
I finally got this building. I needed to add the "Android Support Repository" package and upgrade the material-dialogs package to 0.7.2.8, as 0.6.3.3 is unavailable. It turns out that there's also a gradle lint bug, so I had to build with `./gradlew -x lint build`.

After all this, the debug version of the app works perfectly. The latest version on the site does not, and I have no idea why.

**Comment by erickok** [comment]
Well, for one I am very happy that it does work now, eventually.

Thanks for the explination on the building though. I should try to update
the build instrucitons on the GitHub readme. Or perhaps you can submit a
pull request for that? :P

**Comment by skorokithakis** [comment]
I could submit a PR, but it would be mostly "I went into the thingamajig and changed the foo to bar", as I have no idea why things were happening, I was just randomly StackOverflowing stuff.

By the way, could you send me a signed, release apk of the latest dev? I want to make sure that it's not the release building itself that breaks it.

**Comment by erickok** [comment]
Check http://transdroid.org/beta

**Comment by skorokithakis** [comment]
Yep, that works fine, thanks!
