### ISSUE TITLE
Bandwidth limiting does not work with qBittorrent

### ISSUE THREAD

**Issue by spinn** [erickok/transdroid#198]
When tapping the upper right corner, nothing happens. It would be great if it would pop-up a dialog which would let you set the bandwidth limits, as it already does for the other Torrent clients.

**Comment by Jqh63** [comment]
Just post the same issue as comment and rate into play store, please update API request (using ttorrent client)

**Comment by erickok** [comment]
Correct, this is not supported for qBittorrent as their web interface does not allow me to change the settings. The recent improvements have also not introduced that feature.
