### ISSUE TITLE
RSS feeds with too many items fail to open

### ISSUE THREAD

**Issue by flatlinebb** [erickok/transdroid#203]
When opening an RSS feed with about 300 new items, the app just returns to the main screen, without ever actually displaying the feed. Feeds with fewer items work fine.

Transdroid 2.3.0 (217)
Sprint Nexus 5 Lollipop 5.1

**Comment by erickok** [comment]
Any specific RSS feed I could test with? I could not find any that causes problems (as I do not have any that serves this amount of items). If no way around it, would it be okay to show max, say, 50 or 100 items?

**Comment by flatlinebb** [comment]
I use RSS feeds from a private tracker, so I can't give it to you because
it has my private key in it. But limiting to fewer items should work. I
would try 100.

Thanks,
Bart
___

Sent while on the go.

**Comment by erickok** [comment]
Could send me the link via email or the raw feed (XML) content? I can't seem to find a feed with this many items to test against.

**Comment by flatlinebb** [comment]
I am trusting you with my private info from the tracker. Here is the feed
URL:

https://broadcasthe.net/feeds.php?feed=torrents_notify_40985_ro1zsb7qtwlvltvt35gpvrwu97j0fnrd&user=1328&auth=0cfb2f0e7286aa8c622891e237dd0a68&passkey=ro1zsb7qtwlvltvt35gpvrwu97j0fnrd&authkey=a133715d667310add35eb0cfc11e8c94&name=WEB-DL+720p

**Comment by erickok** [comment]
OK so the feed loads fine here... Not sure what's wrong. Possibly out of memory errors. Does it actually crash (with a popup message)? If so, can you, after the crash, restart Transdroid and get the error data from te Help screen (via Settings)?

**Comment by flatlinebb** [comment]
When it crashes there is no pop up message. I click on the feed to open it
and the app just goes back to the main screen.
My phone is being repaired right now, but I get the same behavior on my
tablet, Nexus 7 2013, with lollipop. I'll send you the log.

**Comment by flatlinebb** [comment]
Please describe your problem:

Transdroid 2.3.0 (217)
rTorrent settings:
https://sabdata@albacore.cloudcat.org:443/rutorrent/plugins/httprpc/action.php

Connection and error log:
1400 -- Tue Jun 23 06:42:33 PDT 2015 -- 3 -- Calling d.multicall with
params [ main d.get_hash= d.get_name= d.get_state= d.get_down_rate=
d.get_up_rate= d.get_peers_connected= d.... ]
1401 -- Tue Jun 23 06:42:33 PDT 2015 -- 3 -- Boot signal received, starting
app update checker service
1402 -- Tue Jun 23 06:42:48 PDT 2015 -- 3 -- Boot signal received, starting
app update checker service
1403 -- Tue Jun 23 06:42:54 PDT 2015 -- 3 -- Calling d.multicall with
params [ main d.get_hash= d.get_name= d.get_state= d.get_down_rate=
d.get_up_rate= d.get_peers_connected= d.... ]

**Comment by erickok** [comment]
I can't seem to reproduce this.
