### ISSUE TITLE
Unable to connect to qBittorrent (3.2.0beta)

### ISSUE THREAD

**Issue by psbj** [erickok/transdroid#205]
Getting the "internal error building request" message when trying to connect.

This could have something to do with the new login page for the webui.

I'm not sure if there are earlier builds which have this problem as I went directly from 3.1.10 to 3.2.0beta.

Running on debian, in case you need to know.

**Comment by spinn** [comment]
3.2.0 is stable now so anyone who chooses to upgrade (and all new users) won't be able to connect to qBittorrent anymore.

**Comment by psbj** [comment]
Are you saying this is permanent or just until it's fixed in a later release?

**Comment by spinn** [comment]
Only until the devs update Transdroid.

**Comment by ThisIsADogHello** [comment]
Looks like qbittorrent updated their WebUI API from 3.10 to 3.20 :/  Kind of a major change for a minor version...

While attempting to debug why my client stopped working, I noticed a bunch of 404 errors in Wireshark, and I found this describing how the API has been changed:
https://gist.github.com/pmzqla/7e5733dbecfc50ee4ecd#file-web-api-documentation

**Comment by ThisIsADogHello** [comment]
I've just submitted a pull request that adds support for 3.2.0, as well as keeps support for 3.1.0 and older.

**Comment by erickok** [comment]
Thanks again for the pull request. Merged in 23400c22925fc852022e851f40b094fbbe2b2642 and ready for beta release.

**Comment by sabret00the** [comment]
@erickok How does one go about joining the beta?

**Comment by erickok** [comment]
I just released the beta here on GitHub as release 2.5.0. Normally you can grab it (manually) via http://transdroid.org/beta
