### ISSUE TITLE
cannot connect to deluge daemon

### ISSUE THREAD

**Issue by k21735** [erickok/transdroid#206]
I am trying to connect from Transdroid 2.3.0 to deluge-daemon version 1.3.6, without SSL. Connection fails, the deluge-daemon log says:

[INFO    ] 15:06:50 rpcserver:203 Deluge Client connection made from: 10.8.0.10:53589
[INFO    ] 15:06:51 rpcserver:223 Deluge client disconnected: [('SSL routines', 'SSL3_GET_RECORD', 'wrong version number')]

Connecting from a deluge client on another computer works fine, so I guess the problem comes from Transdroid.

**Comment by erickok** [comment]
I have just tested with different Deluge versions, including 1.3.7 and the latest, and can connect without issue. Can you also take a look at the connection log by Transdroid? You may use the Error/help report function in the Help settings menu in Transdroid.

**Comment by erickok** [comment]
As for others (see #197) the latest beta fixes Deluge connection issues, I consider this fixed too until I know otherwise.
