### ISSUE TITLE
Connect to Deluge deamon directly, without webUI?

### ISSUE THREAD

**Issue by m-p-3** [erickok/transdroid#214]
I'm currently toying with a Deluge server on Linux, and I'm wondering if it is possible to connect to the remote daemon directly (on default port 58846), without going through the WebUI.

I added a new username:password combo in my .config/deluge/auth file.I am currently able to connect to it remotely using the GTK UI on a PC, and I see Transdroid has the ability to send a username and password instead of the Deluge web password.

When I try to connecting to it through deluged, I get the following error:
ConnectionError exception: org.apache.http.NoHttpResponseException: The target server failed to respond

I suppose the only method to connect to a Deluge server using Transcroid is through the WebUI? If that's the intended behavior that's fine, I'm just trying to find out if something went wrong.

**Comment by erickok** [comment]
Yes, this is the intended behaviour. Like all other supported clients, their exposed web APIs are the one that Transdroid uses to connect, not some custom protocol. So yes, you need to set up a Deluge web interface and use those connection details.
