### ISSUE TITLE
Bug with android L

### ISSUE THREAD

**Issue by ascrounch** [erickok/transdroid#216]
Hello

Got android 5.0.2 on LG g2

Impossible to load a torrent . my disk is grey cannot take any files.

Tryed both beta and stable version...
Scan files is making an FC...

**Comment by ascrounch** [comment]
http://postimg.org/image/3yjn5x3h9/

**Comment by erickok** [comment]
I think you are still using the 2.3.0 version. This is fixed in 2.5.0-beta2. Can you double-check?

**Comment by erickok** [comment]
You might need to install a file manager that is compatible with the new Android 5+ file picker APIs. I recommend Dir.
