### ISSUE TITLE
No way to set proxy?

### ISSUE THREAD

**Issue by burnup** [erickok/transdroid#217]
After browsing through all the settings I couldn't find a way to set a proxy for all Transdroid data traffic. My torrent box is a Tor hidden service so I'd love to have Transdroid be able to resolve the .onion address.

**Comment by burnup** [comment]
I mean by connecting to a local instance of Orbot, obviously.

**Comment by erickok** [comment]
Possible duplicate of #163. Have to investigate some time on the future.
