### ISSUE TITLE
Labels

### ISSUE THREAD

**Issue by Freethefire** [erickok/transdroid#219]
When picking existing labels in dark skin mode, the labels are the same color as background ie white.  

Best regards! 

Update: screenshot from Nexus 7 2013 on android 4.4.4. 
![screenshot_2015-06-30-16-26-03](https://cloud.githubusercontent.com/assets/13038512/8433244/e486ee92-1f44-11e5-824e-aab1777a52ba.png)

**Comment by erickok** [comment]
Fixed in edce58ab035d2db81c80fab5cb66e26f019d9246. Thanks for the report. Will be in next release.
