### ISSUE TITLE
Search history

### ISSUE THREAD

**Issue by Freethefire** [erickok/transdroid#220]
The search history pull down is light grey and the text is white, qhich makes it really hard to read. Also the history list is not situated in connection with input field in landscape mode. 

Best regards!

**Comment by erickok** [comment]
Hmm it looks fine here, but it might be a specific compatibility issue with the Android version/AppCompat library. What device are you using and on which Android version? Do you use the light or dark theme?

**Comment by Freethefire** [comment]
Nexus 7 2013,  with pacman rom android 4.4.4. 
Just checked my LG G2 (d802) and the placement is correct there, but its still kinda hard reading the white text on grey bg. The lg is running cloudyflex 2.8 android 4.4.4. 
Both running transdroid in light theme.

**Comment by erickok** [comment]
Fixed by upgrade AppCompat and updating theme in edce58ab035d2db81c80fab5cb66e26f019d9246.
