### ISSUE TITLE
rTorrent XML-RPC limit is sometimes set too low

### ISSUE THREAD

**Issue by zaemach** [erickok/transdroid#221]
At some point, the TorrentDay search stopped working correctly. It still gives results, but based on what's happening below, I don't think it's correctly downloading the torrent.

The weird problem I was having is that every time I tried to add a TorrentDay torrent from the search results, Transdroid would stop communicating with my seedbox, as would rutorrent. It seemed to have just crashed, and I could only fix it by restarting rTorrent. 

I believe I have traced the problem to the code that sets the XMLRPC size limit in advance of adding the torrent. Because it's not downloading the torrent, but rather a 39-byte error message, it's setting the limit way too low. The result is that Transdroid and rutorrent both lose their ability to communicate with rTorrent.

If I manually adjust the limit back to a more reasonable value, Transdroid and rutorrent resume working without having had to restart rTorrent.

This should be a fairly simple fix--there just needs to be a minimum value (probably a good bit larger than the existing buffer). rutorrent by default automatically sets the limit to 67108863 bytes when it starts running, so I'd guess you have plenty of room.

**Comment by erickok** [comment]
Really, 67108863? That would be 64MB...

What happens is that I set the XML-RPC limit to the size of the torrent plus some small overhead buffer. Normally that would give more than enough space for all the other commands too, however, in this case the Search module is misbehaving and returning a 0-sized torrent, which causes the XML-RPC limit to be set to the size of that small overhead only. I'll set up a minimum to make sure other commands won;t start failing.
