### ISSUE TITLE
Dark theme has unreadable dialog text and toolbar icons

### ISSUE THREAD

**Issue by Forage** [erickok/transdroid#224]
Which the implementation of the new material design there are some problems with the appearance of the text in dialogs like moving a download and the icons in the toolbar when e.g. selecting some text.
Both the text as well as the icons are too white to properly see against the light white background.

Below is a screenshot that shows it all:
![screenshot_2015-07-24-18-45-39](https://cloud.githubusercontent.com/assets/550915/8879930/405d86ba-3235-11e5-88bb-396b60489e1f.png)

As you can see the text can hardly be read even though it's even selected and there are no icons like copy visible at all.

I'm on Android 4.4.4.
Let me know if you need any more information.

**Comment by Freethefire** [comment]
Same here.
