### ISSUE TITLE
Mark-up of pasted text in search bar retained

### ISSUE THREAD

**Issue by Forage** [erickok/transdroid#225]
With 2.5(.1) one can past copied text of e.g. a website into the search into and the mark-up used on the website is retained. I can't imagine that was by design ;-)
Instead it should loose its mark-up so it's clearly readable.

I'm on Android 4.4.4. Dark Transdroid theme.
Let me know if you need any more information.

**Comment by erickok** [comment]
I looked into this, but I am not sure what I can do about it. It is a default Android control and a default copy/paste feature.

Only thing I can think of is catching on-text-changed events and stripping all spans. Will have to test of that even works.

**Comment by erickok** [comment]
I have tried to implement this but I haven't found any solution.
