### ISSUE TITLE
load_start error - XMLRPC

### ISSUE THREAD

**Issue by VomerXDA** [erickok/transdroid#227]
Hi there,

I have a strange issue with transdroid & rtorrent (v0.9.4) using HTTPRPC (SCGI mount point is set to /ruTorrent/plugins/httprpc/action.php).

Strange thing is, I can view the torrent queue, remove, pause, resume BUT I CANNOT add new torrents via transdroid (magnet links or .torrent links).

The error log in transdroid shows this:

18 -- Wed Jul 29 11:23:15 EDT 2015 -- 3 -- Calling load_start with params [some_magnet_link_here ]
19 -- Wed Jul 29 11:23:16 EDT 2015 -- 3 -- de.timroes.axmlrpc.XMLRPCServerException: Method 'load_start' not defined [-506]
20 -- Wed Jul 29 11:23:16 EDT 2015 -- 3 -- ConnectionError exception: Error making call to load_start with params [ some_magnet_link_here ]: de.timroes.axmlrpc.XMLRPCServerException: Method 'load_start' not defined [-506]

Any help would be appreciated.

**Comment by erickok** [comment]
What version of Transdroid are you using? This was fixed in 2.5.1, see #194. If not, let me know.

**Comment by Kramerican** [comment]
Hi erickok - I'm seeing this exact issue and I am frankly baffled. I've triple-checked and I'm using v.2.5.4 (which is the latest as far as I can gather) and I'm seeing this exact issue. 

The log says - when adding a torrent:

Transdroid 2.5.4 (224)

... Later

5692 -- Thu Oct 15 23:17:11 GMT+02:00 2015 -- 3 -- ConnectionError exception: Error making call to load_start with params [ http://torcache.net/torrent/04F650FEF6EC74672084566BAA55F12952F22D36.torrent ]: de.timroes.axmlrpc.XMLRPCServerException: Method 'load_start' not defined [-506]


Looking at the commit for #194 I can see you renamed it to the new, correct, command load.start - so what gives??
