### ISSUE TITLE
Floating action button hovering over delete button when torrents are selected

### ISSUE THREAD

**Issue by sleelin** [erickok/transdroid#230]
The floating action button in the bottom right corner is overlaying the delete button when torrents are selected, making the delete button unusable.
This is happening after long pressing and selecting a torrent, then waiting about five seconds, after which the floating action button reappears.
Expected behaviour: the floating action button should remain hidden

**Comment by erickok** [comment]
I agree that the FAB should remain hidden. I can not reproduce this problem. Could you take a screenshot or (better) screencast of this behaviour. Do you experience this on a phone or tablet and what version of Android are you using?

**Comment by sleelin** [comment]
Seems to be consistently resolved in the latest version
