### ISSUE TITLE
Problem deleting torrents with data on rtorrent 

### ISSUE THREAD

**Issue by pamdemonia** [erickok/transdroid#231]
It seems to work fine the first time, but after that it gets slower and slower to start (minutes, not seconds). The number of files being deleted seems to make no difference, although sometimes going to a detail page or (rarely) hitting refresh will get it to start up.

It's happening on my LG G4, my Nexus 7 2nd gen (both not rooted and up-to-date), as well an on my ancient rooted Galaxy Nexus running an AOSP ROM of 4.4.4. It happens on wi-fi and on LTE. It was happening pre-material update also, but with the latest version it's gotten way worse.

Thanks for an indispensable program.

If you need any more info please ask.

**Comment by erickok** [comment]
I made a bunch of modifications in the rTorrent support, including a fix for incorrect payload size setting. What version of rTorrent are you using? Do you experience the same when (if) you are using a web interface, like ruTorrent? What version of rTorrent are you using? No problem with deleting torrents without the 'with data' options?

I have not seen this problem myself and am a heavy using of an rTorrent server, but there mught be some version/condition that sets this problem off.

**Comment by pamdemonia** [comment]
Sorry it took me so long to get back... 

Recent (not so recent now) changes you made seem to have cleared it up. Thus I am closing this bug.

**Comment by erickok** [comment]
Thanks for the feedback.
