### ISSUE TITLE
Today's update crashes

### ISSUE THREAD

**Issue by Freethefire** [erickok/transdroid#235]
Hey, 

Unfortunately todays update crashes on search. Tried to remove data (reset) both transdroid and search addon, still no luck. On cm12.1 nightly, Nexus 7 2013. 

Edit: might have been to fast to report this. On LG G2 it works, however the back button from search addon to transdroid doesn't work. 

Best regards 
Alex

**Comment by erickok** [comment]
Hallo you provide a crash log? (Check the Error report feature in the Help
menu) What device are you using?

**Comment by Freethefire** [comment]
It's in the mail :) 
Nexus 7 2013 on cm12.1 nightly and LG g2 d802 on lollipop 5.1.1

**Comment by erickok** [comment]
Thanks. Looks tablet related, I'll check it out!

**Comment by bicklp** [comment]
Just wanted to say im also on a nexus 7 2013, stock 5.1.1 and the 2.5.3 / 3.3 update is also crashing when i try to search. Managing torrents is working great...Have emailed error log

Cheers
