### ISSUE TITLE
Can't change port setting

### ISSUE THREAD

**Issue by layanto** [erickok/transdroid#236]
It appears that Transdroid always use port 8080 for qBittorent and does not allow the port to be changed. Port 8080 already used by something else and my qBittorent webui is using a different port. But can't find a way to tell Transdroud to use a different port.

**Comment by erickok** [comment]
It's the first setting in Advanced Options.

**Comment by kokotron** [comment]
I know this is an old issue, but I just found out it's not fixed. What the user actually means is that even if you change the port in Advanced Settings (for example, I have set it to 8181), when using qBittorrent, the actual port used is still the default, which is 8080. This is still an issue today. Please, can you take a look at this again? :)
