### ISSUE TITLE
Custom ports

### ISSUE THREAD

**Issue by J316** [erickok/transdroid#237]
When selecting the torrent software to use it automatically chooses the port based on that choice. You should definitely allow to choose custom ports

**Comment by erickok** [comment]
Duplicate of #236. Hard to find?

**Comment by J316** [comment]
Not hard but confusing, since it's in the same sector of the local network. It should be moved to the main page since it's not an advanced setting but a very basic one.

**Comment by sperfect** [comment]
Thanks. It's because the previous form has a Title bar, so the eye isn't expecting something there...
