### ISSUE TITLE
Unable to access IPv6 server

### ISSUE THREAD

**Issue by tagno25** [erickok/transdroid#238]
I am unable to access my server via IPv6 (via direct IP or DNS).  If I use a DNS record with IPv6, it will fail without even trying the IPv4 address.

Fail via DNS using IPv6
```
D/libc    (14325): [NET] android_getaddrinfofornet+,hn 27(0x73657276657231),sn(),hints(known),family 0,flags 4
D/libc    (14325): [NET] android_getaddrinfofornet-, err=8
D/libc    (14325): [NET] android_getaddrinfofornet+,hn 27(0x73657276657231),sn(),hints(known),family 0,flags 1024
D/libc    (14325): [NET] android_getaddrinfofornet-, pass to proxy
D/libc    (14325): [NET] android_getaddrinfo_proxy+
D/libc    (14325): [NET] android_getaddrinfo_proxy get netid:0
D/libc    (  557): [NET] android_getaddrinfofornet+,hn 27(0x73657276657231),sn(),hints(known),family 0,flags 1024
D/libc    (  557): [NET] _dns_getaddrinfo+, netid:365, mark:917869
D/libc    (  557): [NET] _dns_getaddrinfo-, (NS_SUCCESS)
D/libc    (  557): [NET] android_getaddrinfofornet-, SUCCESS
D/libc    (14325): [NET] android_getaddrinfo_proxy-, success
D/libc    (14325): [NET] android_getaddrinfofornet+,hn 21(0x323030313a3437),sn(),hints(known),family 0,flags 4
D/libc    (14325): [NET] android_getaddrinfofornet-, SUCCESS
D/libc    (14325): [NET] android_getaddrinfofornet+,hn 13(0x3230392e313533),sn(),hints(known),family 0,flags 4
D/libc    (14325): [NET] android_getaddrinfofornet-, SUCCESS
D/libc    (14325): [NET] android_getaddrinfofornet+,hn 27(0x73657276657231),sn(),hints(known),family 0,flags 4
D/libc    (14325): [NET] android_getaddrinfofornet-, err=8
```

**Comment by erickok** [comment]
It looks more like Android is not connecting to the IPv6 address. Can you reach it any other way, like form Chrome?

**Comment by tagno25** [comment]
It seems that the Deluge web interface does not support IPv6, which explains why loading via the IPv6 address fails.  The web interface loaded when I opened it in Chrome on the same Android device.  I wonder if Transdroid is only trying the first IP address when told to resolve a DNS name.

**Comment by erickok** [comment]
Not sure if this a Transdroid issue at all. IPv6 support on Android seems device and os version-dependent at best. I ca not connect to any IPv6 site with my Nexus 4 over wifi or 4G. Also, while Transdroid performs the http requests (via the Apache HTTP Client, to be precise), it relies on the OS for low level networking, such as resolving DNS names.
