### ISSUE TITLE
Search Torrent Name in IMDB, TVDB, Google Search

### ISSUE THREAD

**Issue by apoapostolov** [erickok/transdroid#24]
Add a new search setting when long press a torrent. A secondary list shows up with search engines, I'd like Google, IMDB and TVDB. Before searching allow edit if the search query do user can strip scene name and release tags that'd confuse search engines.

**Comment by gorantornqvist** [comment]
Sharing my simple yet effective imdb redirect script, put it on a web server with php support and set custom search site to http://yourserver/yourscriptname.php?%s
You probably need to keep the ArrRemoveWords list up-to-date.

<?php
$ArrRemoveWords = array("DVDRip","720p","1080p","1080i","BluRay","PROPER","Extended","x264","HDTV","HDDVD","UNRATED","REPACK","LIMITED","DTS","xvid","divx","mkv","avi","mpg","mp4","1999","2000","2001","2002","2003","2004","2005","2006","2007","2008","2009","2010", "2011", "2012", "2013", "2014", "2015","SiNNERS","SEPTiC","REFiNED","HALCYON","Chakra","CiNEFiLE","METiS","iNFAMOUS","Felony","MHD","CROSSBOW","LEVERAGE","HD4U","KaKa","LCHD","PROFiLE","aAF","AMIABLE","iMSORNY","Japhson","BRMP","METH","DIMENSION","CiNEFiLE","HiGHTiMES","CLASSiC","DEPRAViTY","CDDHD","SMOKEY","MACHD","CBGB","MELiTE","TREBLE","TiTANS","TWiZTED","7SinS","HAiDEAF","aBD","LzY","SEMTEX","KYR","OEM", "BestHD", "MOOVEE", "SPARKS", "ROVERS", "SceneHD", "FLHD", "PSYCHD", "GECKOS");

  if ($_SERVER['QUERY_STRING'] != '') {
    $search = $_SERVER['QUERY_STRING'];
    foreach ($ArrRemoveWords as $word) {
      $search = str_replace($word,"", $search);
    }
    $search = str_replace("."," ", $search);
    $search = str_replace("-"," ", $search);
    $search = str_replace(" ","+", $search);
    header("Location: http://www.imdb.com/find?q=" . $search);
  }
?>

**Comment by digitalnomad91** [comment]
@gorantornqvist  where's the script? I have one that I built, but as @erickok mentioned it's going to be difficult to build one that is reliable. I wills hare my solution soon, but if you can share yours that would also be helpful for me. Thanks!
