### ISSUE TITLE
Cannot find search option in 2.5.4

### ISSUE THREAD

**Issue by sirola3000** [erickok/transdroid#240]
Hi, I really like the new layout in version 2.5.4. However I cannot find the search icon anymore. I only seem to be able to find the options file/link/QR onder the plus sign. 

I'm using Android on a HTC-M8 and have the search module installed as well... Could you please help me, it's drivin me nuts not knowing how to do this.

**Comment by erickok** [comment]
Hallo you sure you are using Transdroid (from here or my website) and not Transdrone (from the Play Store) the stripped down Lite version?

**Comment by sirola3000** [comment]
Ahaaaaaaaa! So that's where I went wrong. Thanks for pointing out there's a difference. I have the beloved search icon back!
