### ISSUE TITLE
Invalid passkey when torrent added with Transdroid

### ISSUE THREAD

**Issue by bretter** [erickok/transdroid#241]
I am getting the following error in Transmission when adding torrents from piranha.excom.us (private tracker) using Transdroid:

Invalid passkey! Re-download the .torrent from http://piranha.excom.us

When downloading and adding the torrent from my computer it is started without error.

**Comment by erickok** [comment]
I think you are trying to add files by url to your server, but this typically doesn't work on private trackers. Download the .torrent file to your phone first, then add them using Transdroid.

**Comment by bretter** [comment]
Thanks for the heads up! I am indeed able to add files from private trackers by downloading then opening.
