### ISSUE TITLE
Cannot conenct to Deluge Server running in Thin-Client mode.

### ISSUE THREAD

**Issue by FrozenBeard** [erickok/transdroid#242]
Today I replaced my uTorrent on my home-server with the thin-client deluge setup, where Deluge runs as a service on Windows Sever 2012 R2, and it allows Deluge Client on another machine to download to this, its perfect, I just need to get a mobile interface working with it.
The web-UI is up and running, The Client-Server works fine, same local network with my phone and the latest transdroid, will not connect to the deluge server service :(

any ideas?

http://dev.deluge-torrent.org/wiki/UserGuide/ThinClient

**Comment by erickok** [comment]
Transdroid doesn't connect to the thin client interface of Deluge but the Web UI. So you just need to enable the web interface on Deluge and connect to that using the Web Password.

**Comment by FrozenBeard** [comment]
Turns out it was my Bad, when I changed the Web UI password, I clicked apply and ok, assuming that would set the password, there's a badly placed UI "change" button under the password change input fields I missed. user error!
