### ISSUE TITLE
Dead search engines.

### ISSUE THREAD

**Issue by Jochob** [erickok/transdroid#243]
I don't know if this is the right place to put this. But some search engines are dead now... i.e. extratorrent.cc , now it works in www.etmirrorr.com, how can we fix it? or only you can do it.

Sorry if, this message is not on the right place.

Thank you!

**Comment by erickok** [comment]
The correct place is in its own GitHub project at https://github.com/erickok/transdroid-search Please report any site that you know doesn't work and if they use a different domain or some other reason.
