### ISSUE TITLE
Documentation on github or other wiki

### ISSUE THREAD

**Issue by damccull** [erickok/transdroid#245]
I seem to be having issues accessing the transdroid.org site at the moment, but I can easily get to the the github repo. It'd be nice to see the documentation available in the wiki here or somewhere else if the site is broken.

http://isup.me/www.transdroid.org shows it down for everyone at 2:01AM CST.

**Comment by erickok** [comment]
Well it'd be even nicer if the website was up and running. :grin: I am not a fan of having to duplicate documentation but if I get someone that can help we write docs and maintain them (also on Github) that would be great.

BTW The website is running fine at the moment.
