### ISSUE TITLE
F-Droid build of 2.5.4 failed

### ISSUE THREAD

**Issue by Jonny007-MKD** [erickok/transdroid#246]
Reason: failed to find Build Tools revision 21.1.2

Is this some of your business or does F-Droid have to change things?

greetz

https://f-droid.org/wiki/page/org.transdroid.full/lastbuild_224
https://f-droid.org/wiki/page/org.transdroid.full

**Comment by erickok** [comment]
I do not maintain the F-Droid build. They probably need to update their build tools? At the moment Transdroid needs to be build with build tools 23.0.0.
