### ISSUE TITLE
Not enough space for Search string + Provider 

### ISSUE THREAD

**Issue by fernandog** [erickok/transdroid#248]
@erickok 

the left menu option like the table it's a good way

![2015-10-16 09 24 03](https://cloud.githubusercontent.com/assets/2620870/10541581/a7bbc818-73e8-11e5-8c0e-a09773d5bd4c.png)

**Comment by erickok** [comment]
Noticed this as well on my new phone. Need to fix (remove the search title part, here 'bat...').

**Comment by fernandog** [comment]
why don't use a swipe menu showing providers like in tablet?

**Comment by erickok** [comment]
What's a swipe menu? On tablets o show a fixed side list, but here is no
place for that on phones.

**Comment by fernandog** [comment]
What about a swipe left-right list?
