### ISSUE TITLE
port for rtorrent

### ISSUE THREAD

**Issue by rezad1393** [erickok/transdroid#249]
I cant set the port for rtorrent

is it rutorrent port or rtorrent scgi_port ?

my rutorrent is not set on 80 port but trasdroid just uses 80 port by default and is not changable

**Comment by erickok** [comment]
You can change the port to anything you want. It is the first option in advanced settings.

You need to set the port on which your webserver is running that hosts the SCGI mount. This is typically 80 for http and 433 for https (so these are automatically the defaults).

**Comment by rezad1393** [comment]
oh sorry 
you are right of course
didnt see that option .

**Comment by rezad1393** [comment]
but i still get access denied error
this doesnt happen on the same device browser.
is this rtorrent supported or rutorrent supported?

and what port should i put there?
in rtorrent.rc i have this option 
scgi_port = localhost:5000
and in lighttpd i have these two options

server.port		= 8880


scgi.server = ( "/RPC2" =>
    ( "127.0.0.1" =>
        (
            "host" => "127.0.0.1",
            "port" => 5000,
            "check-local" => "disable"
        )
    )
)

**Comment by erickok** [comment]
Yes typically you have the SCGI server port at 5000 and then you connect to
the Web port which you seem to have set at 8880.

**Comment by rezad1393** [comment]
Why are you answering with a yes?
I ask which port should I put in the setting and you answer is yes?
I have tried the port 8880 in transdroid but that doesn't work
It says "access denied"
I can open rutorrent on the same tablet in firefox with this address http://192.168.1.10:8880/
But in transdroid the server address is exactly that but still it won't open

On November 4, 2015 8:36:39 PM GMT+03:30, Eric Kok <notifications@github.com> wrote:
>Yes typically you have the SCGI server port at 5000 and then you
>connect to
>the Web port which you seem to have set at 8880.
>On 16 Oct 2015 7:37 pm, "rezad1393" <notifications@github.com> wrote:
>
>> but i still get access denied error
>> this doesnt happen on the same device browser.
>> is this rtorrent supported or rutorrent supported?
>>
>> and what port should i put there?
>> in rtorrent.rc i have this option
>> scgi_port = localhost:5000
>> and in lighttpd i have these two options
>>
>> server.port = 8880
>>
>> scgi.server = ( "/RPC2" =>
>> ( "127.0.0.1" =>
>> (
>> "host" => "127.0.0.1",
>> "port" => 5000,
>> "check-local" => "disable"
>> )
>> )
>> )
>>
>> —
>> Reply to this email directly or view it on GitHub
>>
><https://github.com/erickok/transdroid/issues/249#issuecomment-148780976>.
>>
>
>
>---
>Reply to this email directly or view it on GitHub:
>https://github.com/erickok/transdroid/issues/249#issuecomment-153793807

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by erickok** [comment]
Of you get access denied than the username or password are incorrect. Again
these are the username and password you've set up in your webserver. If you
don't want to use a username and password, check the option in Advanced
Settings.

Cheers,
Eric

**Comment by rezad1393** [comment]
ok 
setting no password have fixed it.
thanks eric
