### ISSUE TITLE
Add alternate hostname when using specifics Wifi. Usefull when using ssh tunnel at phone

### ISSUE THREAD

**Issue by fernandog** [erickok/transdroid#250]
@erickok 
As Transmission is http only.
That way I can set localhost:port when using ssh tunnel and internal IP with using Wifi at home
Transmission does not have plans to support certificates
That way I can secure my connection to transmission
thanks!

NZB360 does something like that. You can set local host and remote host.
http://i.imgur.com/QstzCvKl.png

**Comment by erickok** [comment]
You already can. Enter the SSID of your local network and enter the local IP (and port number). All in Advanced settings.

Note that these do not get switched until Transdroid is freshly started (which is sort of a bug). So you might need to hit the back button and restart Transdroid to use the correct setting.
