### ISSUE TITLE
load_start issue still present in latest version?

### ISSUE THREAD

**Issue by Kramerican** [erickok/transdroid#251]
Ok let's try it one more time and see if this gets noticed - posted as a comment to #227 :

Hi erickok - I'm seeing this exact issue and I am frankly baffled. I've triple-checked and I'm using v.2.5.4 (which is the latest as far as I can gather) and I'm seeing this exact issue.

The log says - when adding a torrent:

Transdroid 2.5.4 (224)

... Later

5692 -- Thu Oct 15 23:17:11 GMT+02:00 2015 -- 3 -- ConnectionError exception: Error making call to load_start with params [ http://torcache.net/torrent/04F650FEF6EC74672084566BAA55F12952F22D36.torrent ]: de.timroes.axmlrpc.XMLRPCServerException: Method 'load_start' not defined [-506]

Looking at the commit for #194 I can see you renamed it to the new, correct, command load.start - so what gives??

**Comment by erickok** [comment]
I have read your message, don't worry, I just didn't find the time yet to study in detail what is happening. There is a switch to use one method or the other based on the rTorrent version but some very specific versions still seem to hve issurs. What version of rTorrent are you using?

**Comment by Kramerican** [comment]
Hi Erick - Sorry I didn't mean to harass you or anything :O)

Yeah I suspected there was a version check at work ... The version of rtorrent I'm using is 

Client version 0.9.4

Package: rtorrent-rpc for openwrt - thought it was listed here, but can't find it atm:

http://downloads.openwrt.org/snapshots/trunk/ar71xx/generic/packages/packages/
