### ISSUE TITLE
Register as program for .torrent file

### ISSUE THREAD

**Issue by Jonny007-MKD** [erickok/transdroid#254]

**Comment by Jonny007-MKD** [comment]
Sorry, mobile website ;)

Sometimes I have to download torrent files because of the MIME or something and want to add them to Transdroid afterwards.

It would be nice if I could do this by simply "opening the file" in the Download section of the browser or in the file manager.
Also, the file dialog in Transdroid does not allow me to select .torrent files; they are grayed out.

So I suppose that Transdroid has to register as handler or something for these files.

**Comment by erickok** [comment]
Transdroid is already registered as .torrent handler as well as handler of the x-bittorrent mime type. However, it depends on how the website serves the torrent files whether this actually works. 

About the file dialog: again it depends on how the file was downloaded (what mime type it had) and which app you use as file manager. I recommend [Dir](https://play.google.com/store/apps/details?id=com.veniosg.dir).
