### ISSUE TITLE
Whitespace around IP/hostname results in connection error

### ISSUE THREAD

**Issue by deckmar** [erickok/transdroid#255]
When adding a new server in .lite (Transdrone) and accidentally getting a white-space after the IP or hostname, the connection to the server will fail. 

A white-space is added automatically if using the keyboard auto-complete, and the reason for the failed connection is neither obvious nor necessary.

This is solved by trimming the input text, or even regexp removing invalid IP/hostname characters - but the latter is trickier.

**Comment by erickok** [comment]
Merged into the 2.5.5 release. Thanks!
