### ISSUE TITLE
uTorrent - impossible to configure port

### ISSUE THREAD

**Issue by woj-tek** [erickok/transdroid#260]
I'm trying to setup connection to the uTorrent and after going through options I can't find any way to setup port number. Only in terms of local network, but that kinda defies the point for me. Also - I don't really want to use the default 8080 for that.

**Comment by erickok** [comment]
It's the first option in Advanced settings.

**Comment by woj-tek** [comment]
Yay! It's there. I think in my head I've considered first item as a header not an option so I've automatically skipped it. Now it works like a charm - thanks! :-)
