### ISSUE TITLE
Cannot connect through Verizon

### ISSUE THREAD

**Issue by BrttClne22** [erickok/transdroid#262]
I cannot connect to through Verizon's Wireless Network, however, I can connect through any LAN network using the same configuration. Has anyone else experienced this? I wouldn't think Verizon would block just Transdroid as it's a typical HTTPS connection. The server I'm connecting to works fine through the web browser on Verizon's network.

Any suggestions on how to debug the response from the server if there is one?

**Comment by erickok** [comment]
Likely you have not (correctly) set up your port forward, or you are using the incorrect external IP address. You can use the Error report function from the Help menu in Transdroid to get a detailed error log and/or send me the log for direct support.
