### ISSUE TITLE
Search need the install of a new APK

### ISSUE THREAD

**Issue by sorcer1** [erickok/transdroid#263]
I'm using Transdroid 2.5.5 and it's working to see my torrents on a seedbox.
I try to do a search and after the download an the install of the transdroid-search-3.5.apk i try to do a new search and i still have the same message.

In the search i desactivate all the publics torrents.
I added a new private search torrent (www.t411.in).

can somebody help me ?

**Comment by erickok** [comment]
If I understand correctly, Transdroid still asks you to install the Search Module? Make sure you install this from http://transdroid.org/download and then close Transdroid (using the back button or kill the app) and restart.

That private site is not natively supported, so all you can do is add a custom search, which will open the browser.

**Comment by sorcer1** [comment]
Yes, this my problem.
Still after download and install the search module transdroid ask me to install the search module.
Even after a phone restart.

**Comment by erickok** [comment]
Did it install correctly? Can you start the Torrent Search settings app (where you see the list of sites supported and enable/disable them)?

**Comment by sorcer1** [comment]
yes i can do enable or disable the items.
in my 1st post i saied "i desactivate all the publics torrents".

**Comment by erickok** [comment]
Ah now I see. So you use a private site but disabled all the public sites? Might be a bug, I have to check.

What happens when you enable at least one public site?

**Comment by sorcer1** [comment]
the search works...
