### ISSUE TITLE
Can't connect to deluge-web ui behind nginx revers-proxy

### ISSUE THREAD

**Issue by Haxy** [erickok/transdroid#265]
I set revers proxy on my nginx server to deluge-web.
location /deluge {
  proxy_pass        http://127.0.0.1:8112/;
  proxy_set_header  X-Deluge-Base "/deluge/";
}
Is it possible to set transdroid works with this config?

**Comment by erickok** [comment]
I am no expert on this at all and have never used nginx. If you want to set up a folder, you can find this setting in Advanced settings in Transdroid.
