### ISSUE TITLE
Transdroid apk

### ISSUE THREAD

**Issue by weezardry** [erickok/transdroid#268]
Hi there, I'm trying to download 2.5.5 apk but doesn't seems to work?

Thanks a lot!

**Comment by erickok** [comment]
What do you mean, doesn't work?

**Comment by weezardry** [comment]
i'm trying to download the apk for transdroid and the search module, but the links that were somehow provided led me to error pages...
https://github.com/erickok/transdroid/releases/download/v2.5.5/transdroid-2.5.5.apk
http://transdroid.org/latest-search
http://transdroid.org/latest

**Comment by erickok** [comment]
I don't get any error page here. Can you click the links in Releases here in GitHub?
