### ISSUE TITLE
Add server setting and new Chinese translation

### ISSUE THREAD

**Issue by bkjzs** [erickok/transdroid#271]
Hi,
Would you like to add a page to edit settings for a certain server, like a key-value table.
What's more, I uploaded new translation for Chinese Simplified.
Thanks.

**Comment by erickok** [comment]
I am not sure what you mean by having a key-value table for server settings? The settings screen doesn't work for you?

Translations go into http://translate.transdroid.org/

**Comment by bkjzs** [comment]
I mean, for example, the setting for aria2 itself, not for this app.
By the way, I have uploaded the translation already.

**Comment by erickok** [comment]
Duplicate of #204 for the server stats.

I will pull translations and merge them into Transdroid for the next release.
