### ISSUE TITLE
Folder support for uTorrent?

### ISSUE THREAD

**Issue by some-guy-23** [erickok/transdroid#277]
Right now the option to choose a subfolder for uTorrent seems to be disabled/greyed out.

This makes it more difficult to get it connected to a reverse proxy setup. Is there something I'm missing, or is it just not supported for uTorrent?

**Comment by erickok** [comment]
Advanced settings - > Folder.

**Comment by some-guy-23** [comment]
Yeah, that's the setting that is greyed out. :(

**Comment by erickok** [comment]
Hum it seems so, very odd. Okay I'll take a look.

**Comment by some-guy-23** [comment]
Let me know if you need any help debugging/troubleshooting.

I know there was one odd thing with setting up the reverse proxy, which is the logic used for the webUI uses absolute URL's once it gets to the API calls. So for example -

domain.com/utorrent/gui/?token=123

Had to setup an additional rewrite rule to handle this (so local requests didn't end up mapping to localhost:port/gui/gui/?token=123). As opposed to the other resources with requests (js/css/etc.) directly from domain.com/utorrent/resource and could be mapped up to localhost:port/gui/

However, I'd imagine the webUI's logic for building requests shouldn't affect Transdroid?

**Comment by erickok** [comment]
Fixed. Note that the folder comes after the port number but before the fixed /gui part. So if you set it to `/proxy` the construfted url looks something like `https://your-server.com/proxy/gui`.
