### ISSUE TITLE
Addiation: URL Base

### ISSUE THREAD

**Issue by shawncdavies** [erickok/transdroid#284]
Would it be possible to add a url base option? I'm running all my web clients through a reserve proxy but I couldn't find a way to do this in your app. 

My current url looks like https://subdomain.domain.org/deluge. Every time I try to add this it gets save as https://subdomain.domain.org/deluge:8112 . I tried changing to enter :443/deluge in the port field but it wouldn't accept anything but numbers.

**Comment by erickok** [comment]
There's already a folder setting in Advanced settings where you can enter /deluge.
