### ISSUE TITLE
Keyboard opens on delete

### ISSUE THREAD

**Issue by Freethefire** [erickok/transdroid#285]
As the title says, whenever I delete a torrent in Transdroid, the keyboard pops up with focus on the "Filter" text box. It's no biggie, but starts to become quite annoying. 
Keep up the good work!

**Comment by Freethefire** [comment]
Only in landscape though it seems.

**Comment by Freethefire** [comment]
Sorry about the closing and reopening... 

Keyboard only pops up in landscape mode.

**Comment by erickok** [comment]
What device do you use? Indeed when the filter entry box gets the focus the keyboard pops up. A UX bug I would agree.

**Comment by Freethefire** [comment]
Sorry, sloppy me. 
I'm on Nvidia shield k1, LG G2 and Nexus 7 2013. Both marshmallow and lollipop.

**Comment by erickok** [comment]
I can't fully reproduce this, but hopefully my commit fixes this.

**Comment by Freethefire** [comment]
Will continue to monitor the app, and report back. Thanks!

**Comment by bwitt** [comment]
@erickok sounds like this issue can be closed

**Comment by erickok** [comment]
Yup
