### ISSUE TITLE
grabicon returning "405 Not Allowed"

### ISSUE THREAD

**Issue by adelolmo** [erickok/transdroid#287]
c&p from my comments on https://github.com/erickok/transdroid/issues/269

> I get "405 Not Allowed" when trying the url in the computer browser.
> http://grabicon.com/icon?origin=www.transdroid.org&domain=http://showrss.info/user/18370.rss?magnets=true&namespaces=false&name=clean&quality=null&re=yes
> 
> I was curious about grabicon.com and checked their website. It turns out that it's not a free service after the first 30 days trial period. Then again, there's a limit of requests per day in the different payment packages (http://grabicon.com/pricing).
> Is it grabicon.com the best option?
> Here they suggest two other options: http://stackoverflow.com/questions/22842262/an-alternative-for-http-g-etfv-co-url-favicon-services#answer-27899580
> But i don't know any of them.

**Comment by erickok** [comment]
The Grabicon service was free (without indication that would change) when I chose it. Things have changed.

**Comment by adelolmo** [comment]
That fixes the problem.
Thanks !
