### ISSUE TITLE
Pirate Bay?

### ISSUE THREAD

**Issue by DykeJones** [erickok/transdroid#288]
Any hope of a thepiratebay.se functional search.  I know they are having tons of issues lately, and everything has to be done via proxy, so I understand if unlikely, but figured worth asking if it's in the works or just a wet dream not worth betting on.

Thanks for all your hard work, the app is amazing!

**Comment by erickok** [comment]
This should really go into https://github.com/erickok/transdroid-search Having said that, provide me with a working proxy and I'll change it. I currently use pirateproxy.wiki but that seems to have stopped working.

**Comment by DykeJones** [comment]
I use https://proxybay.la/ to find which proxies are active at any given
point.  It is merely a site that lists the active proxies and which are
up.  The proxies I most commonly use are:

https://ahoy.re/
https://tpb.proxyduck.net/
https://pirateproxy.tv/

I hope this helps.

Thank you again for all the work contributed to this project, I love this
tool as I am sure thousands others do as well.  I am sure you do not
receive the appreciation you deserve for it, so once again, thank you.

-Mike
