### ISSUE TITLE
Upload of torrents fails

### ISSUE THREAD

**Issue by jaali1337** [erickok/transdroid#290]
Previously this issue never used to happen, however as of the last 6 months (approx) this has been happening. 

I have had this occur in both cm 12.1 (android 5) and android 6. When I "download" a torrent from a Web browser, I get the option to open it with transdrone. When I do, I see the upload bar with the file open down the bottom of the screen and then dissappear. However, the file never makes it to my remote client (in this case deluge). The only way I can successfully upload is to download manually, and then use es file explorer and select the file through there. Trying to use the native "recent" or "download" tabs on the left have the same effect. Any assistance would be helpful.

**Comment by erickok** [comment]
When you open a link with Transdroid, it sends the link directly to your torrent client. This may or may not work, depending on the site you use. Downloading it first to your device and then uploading it (opening it) with Transdroid should work though. If this still doesn't work, can you provide an example link?
