### ISSUE TITLE
Not observing WiFi specific proxy settings

### ISSUE THREAD

**Issue by smoopmeister** [erickok/transdroid#293]
I have a WiFi network with an auto config URL/PAC file configured for specific sites which includes the below RSS feed I'm referencing.
When I try to navigate to an RSS feed in my browser without a PAC file, it doesn't connect.
When I try to navigate to an RSS feed in my browser **with** a PAC file, it connects fine.

On my phone, in chrome, that same RSS feed is accessible.
On my phone, in Transdroid, that same RSS feed is inaccessible.

This leads me to believe that transdroid isn't observing the proxy for the available connection. I've see other issues such as #217 which is about a proxy configurable within Transdroid. 217 references #163 which is about VPN. Neither of these are the same as the issue I'm experiencing.

**Comment by erickok** [comment]
I have no experiences with this but I expect the platform to take care of this. If it doesn't, that it I am afraid.
