### ISSUE TITLE
NoClassDefFoundError with setSupportActionBar of compat-v7

### ISSUE THREAD

**Issue by LiliWeiSE** [erickok/transdroid#295]
Dear developer of transdroid,

I have found out that the method setSupportActionBar of android support library v7 is widely used in the code. However, this method crashed your app on some Samsung devices.
The discussion can be found in the bug tracking system of Android: [here](https://code.google.com/p/android/issues/detail?id=78377). 
Numbers of apps are affected by this problem. And fixes were found effective by using the proguard like in [comment #308](https://code.google.com/p/android/issues/detail?id=78377#c308) or somebody reports that there's a valid workaround for this issue in 24.0.0-alpha1.

Thank you very much if you can fix this. Hope this information is helpful. :)

**Comment by erickok** [comment]
Yeah I am not going to add Progaurd to work around some bug in some Samsung device. I will upgrade to AppCompat 24 when it is released.

**Comment by bwitt** [comment]
is this still an issue?  do we need to bump this
https://github.com/erickok/transdroid/blob/aadddd0d3ac926bb376e956e2d2451f7d91ff638/app/build.gradle#L82
to the latest stable version?
https://developer.android.com/jetpack/androidx/releases/appcompat#version_151_3

**Comment by erickok** [comment]
Very old; will close.
