### ISSUE TITLE
Deluge doesn't see active web session.

### ISSUE THREAD

**Issue by paulpoco** [erickok/transdroid#298]
Not a Transdroid problem but if the deluge webui has not been opened by a browser then Transdroid cannot connect.

Steps involved:
Launch Transdroid and it responds no active webui.
Then I have to open a browser and connect to webui.
Then I can connect with Transdroid.

Is there a way for Transdroid to automate this?

**Comment by erickok** [comment]
No, but you can automate this on your server by having it connect to a default Deluge daemon (you are probably just running 1 anyway). See http://dev.deluge-torrent.org/wiki/Faq#HowdoIauto-connecttoaspecificdaemon
