### ISSUE TITLE
transdroid showing peers as seed count for rtorrent

### ISSUE THREAD

**Issue by binhex** [erickok/transdroid#299]
So i am seeing an issue with the latest release of Transdroid (2.5.6) and rTorrent, where Transdroid is incorrectly showing the number of seeds, it looks to be calculating the number of seeds from the number of peers, so the seed and peer count is always the same. I have seen this issue consistently for all torrents, so it does not seem to be related to a particular tracker, i have also double checked the ruTorrent webui and this is reporting a different seed and peer count to Transdroid.

**Comment by erickok** [comment]
I use rTorrent's reported:
d.peers_connected=
d.peers_not_connected=
d.peers_accounted=
d.peers_complete=
d.peers_accounted=

These map in Transdroid to:
seedersConnected = peers_complete
seedersKnown = peers_connected + peers_not_connected
leechersConnected = peers_accounted
leechersKnown = peers_connected + peers_not_connected

As far as I can tell that is the correct way to calculate seeders and leechers. I don't know what ruTorrent does. Any suggestions?

**Comment by binhex** [comment]
Hi Eric, thanks for responding to this, i have no idea how ruTorrent calculates it, all i do know is its different to how Transdroid is doing it :-). i will do some digging for you and see if i can figure out how they are doing it and let you know.

p.s gotta say, i love transdroid, superb work!
