### ISSUE TITLE
Unable to set default port number

### ISSUE THREAD

**Issue by matthewlinton** [erickok/transdroid#307]
I run transmission through NGINX on port 80 and 443 (For internal and external connections). From what I can tell, there is no way to change the default port in the overall server configuration.

**Comment by erickok** [comment]
Duplicate of #236. It's the very first setting in the Advanced Settings screen.

**Comment by erickok** [comment]
Duplicate of #236. It's the first setting in Advanced Options.

**Comment by matthewlinton** [comment]
Thanks for the quick response. I have no idea why I didn't see that. Everything is working now.
