### ISSUE TITLE
Transdroid won't authenticate to Caddy.

### ISSUE THREAD

**Issue by skorokithakis** [erickok/transdroid#312]
Transdroid doesn't want to authenticate when using Caddy as a server. I traced the problem and I'm getting an exception:

class org.apache.http.client.ClientProtocolException
org.apache.http.auth.MalformedChallengeException: Authentication challenge is empty

This is in `DelugeAdapter.java` on line 485 of current master. Unfortunately I don't know how to solve this, short of removing authentication on Caddy.

**Comment by erickok** [comment]
Could you give some background. What is Caddy and how do you use it with Deluge? It seems your server isn't understanding the basic authentication header I send it.

**Comment by skorokithakis** [comment]
Ah yes, sorry. Caddy is a web server, I'm using it to proxy deluge. All the browsers, including the phone's, are working fine, but Transdroid refuses to. I can send you an email with a user and password for my server, if you want to try, or you can just download and run the caddy binary locally.

**Comment by skorokithakis** [comment]
Maybe this applies?

http://stackoverflow.com/questions/13494148/org-apache-http-client-clientprotocolexception

**Comment by erickok** [comment]
Maybe, but I do not manually Base64 the auth header. I use the Apache library's default credentials feature.

https://github.com/koying/transdroid/blob/master/lib/src/org/transdroid/daemon/util/HttpHelper.java#L119

And I have never seen a webserver which was not compatible. Can you easily log the full request you receive in Caddy?

**Comment by skorokithakis** [comment]
I have logged the failing request's authorization header and caddy said it was completely unset. I have also looked at it with netcat and the header was missing. Stepping through it in the debugger later was showing it as added, though.

I'll try mitmproxy to get the exact thing that was sent and report back.

**Comment by erickok** [comment]
With Deluge I'm not using pre-emptive authorization so the first request won't have the header. The server then responds with an authorization request and a new call is made. Perhaps Caddy doesn't respond?

**Comment by skorokithakis** [comment]
Okay, I've run the traffic through mitmproxy and transdroid (transdrone, in this instance), makes a request that doesn't include auth headers. Caddy responds with:

~~~
Content-Encoding:           gzip
Content-Type:               text/plain
Server:                     Caddy
Strict-Transport-Security:  max-age=31536000; includeSubdomains
Vary:                       Accept-Encoding
Www-Authenticate:           Basic
Date:                       Tue, 31 May 2016 10:31:32 GMT
Content-Length:             40
[decoded gzip] Raw
401 Unauthorized
~~~

The STS header is because I switched to port 80 for this test, but the same thing seems to happen with TLS. Caddy definitely replies (I can see it in the log), but Transdroid just never tries to make a subsequent (authenticated) request. Why not use preemptive authorization with Deluge? That would solve the problem and make things faster by avoiding one roundtrip.

**Comment by erickok** [comment]
I can't know upfront what (if any) auth strategy is used (basic, digest), and Deluge by default doesn't een do this of course, so that's I think a good reason not to send the basic auth headers preemptively. It's also considered better for security to only send credentials if the server asks for them. Why, however, Transdroid never responds again I can't quite tell without a debugging session. The Caddy response looks fine to me.

**Comment by skorokithakis** [comment]
Do you have a GPG key? I can send you the server address and some test credentials if you like.

**Comment by erickok** [comment]
Okay it might be a bug in the Apache http client. Since I use the default Android version it probably won't have the fix.

See https://issues.apache.org/jira/browse/HTTPCLIENT-1604

I might have to manually package an updated and patched version of the lib in Transdroid. But I am afraid to break user's setups...

**Comment by skorokithakis** [comment]
Actually, I think it never responds because the above exception is raised, so it doesn't get as far as retrying.

**Comment by skorokithakis** [comment]
Ah, yep, looks like that's it. Too bad it's an upstream bug, releasing will be harder, you're right. Isn't the danger pretty much the same as using the updated version if it were in the OS, though?

**Comment by skorokithakis** [comment]
Also, is there anything I can do to work around this for the moment? Transdroid isn't working for me at all right now...

**Comment by erickok** [comment]
Sort of and clearly the OS-packaged version is not bug free either. Ideally I'd move away from the Apache lob but that would be a major work as quite some very specific features are used in Transdroid which don't work out of the box with Android's UrlConnection oor OkHttp.

**Comment by skorokithakis** [comment]
Hmm, that's too bad. Can I easily build a version with the upstream library locally, until a fix is released, or do something else to make it work with my setup?

**Comment by erickok** [comment]
I would not say it is easy to build a version with the upsteam lib. Maybe it is, I haven't tried. TO make it work with your setup I guess you could try a default authentication scheme, use a different proxy webserver or connect directly to deluge (it supports SSL) instead of via a proxy. Sorry for the lame answer.

**Comment by skorokithakis** [comment]
Hmm, thanks, that's too bad. I tried, apparently you need to put the dependency in your gradle file and then use something called jarjar to repack it, but I have no idea what that does. I'll see if I can work around it, thanks.

**Comment by skorokithakis** [comment]
Do you know if the Apache library has been updated to fix this bug? I'm running Android N but it persists. I haven't been able to find a workaround, and I'm wondering if it's likely that upstream will fix this soon, would you have an idea?

**Comment by erickok** [comment]
Likely the Apache library will work for you, but the Transdroid has to package this manually. No updates of the Apache lib in Android itself is ever updated (in fact it is deprecated in Android 6+).

**Comment by skorokithakis** [comment]
Ah :/ Are you planning to move off it at some point?

**Comment by skorokithakis** [comment]
This is primarily a caddy error, it violates the RFC by not sending a realm. This has been fixed upstream
