### ISSUE TITLE
You can not enter the correct port number when connecting to utorrent

### ISSUE THREAD

**Issue by IRainman** [erickok/transdroid#314]
Good day!

Trying to add utorrent address 192.168.1.1:32769 but the program worked appends address assigning port 8080, in the end it turns out that the program tries to connect to the address http://192.168.1.1:32769:8080 and of course nothing works. Correct, please.

P.S. version 2.5.7

**Comment by erickok** [comment]
Don't append the port in the host name, but enter it in the port field. It's the first setting in Advanced Settings.
