### ISSUE TITLE
Cannot connect when using reverse proxy (domain.com/deluge)

### ISSUE THREAD

**Issue by TimoVerbrugghe** [erickok/transdroid#316]
Hi Eric!

I'm really loving your application, but have recently hit a problem. I'm trying to put all the services of my Ubuntu home server through a reverse proxy, including deluge.

Currently, I can access deluge through a webbrowser using https://mydomain.com/deluge using port 443 (reverse proxied using Apache and using SSL).

But when I try to add the settings in your application (using Transdrone from Play Store at the moment), your application puts the port number in the wrong place.

Namely: https://mydomain.com/deluge:443 instead of https://mydomain.com:443/deluge. If I leave the port number empty, then it will use the default port 8112 instead (also in wrong place).

Is there any way to disable the port number if you are already enabled the SSL option in your application?

Thanks!

**Comment by erickok** [comment]
You are probably entering the data (port number and folder) in the wrong field. The hostname should JUST be your hostname. For the port number and folder there are separate settings in Advanced Settings of your config. 

If you want to use SSL, don't forget to enable this too in Advanced Settings.

Dub of #314 ?
