### ISSUE TITLE
Error Communicating with Server

### ISSUE THREAD

**Issue by xXShiina** [erickok/transdroid#321]
I have a problem with this app. I'm not sure what I'm doing wrong but I can't get it to connect.

I'm doing this on an Samsung Galaxy S4 from Verizon.

In my app settings I have it set to Utorrent. The Host name or IP is my computer IP which is housing Utorrent. I have my Username and password setup in both the Utorrent on my computer and in my phone.

But for advanced settings I'm not sure what to do. For port number i have it set to 8080, Local port number is also 8080, for local IP its my computers IP, which is a static IP.

I've followed the steps in the troubleshooting page but I'm not understanding something. It says to put the external IP address into the IP, but where does it go? There's 2 spots one in the normal settings and one in the advanced settings.

Also in the troubleshooting it says to use the IP from WhatismyIp, I thought that I would use the static IP that my computer is using not the external.

I have port forwarded correctly I believe, I had to go into my AT&T router and my Asus router to get them to communicate to each other.

I'm not sure what I'm doing wrong.

**Comment by erickok** [comment]
When connecting externally (your phone is not connected to your home Wi-Fi network) Transdroid issues your external IP setting, so the one from WhatIsMyIP. Make sure that it works via your phone browser and then it will work with Transdroid too.

**Comment by xXShiina** [comment]
Alright.

How would I go about making it connect using my WiFi?

I have some questions, I added my questions in the form of pictures. I added text next to the ones I don't understand really.

![transdroid 1](https://cloud.githubusercontent.com/assets/18011651/17092442/56bd81d2-5208-11e6-88b4-8cbcd89df3b2.png)
![transdroid 2](https://cloud.githubusercontent.com/assets/18011651/17092444/56be3f1e-5208-11e6-850e-a9b5ddad9d9e.png)
![transdroid 3](https://cloud.githubusercontent.com/assets/18011651/17092445/56bead14-5208-11e6-94a8-6c54978f4628.png)
![transdroid 4](https://cloud.githubusercontent.com/assets/18011651/17092443/56be1aa2-5208-11e6-9af7-9eb310f63231.png)

**Comment by erickok** [comment]
There is an install guide on my website www.transdroid.org. Fo specific connection problems perhaps you can better send me an error/help report via the app (see the Help settings menu). The normal 'IP or host name' setting is your external IP (see whatismyip.com). The port number is 8080 by default if you use uTorrent, but you can set it manually. The 'Local IP or host' and 'Local port number' settings are optional advanced settings and used only if you want to configure Transdroid to connect on a different IP when connected to a specific wifi network ('Local network').

The search sites settings have nothing to do with connecting to your server in the first place.
