### ISSUE TITLE
Can't connect to Deluge

### ISSUE THREAD

**Issue by Magic815** [erickok/transdroid#326]
So I have Deluge set up to work via reverse proxy so that I can reach it at the following:

https://example.com:10443/deluge

I am using 10443, because I run my computer behind a VPN, which uses port 443. 10443 is forwarded on both my router and VPN, and I'm currently able to reach the Deluge WebUI by entering the above URL in my browser.

However, the server I set up for this in Transdroid doesn't seem to connect. The server is correctly showing as 'https://example.com:10443/deluge' within the server list in Transdroid.

As for settings, I've put in the following:

Server Type: Deluge 1.2+
IP or host name: example.com
User name: < blank>
Password: < blank>
Deluge web password: deluge1234 (where deluge1234 is the password I changed it to in Deluge settings)

Advanced:
Port number: 10443
Local network: < My SSID for my home WiFi>
Local IP or host: 192.168.X.XXX < My internal IP>
Local port number: 8112
Disable authentication: < unchecked>
Folder: /deluge
Connection timeout: < untouched>
Use SSL: < checked>
Accept all SSL certifications: < checked> (and I tried < unchecked>, with the same result)
Custom SSL thumbprint: < untouched>

Optional:
Server OS: Windows (I'm on Windows) (Also tried choosing 'Linux,' with the same result)

With the above, the arrow icon just keeps spinning, but never stops. And it never throws an actual error message. Any thoughts? (I'm running Deluge 1.3.13 on Windows 8.1, 64 bit).

**Comment by erickok** [comment]
Looks correct to me. Could you send an error report form the Help menu? This should create a more in depth log or what Transdroid is trying to do. So you use no basic auth on your reverse proxy?

**Comment by Magic815** [comment]
Log has been sent. As for basicauth - I don't have it globally set on my webserver. Another service (Muximux) has basicauth enabled, but Deluge doesn't. I was figuring that SSL and the deluge web password would be enough. (But let me know if you think otherwise, haha).

**Comment by paulpoco** [comment]
After starting Deluge you have to connect with Browser first to establish the web interface.  Then try Transdroid?

**Comment by erickok** [comment]
Until further info, I blame the proxy.
