### ISSUE TITLE
Is there a way to launch transdroid from a url?

### ISSUE THREAD

**Issue by skorokithakis** [erickok/transdroid#327]
I use PushJet for notifications when torrents are complete. PushJet supports a url it can open when I tap the notification. Is there a URL I could use that would automatically open Transdroid?

**Comment by erickok** [comment]
Not really. You can start Transdroid via intents (even control your server through Transdroid via intents) and of course I support adding of torrents via links, but there is not a single start url I support. You can try to provide a magnet:// link (empty magnet schema link), but Transdroid will try to add it and give a warning/error every time, not ideal.

**Comment by skorokithakis** [comment]
Ah, I see, thank you!

**Comment by skorokithakis** [comment]
Err, would you consider changing the code to not give an error on empty magnet links, or support some other start URL perhaps?

**Comment by erickok** [comment]
But I am willing to add it, especially if there are more users who would like this?

**Comment by skorokithakis** [comment]
It's not so big a deal that I would like you to add a new URL, but at least maybe just not consider an empty magnet URL an error.
