### ISSUE TITLE
TPB and Extra Torrent Functionality

### ISSUE THREAD

**Issue by chrismo16** [erickok/transdroid#328]
When searching for sorting on TPB within the app I do not receive any matches. In Extra, I receive matches but when trying to add a torrent nothing happens. Is there a way to correct this?

**Comment by erickok** [comment]
Perhaps the specific site is blocked in your country? The proxy used at the moment is theproxypirate.pw; https://github.com/erickok/transdroid-search/blob/master/app/src/main/java/org/transdroid/search/ThePirateBay/ThePirateBayAdapter.java#L53 For Extra Torrent the main site is used; https://github.com/erickok/transdroid-search/blob/master/app/src/main/java/org/transdroid/search/RssFeedSearch/ExtraTorrentAdapter.java#L53
