### ISSUE TITLE
Add option to donate

### ISSUE THREAD

**Issue by olejon** [erickok/transdroid#329]
Hi from a fellow developer. I can not find a way to donate to the development of Transdroid. In the Play Store version you can add Google In-App Billing (the "purchase" must be "consumed" immediately to allow users to donate several times, it's all in the documentation), and on the website you can add a button to PayPal or something (Google takes about 30% of all purchases through apps, there's no code difference between a donation and a purchase). Remember you can not, according to Google's guidelines, add any other donation option than Google's own, in a Play Store app). Maybe there's already a donate button somewhere? I haven't found it. That's the only way I can contribute ATM. Just want to help :)

**Comment by erickok** [comment]
Thanks for wanting to help/donate!

I won't implement in-app transactions as that would requite dependencies on Play services which I don't really want and it would prevent distribution outside the Play Store (or make special releases for that). I sued to have a big Donate button on my website... I should add it again! Anyway, donations are welcome via PayPal at erickok@gmail.com !

**Comment by olejon** [comment]
Google In-App Billing as it is called is actually open source. You must download it in the SDK manager and add it as a Gradle dependency, yes. You can even upload the APK to F-Droid and it will be accepted and built (they only accept 100 % open source and build and sign the code themselves). I know this because I have an app with Google In-App Billing that is on Google Play, Amazon, Jolla Harbour, Blackberry World and F-Droid. *The exact same APK*. Well actually now it's different, because it supports Android Wear, and THAT requires Google Play Services. Also another app I have I use GMS because it implements maps. All the stores accept the APK anyway (with GMS), but not F-Droid (not really a "store" but...), so I must remove and modify some code here and there before pushing to the GitHub repo F-Droid automatically clones the code from and build the APK for F-Droid. Then I just undo the changes after pushing to F-Droid GitHub repo.

Of course one must check in code "purchasing" is supported on the device (in other words installed on a device that has the essential Google Play components), and if not, display an informative dialog. If you distribute on for example Amazon their quality control will not accept the app if a button does nothing for instance, but a dialog is ok. In that case be careful and not mention PayPal or any other service in your code/strings, as Google checks for that when you upload in Google Play Developer Console, because it's illegal to make transactions in a Google Play app using other services. Something like "Your device does not support this, please go to the website".

It's pretty easy to set up with pretty good documentation that cannot be said about all Android APIs... Prices and the names of the different donation options (if you add three options for instance) is set in Google Play Developer Console.

BTW: I thought you already had two versions? Transdrone and Transdroid. I remember Transdroid was banned from the Play Store so I have used the APKs from the website since. Is there no difference? I understand the search APK has to be downloaded separately anyway.

**Comment by erickok** [comment]
Okay I did not know that it was 100% opens source, good to know. Still, it would require implementing and testing something for which I hardly have any time and doubt it will generate enough to justify it. It does mean I could use it for the freely distributed version of the app via the website, right? The vast majority of users are using that full version.

**Comment by olejon** [comment]
No unfortunately I don't think you can. Google Play will refuse to do "purchases" if the app is not in the Play Store, same package name etc and the prices are defined when you go to Google Play Developer Console and click on your app and then there is an option for "In-app Products". If the package is identical it should work. Let's say I put the exact same APK I upload to Play Store for download on my website and the user installs it (installation from unknown sources must then be enabled in Settings as you know). Then it should work without problems.

Then I suggest you add a Donate option in the Settings of Transdroid or wherever you'll like it to be in the app, and when the user clicks it it goes straight to the PayPal donation site. To get the URL create a PayPal donation button (you're not interested in the button, just the URL it goes to).

* Go here: https://www.paypal.com/bm/cgi-bin/webscr?cmd=_button-designer&factory_type=donate
* Don't care about customizing the button, but fill out "Organization name/service field" (could say "Transdroid")
* Skip Step 2 and 3 (not necessary, as it says: Optional)
* Click the yellow "Create Button" below the steps
* IMPORTANT: Click the "Email" tab, only that will give you the direct URL and not an HTML form code
* Add somewhere in Transdroid a Donate possibility which opens the browser using a regular Intent for that to the URL
* Done

WARNING: Do not add this Donate possibility to the Play Store app then. Nowhere in the Play Store app code or XML (strings for instance) should it say "PayPal". You could get the app banned then. I suppose there are already code differences between Transdrone and Transdroid that so this would only be a couple of lines to add to Transdroid and remove from Transdrone, or the other way around. Don't know how you share the code between the two if they are different in functionality.

**Comment by olejon** [comment]
Updated my comment above a little bit.

**Comment by erickok** [comment]
Sounds good, thanks for the help @olejon as well as the donation!

**Comment by olejon** [comment]
You're welcome :)
