### ISSUE TITLE
Search module 

### ISSUE THREAD

**Issue by chewy74** [erickok/transdroid#330]
Hi Eric, 

The search module needs to be updated. Kickass, strike search and piratebay proxied all no longer work. Also the search function still crashes transdroid when used on a tablet...on a phone it's fine. 

Haven't seen an update for this in a while, but noticed the playstore version was updated in May. Would you suggest moving to that version now if you are planning on stopping this project? 

Anyways thanks for your hard work

**Comment by erickok** [comment]
Can you elaborate on 'doesn't work'? Are you on the latest release? KAT is already removed. The PB proxy works fine here. I have to take a look at Strike Search as it indeed looks down.

**Comment by erickok** [comment]
BTW This report should really go in https://github.com/erickok/transdroid-search so I created a ticket there: https://github.com/erickok/transdroid-search/issues/46

**Comment by chewy74** [comment]
Sorry Eric, I was on version 2.54 transdroid and search module 3.5

The apps update notification never notified me of a update from either.

**Comment by Atrejoe** [comment]
Same here, I wasn't notified about the updated search module.

**Comment by chewy74** [comment]
There might be an issue with the update notification? 

Eric? I still have a old version of the apk and could try to get a log if you want one. Let me know

**Comment by erickok** [comment]
The update notification is managed by Transdroid, not the search module,
actually. You can view Transdroid's log to see if it checked the version,
but I suspect the url where the latest version is mentioned was not updated
by me... http://www.transdroid.org/update/latest-search

**Comment by chewy74** [comment]
Yes, I didn't receive any notification from transdroid for either the search or the transdroid app itself. 

Thanks
