### ISSUE TITLE
Change default deluge port

### ISSUE THREAD

**Issue by kashifsmalik** [erickok/transdroid#338]
When configuring deluge server, Transdroid automatically sets 8112 as default port, and there is no option to change it.

**Comment by TheSoftwareDev** [comment]
The port number can be changed under Server > Advanced Settings > Port
Number

**Comment by kashifsmalik** [comment]
Thanks for the support and apologies for the oversight.

**Comment by rendeko** [comment]
I'm still having this issue on 2.5.7. Adding an optional port number still presents the server as username@xxx.xxx.xxx.xxx:8112. This is on the FDroid release.

**Comment by erickok** [comment]
@rendeko You maybe used the Local port setting (only used for your local network) instead of the main port setting?

**Comment by rendeko** [comment]
@erickok That's exactly what I did... The port number setting takes the place of the Transdroid header when going into advanced settings, so my eyes must have glanced over it every time. My bad, thanks.
