### ISSUE TITLE
Application crashes after adding a magnet link

### ISSUE THREAD

**Issue by antoinereis** [erickok/transdroid#340]
Next magnet link leads to application crash:

magnet:?xt=urn:btih:59a4b05c456b30bae0e475f6f9696299472fe601&amp;dn=rutor.info_%D0%A2%D0%B5%D0%BE%D1%80%D0%B8%D1%8F+%D0%91%D0%BE%D0%BB%D1%8C%D1%88%D0%BE%D0%B3%D0%BE+%D0%92%D0%B7%D1%80%D1%8B%D0%B2%D0%B0+%2F+The+Big+Bang+Theory+%5B10%D1%8501-07+%D0%B8%D0%B7+24%&amp;tr=udp://bt.rutor.org:2710/announce&amp;tr=http://announce.opensharing.org:2710/announce&amp;tr=udp://exodus.desync.com:6969&amp;tr=udp://tracker.publicbt.com:80&amp;tr=udp://tracker.openbittorrent.com:80&amp;tr=udp://open.demonii.com:1337&amp;tr=http://retracker.local/announce

**Comment by erickok** [comment]
This url is invalid as it includes an invalid escape sequence. Of course Transdroid should report this and not crash, which I fixed.
