### ISSUE TITLE
Enhancement - Keep previous search text in the text field so it can be edited

### ISSUE THREAD

**Issue by pholcroft** [erickok/transdroid#341]
Currently when you search you have to enter your search text from scratch, even if you just want to change a single character from a previous search. e.g. Previous Search: "searchterm s05e06" New Search: "searchterm s05e07"

When you click on search the text field should remain empty, but if the user clicks on a search from history, then put that text in the search field and then let them click to search, rather than just searching immediately. This will allow the search text to be editable before searching.

If you want an example of this, the eBay app works this way.

**Comment by erickok** [comment]
When entering a search text you should see the list of recent queries and you can click on the arrow icon on the right to re-use it (after which you can edit the text again).
