### ISSUE TITLE
qBittorrent, sort by "completed on" is broken.

### ISSUE THREAD

**Issue by kokoko3k** [erickok/transdroid#344]
Just as subject says, items are not sorted right.

**Comment by baggar11** [comment]
I've noticed the same thing.

**Comment by erickok** [comment]
Hmm qBittorrent already seems to support this now for 2 years... (See https://github.com/qbittorrent/qBittorrent/commit/b94a1b9fbe7f365b59b070f7ea611956b595681b) So I added this + support for 'Added On' + proper error state support.
