### ISSUE TITLE
Dismiss message from lock screen 

### ISSUE THREAD

**Issue by PMaynard** [erickok/transdroid#345]
With out having to unlock the device, it would be nice to be able to dismiss the message from the lock screen. The message I normally see is an alert for a new RSS item.

**Comment by erickok** [comment]
Not sure what Transdroid can do here.... they are just normal notifications.

**Comment by PMaynard** [comment]
With some apps I have, when I get a notification e.g. email I can swipe it away from a locked phone. 
But not with transdroid, which is why I thought you might have done something different.

I am using CM13 and the default email app.

**Comment by erickok** [comment]
No idea what I can do here. There are notification security levels which can be used to show/partialy show/hide sensitive notifications, but nothing that I do would prevent them from being swipable.
