### ISSUE TITLE
Allow completely custom host names / URLs

### ISSUE THREAD

**Issue by Jeimuzu88** [erickok/transdroid#348]
Currently when you're setting up a new server, the port number is automatically appended to the end of server the IP/Hostname. It would be useful to have a "Custom" server type, which would allow the user to type the whole hostname, which doesn't automatically append a port.

This would be useful for people who access their torrent server via a reverse proxy, e.g "example.com/deluge", rather than "example.com:8112". Currently if a URL such as "example.com/deluge" is supplied, a connection URL of "http://example.com/deluge:8112" is generated.

**Comment by erickok** [comment]
You can use a reverse proxy just fine, use the folder setting. In your example, use example.com as host, port 80 and a folder setting /deluge.
