### ISSUE TITLE
Error writing parcel when having too many torrents

### ISSUE THREAD

**Issue by fbarriga** [erickok/transdroid#351]
I'm currently seeding more than 4000 torrents.
If I'm at the main view (torrent list) and I press over a torrent to see the details it works but I get this error on the logs:

```
02-06 17:31:20.819 20960-20960/org.transdroid.full E/JavaBinder: !!! FAILED BINDER TRANSACTION !!!  (parcel size = 1700964)
```

The method involved in the error is `Torrent.writeToParcel` as it's called for every torrent.

**Comment by erickok** [comment]
Dupliocate of #391.
