### ISSUE TITLE
Lint warnings causing display issue, ignored return value of read

### ISSUE THREAD

**Issue by Acmine** [erickok/transdroid#353]
Hi,

I am using Lint to check for warnings in transdroid and found the following warnings may cause unexpected results:
1. **Avoid passing null as the view root (needed to resolve layout parameters on the inflated layout's root element)**
This warning is reported [on line 181 in ListWidgetConfigActivity.java](https://github.com/erickok/transdroid/blob/master/app/src/main/java/org/transdroid/core/widget/ListWidgetConfigActivity.java#L181) and some other locations. Passing null to the parent parameter will lead to unexpected widget display. This has been a widely discussed problem and I've found some related posts on [StackOverflow](http://stackoverflow.com/questions/5026926/why-does-layoutinflater-ignore-the-layout-width-and-layout-height-layout-paramet/5027921#5027921) and [here](https://possiblemobile.com/2013/05/layout-inflation-as-intended/).

2. **Result of `FileInputStream.read()` is ignored**
This warning is reported [on line 108 in VuzeAdapter.java](https://github.com/erickok/transdroid/blob/877ccd0c3a57830dff0d5a6f11e75e4965c57d32/app/src/main/java/org/transdroid/daemon/Vuze/VuzeAdapter.java#L108).
I think ignoring the return value of read() can be problematic as it may not always read all the contents and fill in the buffer. I found a related post [here](https://www.securecoding.cert.org/confluence/display/java/FIO10-J.+Ensure+the+array+is+filled+when+using+read()+to+fill+an+array).

In addition I also found many usage of apache http client which has already been deprecated as suggested [here](https://android-developers.googleblog.com/2011/09/androids-http-clients.html). I think this might cause connection problems sometimes.

Hope this information can help you. :)

**Comment by erickok** [comment]
Thanks for your report.

1. This isn't an easy fix as the target for the view is the action bar, so I cannot just pass that as a parent. Anyway, the theme is already set correctly, so there is no bug.

2. I do not care about the number of bytes read here, as I already read all available.

As per the Apache Http Client usage, while I have worked a bit on a rewrite, a full replacement is a HUGE refactor and would require everything to be retested, etc. So yeah.. not happening any time soon. Plus, while it is deprecated (for good reasons) it is still working just fine.

Cheers for the input!
