### ISSUE TITLE
Latest Deluge broke transdrone 

### ISSUE THREAD

**Issue by yeyeoke** [erickok/transdroid#355]
As stated by the title, lastest update to Deluge (1.3.14) had some added security that broke transdrone. 

Here is a link to Deluge forum that discusses this: 
http://forum.deluge-torrent.org/viewtopic.php?f=7&t=54428

**Comment by marchom** [comment]
As far as I can tell, the guys from Deluge dev added a check for the content type of the http request on the web interface. 

This should be easily fixed by adding
`
            httppost.setHeader("Content-Type", "application/json");
            httppost.setHeader("Accept", "application/json");
`
to
`app/src/main/java/org/transdroid/daemon/Deluge/DelugeAdapter.java line:525;556`

Perhaps someone can test if this fixes it and is backwards compatible. It would be great to get this compatibility issue sorted out.

**Comment by AnnieTheEagle** [comment]
@marchom I actually did this change yesterday but only got around to testing it. Just adding the `httppost.setHeader("content-type", "application/json");` was sufficient.

See Deluge code change [http://git.deluge-torrent.org/deluge/commit/?h=1.3-stable&id=318ab179865e0707d7945edc3a13a464a108d583](here).

**Comment by marchom** [comment]
Yeah, that makes sense. Deluge only checks on the content-type. Good stuff @AnnieTheEagle. I'll wait until F-Droid picks up the new version to try it out.

**Comment by beemo** [comment]
Hi All,

Was this commit added to 2.5.7 ? I'm still seeing these all over my transdroid logs:

```38808 -- Fri Mar 10 15:42:21 PST 2017 -- 3 -- Error: AuthenticationFailure exception: Password error? Server time difference? No (valid) cookie in response and JSON was: ```

Thanks in advance for your help.
bmo

**Comment by AnnieTheEagle** [comment]
I still get alot of failures while trying to refresh Deluge. It doesn't happen with rTorrent based servers.

**Comment by beemo** [comment]
I haven't been able to connect to deluge at all for 2 days, not just
refresh errors.

**Comment by boekhold** [comment]
What are the chances of a 2.5.8 release that includes this fix? I can only assume this affects a lot of users.

**Comment by beemo** [comment]
Here's a re-compiled version of transdroid with the above fix, for anyone not smart enough to use SDKs, Gradle or Android studio. (I was BARELY smart enough / it took me 2 hours to get all the tools working and get a successfully build).

https://www.dropbox.com/s/lwnu7wswze8zbwk/transdroid_3-11-2017.apk?dl=0

**Comment by paulpoco** [comment]
Yes I tried to get Android Studio working on Ubuntu but gave up.  I have made Android apps before(Icon Packs) but that was on Windows 7.

Thanks for making a temp version, will try it out.

**Comment by paulpoco** [comment]
You have to export your settings first, then uninstall, then install the temp version, then import your settings.

**Comment by bicodegas** [comment]
This temp version seems to be working fine. I suppose the new version will end up on f-droid, right?

**Comment by erickok** [comment]
Yes and I'll release an official 2.5.8 version too. Sorry for the slowdowns I'm away for the weekend.

**Comment by Ansem93** [comment]
what's f-droid?

**Comment by AnnieTheEagle** [comment]
@erickok - Will the official 2.5.8 have any fixes for the issues around deluge sometimes not refreshing.

**Comment by beemo** [comment]
@erickok @marchom @AnnieTheEagle - Thanks for addressing. We all appreciate Transdroid, a very convenient app that you provide for free.

@Ansem93 - F-droid is an android package/application manager, similar to the Google App store but specifically for FOSS.  https://f-droid.org/

**Comment by lucifurious** [comment]
ETA on 2.5.8?

**Comment by ksample** [comment]
Thanks for a great app! I use it every day.  I built the latest commit and it connects to Deluge again w/no issues I can see (Nougat on LG V-20).

Thanks again!

**Comment by SweAdelpha** [comment]
The Dropbox link doesn't work anymore. Can some one be so kind to upload the temp version again? Would really appreciate it!

**Comment by beemo** [comment]
Apologies. I restored the download link.

**Comment by SweAdelpha** [comment]
Thank you so much!

**Comment by erickok** [comment]
2.5.8 is released.
