### ISSUE TITLE
Search providers

### ISSUE THREAD

**Issue by svin83** [erickok/transdroid#357]
why was yts.ag removed? why isn't mkvcage and katcr.co added to this?

Is it possible to edit search providers manually?

**Comment by erickok** [comment]
This should really go in https://github.com/erickok/transdroid-search

YTS was disabled as it started using an annoying CloudFlare service that blocks any non-Javascript access. This is crazy as it is a JSON API, so I asked them but never heard about it.

As for the other sites, you can request them (1 issue per site please) at the above linked HitHub project.
