### ISSUE TITLE
SSL client certificate validation

### ISSUE THREAD

**Issue by keschrich** [erickok/transdroid#361]
I have ruTorrent running in a vm environment with SSL client certificate validation enabled.

The certificate is added to my phone, but unfortunately it seems that Transdroid does not make use of it and cannot connect to this server.

**Comment by erickok** [comment]
Transdroid doesn't do anything special with certificates loaded in your phone. If it is a self-signed certificate you are best to add the SHA-1 hash to Transdroid in the Advances Settings.

**Comment by lorek123** [comment]
It would be nice if it should. That's what I'm getting when trying to log in via app:
Sun Oct 13 17:25:57 GMT+02:00 2019 -- 3 -- Error: AuthenticationFailure exception: Password error? Server time difference? No (valid) cookie in response and JSON was: <html>
<head><title>400 No required SSL certificate was sent</title></head>
<body>
<center><h1>400 Bad Request</h1></center>
<center>No required SSL certificate was sent</center>
<hr><center>nginx</center>
</body>
</html>
When I'm trying to log-in via browser it works fine. 
My setup contains Deluge 2.0.3 with nginx as reverse-proxy.

**Comment by lorek123** [comment]
@erickok please reopen as this issue is still valid.
