### ISSUE TITLE
Trandrone on Windows? 

### ISSUE THREAD

**Issue by Ansem93** [erickok/transdroid#362]
There is any hope to see Trandrone on Windows 10 as universal app? 
I really love this app! I find it the best and it's also open source!

**Comment by erickok** [comment]
Sorry I have no such plans, also since I have way too many hobby projects already and am rewriting Transdroid at the moment... sorry!

**Comment by WilliamABradley** [comment]
@Ansem93, I am currently writing an app Called RemoTorr, which has similar features to Transdrone, however, it is a UWP app. 
Transdrone would need a complete re-write for Windows as it is written in Java, which is unsupported by UWP. 

RemoTorr is a UWP App, but could support cross-platform efforts such as Xamarin in the future. I am currently working to support the same clients as Transdrone (Currently, uTorrent/Bittorrent, QBittorrent, Deluge and soon Transmission), as well as Smb Folder mapping, RSS, and more. [Windows Store Link](https://www.microsoft.com/en-us/store/p/remotorr/9nblggh42q62)
