### ISSUE TITLE
Intent

### ISSUE THREAD

**Issue by svin83** [erickok/transdroid#369]
Other apps for browsing and searching for torrents does not recognize transdroid as a torrent application. Examples are TPB-Premium and "torrent search engine"

**Comment by erickok** [comment]
I support normal intents for magnet and torrent links just fine, as long as the extension or mime type is set correctly.

**Comment by svin83** [comment]
It works with transdrone but not with transdroid.

26. apr. 2017 19:27 skrev "Eric Kok" <notifications@github.com>:

**Comment by erickok** [comment]
Do you have both installed? Then you might have chosen Transdrone as the default app. You can reset that in system settings. There's no functional difference on this feature between the two apps.

**Comment by svin83** [comment]
I installed transdrone after transdroid just to see it there was a
difference... And the other apps recognized transdrone right away, but they
never recognized transdroid... Maybe the fault is in the other apps? How
they recognize other apps/intents?

Linked to an app in the app store that works like a charm with Transdrone,
but not with Transdroid.

https://play.google.com/store/apps/details?id=com.paolod.torrentsearch2

26. apr. 2017 19:54 skrev "Eric Kok" <notifications@github.com>:

**Comment by erickok** [comment]
I tried that app and when I choose 'Download with torrent client' it starts with Transdroid just fine.

As a side note, why would you use this app if Transdroid already has search integrated, without all the ads and unnecessary permissions?

**Comment by svin83** [comment]
Yeah. I've had correspondence with the app's creator. They actually
maintain a list of clients rather than use intents. So the fault was with
their app, and Transdroid was added after my request.

Their search app has more/different search providers than transdroid
search, so I use both.

And at the moment it seems the TPB proxy used by Transdroid search is down.

4. mai 2017 10:10 skrev "Eric Kok" <notifications@github.com>:
