### ISSUE TITLE
Deluge 1.3.15 broke connectivity again

### ISSUE THREAD

**Issue by Panderine** [erickok/transdroid#371]
New Deluge version released May 17th breaks connectivity with transdroid.

**Comment by Panderine** [comment]
Sorry.. was something wrong on my side.

**Comment by crafty35a** [comment]
@Panderine Do you know what the fix was on your end? I'm completely unable to connect to deluge 1.3.15, "Internal error building request"

**Comment by Panderine** [comment]
Sorry I don't remember. But I think it was messing with the connection
settings.
