### ISSUE TITLE
Connection issue with rtorrent over Wifi

### ISSUE THREAD

**Issue by c64bob** [erickok/transdroid#372]
Hi, I'm getting "connection error" when trying to connect to an rtorrent instance over wifi. I am running transdrone 2.5.8 on Android 7.1.1, and have rtorrent 0.9.6 running in the cloud. Connection works without a problem if I am using http. It also works without a problem when using https and my phone's mobile connection. However, when I use https and wifi the connection error appears. I have set transdrone to accept all certificates. Still I see this error message appear in my log:

Connection and error log:
1724 -- Sun May 14 15:18:19 GMT+02:00 2017 -- 3 -- Calling system.client_version with params [ ]
1725 -- Sun May 14 15:18:27 GMT+02:00 2017 -- 3 -- de.timroes.axmlrpc.XMLRPCException: org.apache.http.conn.HttpHostConnectException: Connection to https://king.seedhost.eu:443 refused
1726 -- Sun May 14 15:18:27 GMT+02:00 2017 -- 3 -- Calling d.multicall2 with params [ main d.hash= d.name= d.state= d.down.rate= d.up.rate= d.peers_connected= d.peers_not_connected= d.... ]
1727 -- Sun May 14 15:18:27 GMT+02:00 2017 -- 3 -- de.timroes.axmlrpc.XMLRPCException: org.apache.http.conn.HttpHostConnectException: Connection to https://king.seedhost.eu:443 refused
1728 -- Sun May 14 15:18:27 GMT+02:00 2017 -- 3 -- ConnectionError exception: Error making call to d.multicall2 with params [ main d.hash= d.name= d.state= d.down.rate= d.up.rate= d.peers_connected= d.peers_not_connected= d.... ]: de.timroes.axmlrpc.XMLRPCException: org.apache.http.conn.HttpHostConnectException: Connection to https://king.seedhost.eu:443 refused`

**Comment by erickok** [comment]
For security/privacy reasons you might want to contact me directly via mail (transdroid@2312.nl). From what I can see now I cannot get any connection to that domain when using https so it looks like a server configuration issue to me.

Also note that there exists a setting in Transdroid (in Advanced Settings) to set up a local wifi network with ip/port which is used to connect to an alternative (local ip) when on the same network as your server, but in your case (with cloud hosted seedbox) you should not use this at all.
