### ISSUE TITLE
RSS ParseException with zooqle RSS feed

### ISSUE THREAD

**Issue by Jzooor** [erickok/transdroid#373]
I wanted to start using RSS feeds in Transdroid, and I am starting with a user feed from zooqle. I'm getting errors trying to load my feed.

Error in the log is:
RSS feed https://zooqle.com/rss/tv/26nhfurwp8.rss error: org.apache.harmony.xml.ExpatParser$ParseException: At line 39, column 126: not well-formed (invalid token).

I looked over the XML myself and I could not find anything that appeared incorrect. The line/column pointed to appeared to match up with some unescaped ampersands but that was in a URL wrapped in CDATA.

**Comment by erickok** [comment]
That specific URL is working fine for me (now). Perhaps they fixed it or there was some specific torrent with invalid characters.
