### ISSUE TITLE
RSS RARBG Parser error

### ISSUE THREAD

**Issue by lightglitch** [erickok/transdroid#374]
I'm getting the following error 
```
error: org.apache.harmony.xml.ExpatParser$ParseException: At line 6, column 2: mismatched tag
```
with https://rarbg.to/rssdd.php?category=44 RSS but I don't see any error on the XML.

**Comment by lightglitch** [comment]
It looks like rarbg returns forbidden instead of the RSS when using inside Transdroid.

**Comment by erickok** [comment]
Yes... :(
```
<html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
<hr><center>nginx</center>
</body>
</html>
```
It seemed that it requires a User-Agent header to be set, which is a fair requirement, so I added this.
