### ISSUE TITLE
Feature to add or modify header / Transdroid broken with qbittorrent 3.3.13 

### ISSUE THREAD

**Issue by Matth7878** [erickok/transdroid#376]
Transdroid is broken with qbittorrent after a patch to check referer header to implement CSRF defense.
Related commit is : [[WebUI]: Implement CSRF defense ](https://github.com/qbittorrent/qBittorrent/commit/7c2437e5f27c76933c4e1ec3f4734f6cec6c22d8)
And related issue after this commit : [[WebUI] All alternatives WebUI clients are being broken with 3.3.13 except official one](https://github.com/qbittorrent/qBittorrent/issues/6882)

Even though It's likely a solution is going to be offered in qbittorrent one solution seems to add a Origin or Referer header. Adding or modifying header in advanced parameter would be a nice addition to resolve / prevent such problem.

**Comment by bkach** [comment]
It looks like this is addressed in this commit https://github.com/qbittorrent/qBittorrent/commit/8d2fb06f6531aaef6c8179447204ebf1dfba41d6, and it seemed to be merged on june 14th https://github.com/qbittorrent/qBittorrent/pull/6887

The last release was 12 days ago.. so if this was the issue, it should be fixed..

**Comment by speedwaystar** [comment]
can confirm it was fixed in the most recent release of qbittorrent.

**Comment by erickok** [comment]
Thanks for the update. Also closes #380.
