### ISSUE TITLE
Allow nginx proxy_pass (Folder option in Advanced settings is disabled)

### ISSUE THREAD

**Issue by Nindaleth** [erickok/transdroid#377]
I know about #348 and #334 and they unfortunatelly didn't help.

I have an RPi setup to route all external traffic through a single port to the given service based on a resource, e.g. http://mymachine.dyndns.org:12345/resource with several services available this way behind Nginx.

* I can configure my own port in URL just right, but I can't add the resource into it - at that point I get ...dyndns.org:12345/resource:12345
* I can't omit the port from URL either, as then I get ...dyndns.org/resource:12345
* I would love to set the hostname to '...dyndns.org', set the port to '12345' and use the Folder setting '/resource', but the folder setting is disabled for me

Setting up for qbittorrent, using Transdroid 2.5.8. I can use qbittorrent Web UI without any issues, but would like something more user-friendly on the phone.

**Comment by lozbrown** [comment]
Can you use the folder in advanced settings? I have a similar set up working with utorrent server behind nginx..

**Comment by erickok** [comment]
Yes use the folder option.

**Comment by Nindaleth** [comment]
**the folder setting is disabled for me**

**Comment by erickok** [comment]
Hmm yes might be disabled for qBittorrent... Wel check later.

**Comment by okelet** [comment]
Yes, it is disabled for me too, please, re-open the issue.
