### ISSUE TITLE
Refresh and turtle mode buttons too close to each other

### ISSUE THREAD

**Issue by klauf** [erickok/transdroid#379]
Hi all
While refreshing with the button in the taskbar I sometimes activate the turtle mode by mistake. If the buttons were clearly separated the risk would be reduced,what do you think ?
Cheers

**Comment by erickok** [comment]
The buttons are implemented using the default Android (action bar) icon menu. So all buttons like these (typically in the top right of the screen) are standardised in size and paddings.

**Comment by klauf** [comment]
Hi erikok, thanks for your answer. I understand the need of 'standardized' scheme in an os, but still I guess there must be a possibility, is there any 'separator' in android? Or insert a blank 'fake' button? Or move the turtle button on the left of speeds indicators?

**Comment by erickok** [comment]
It is not so much a technical issue, but rather a UI-philosophical one. I do not consider miss clicks a real issue here, especially since the icon will give you feedback about the turtle mode status. Sorry for disagreeing.
