### ISSUE TITLE
Calls to qBittorrent use POST instead of GET; no authorization prior

### ISSUE THREAD

**Issue by cgaeden** [erickok/transdroid#380]
App Version: Transdrone 2.5.8
qBittorrent Version: 3.3.13
OS: Android 7.0
Error: Internal error building request
Network: Wi-Fi - client and WebUI on same subnet
Details:
Wireshark capture shows Transdrone client making HTTP/1.1 POST call with URI '/version/api' prior to authorization call. This is the first call after the TCP handshake, which results in 401 Unauthorized error. Subsequent calls for URIs 'about.html' and '/json/events' results in same error, as login call never appears to be made, and cookie is never set. 
[qBittorrent3.3.13_Transdrone2.5.8_Unauthorized.pcapng.zip](https://github.com/erickok/transdroid/files/1087260/qBittorrent3.3.13_Transdrone2.5.8_Unauthorized.pcapng.zip)

Also, qBittorrent API documentation suggests calls should be made with GET method.

**Comment by StrikeForceZero** [comment]
I can't confirm I'm having the same issue but I have the same environment and getting similar error when it was working a few months ago

**Comment by StrikeForceZero** [comment]
Appears to be fixed with https://github.com/qbittorrent/qBittorrent/pull/6887
Just waiting on the update to be published

**Comment by sledgehammer999** [comment]
I'll try to make the release this weekend.

**Comment by erickok** [comment]
Via #376.
