### ISSUE TITLE
connect to URL without appending any port #

### ISSUE THREAD

**Issue by rylincoln** [erickok/transdroid#381]
I can't figure out how to setup the app to allow me to set the server simply to a URL without the app automatically appending a port to the end of the URL.

i.e.
https://mydomain.org/deluge  is setup with nginx reverse proxy so I don't need to set the port in the app just the server url.  If i delete the port from advanced settings then the app auto appends :8112 to the URL.

Is this possible currently?  Or do i need to change my setup.

Thanks for the awesome software.

**Comment by erickok** [comment]
Use the very first setting under Advanced Settings to enter your port number (note there is no header).

**Comment by kpupp** [comment]
@erickok I'm having the same problem - I don't need to enter a port for the reverse proxy URL, but the app adds one anyway. In the advanced options, there's only a way to specify a different port, not NO port. Unless I'm misunderstanding or missing something.

**Comment by erickok** [comment]
You always connect to some port. If you're connecting over ssl (Https) you should try 443.

**Comment by kpupp** [comment]
This does not work (443 with an HTTPS URL (which for the record is https://qbittorrent.my.domain.tld), even tried 80 just in case). It works no problem with my actual web browser though, and does on the local network.

**Comment by erickok** [comment]
Your browser, even when it's not showing it, also uses 443 for https. There must be another incompatible setting. Did you set the folder/path setting?

**Comment by kpupp** [comment]
I did not. Just the URL to the app, and the settings for the local set up.

**Comment by kpupp** [comment]
For more info (I wanted to make sure I was getting everything written down right): Made sure to double check the WebUI username/password and everything today - even resetting it to be SURE it was right, and it's still not working for me with the URL. The URL the app is generating is:`https://[username]@qb.[subdomain].synology.me:443` -- is that right? I have the following settings:

- IP/hostname: qb.[subdomain].synology.me
- Username: [WebUI username]
- Password: [WebUI password]
- Advanced settings:
- - Port: 443
- - Local Network: [SSID]
- - Local Port: [Local port]
- - Disable auth: [ ]
- - Folder: Empty
- - Connection timeout: default/unset
- - Use SSL: [X]
- - Use SSL on local: [X]
- - Accept all certs: [ ]
- - Custom thumbprint: defualt/unset

Toggling off SSL and using 80 instead if 443 doesn't change anything, nor does Disabling Authentication or Accepting All Certs.

**Comment by kpupp** [comment]
For more info (I wanted to make sure I was getting everything written down right): Made sure to double check the WebUI username/password and everything today - even resetting it to be SURE it was right, and it's still not working for me with the URL. The URL the app is generating is:`https://[username]@qb.[subdomain].[domain].[tld]:443` -- is that right? I have the following settings:

- IP/hostname: qb.[subdomain].[domain].[tld]
- Username: [WebUI username]
- Password: [WebUI password]
- Advanced settings:
- - Port: 443
- - Local Network: [SSID]
- - Local Port: [Local port]
- - Disable auth: [ ]
- - Folder: Empty
- - Connection timeout: default/unset
- - Use SSL: [X]
- - Use SSL on local: [ ]
- - Accept all certs: [ ]
- - Custom thumbprint: defualt/unset

Toggling off SSL and using 80 instead if 443 doesn't change anything, nor does Disabling Authentication or Accepting All Certs. I don't have firewall settings or anything blocking the app/my phone.
