### ISSUE TITLE
Connect to WebUI

### ISSUE THREAD

**Issue by illusaen** [erickok/transdroid#383]
Hello,

I have the webUI for transmission working on my remote server, but can't figure out how to connect transdrone with it. Can the app connect to the web instead of directly to the daemon?

**Comment by erickok** [comment]
For transmission the daemon and web ui are the same process. Transdroid always connects to a web api (such as the web ui here) and I do not see why that would give any issues with Transdroid?

Just point Transdroid to your Transmission web UI and you are good to go.
