### ISSUE TITLE
Torrent file is not added when using FileChooserIntent from another app

### ISSUE THREAD

**Issue by loibi93** [erickok/transdroid#388]
Hello,

I am currently writing an app for a private Tracker, and I am downloading the torrent files to the device. Then I open transdroid with the following code:
`Intent intent = new Intent(Intent.ACTION_VIEW, FileProvider.getUriForFile(context, AUTHORITY, file));
        intent.addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION);
        return Intent.createChooser(intent, context.getString(R.string.file_chooser_message));`

This gives me the option to open the file with transdroid. Sometimes it is working fine, but sometimes I get an error in transdroid saying, that it was not able to open the .torrent file. Also it seems like the app is not connected to my deluge server on those occasions.
Is it possible that the app needs to connect to the server before adding the torrent ?

**Comment by erickok** [comment]
No it should work fine. However, the way file sharing works nowadays on Android via the file provider means that you (as you correctly did) share a temporary permission to access the file. That works fine but only for fresh activity starts. Unfortunately, Transdroid's main activity is `launchMode="singleTop"` and as such intents such as yours can be delivered straight to an already running instance. In that case I get your intent in my `onNewIntent` method but, and this is the problem, the temporary file permission doesn't seem to (always?) work in this case.

So you will see that when Transdroid is not running (such as when you close it using the back button), you Intent will work just fine and the torrent is added, but when it is still in the background it doesn't (might not?) work. To the best of my knowledge there is no solution or workaround to this problem and a limitation of Android's complicated and confusing intent modes together with the ever changing way on how files are shared on Android. 

![](https://media.giphy.com/media/5LU6ZcEGBbhVS/giphy.gif)
