### ISSUE TITLE
Crashing if remote server contains a lot of torrents

### ISSUE THREAD

**Issue by djl** [erickok/transdroid#391]
At around the 1000 torrent mark, Transdroid crashes when trying to view a specific torrent or when switching to another app. When this happens I need to force stop the app before it will begin responding again.

Settings:

* rtorrent: 0.9.6
* rutorrent: 3.6

Log from `Settings > Help`:

    Transdrone 2.5.8 (228)

    Connection and error log:
    13016 -- Wed Sep 27 09:20:50 GMT+01:00 2017 -- 3 -- Calling system.client_version with params [ ]
    13017 -- Wed Sep 27 09:20:51 GMT+01:00 2017 -- 3 -- Calling d.multicall2 with params [  main d.hash= d.name= d.state= d.down.rate= d.up.rate= d.peers_connected= d.peers_not_connected= d.... ]
    13018 -- Wed Sep 27 09:21:18 GMT+01:00 2017 -- 6 -- E: java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1012696 bytes
    13019 -- Wed Sep 27 09:21:18 GMT+01:00 2017 -- 6 -- E: android.os.BinderProxy.transactNative(Native Method)
    13020 -- Wed Sep 27 09:21:18 GMT+01:00 2017 -- 6 -- E: android.os.BinderProxy.transact(Binder.java:615)
    13021 -- Wed Sep 27 09:21:18 GMT+01:00 2017 -- 6 -- E: android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3636)
    13022 -- Wed Sep 27 09:21:18 GMT+01:00 2017 -- 6 -- E: android.app.ActivityThread$StopInfo.run(ActivityThread.java:3802)
    13023 -- Wed Sep 27 09:21:18 GMT+01:00 2017 -- 6 -- E: android.os.Handler.handleCallback(Handler.java:751)
    13024 -- Wed Sep 27 09:21:18 GMT+01:00 2017 -- 6 -- E: android.os.Handler.dispatchMessage(Handler.java:95)
    13025 -- Wed Sep 27 09:21:18 GMT+01:00 2017 -- 6 -- E: android.os.Looper.loop(Looper.java:154)
    13026 -- Wed Sep 27 09:21:18 GMT+01:00 2017 -- 6 -- E: android.app.ActivityThread.main(ActivityThread.java:6186)
    13027 -- Wed Sep 27 09:21:18 GMT+01:00 2017 -- 6 -- E: java.lang.reflect.Method.invoke(Native Method)
    13028 -- Wed Sep 27 09:21:18 GMT+01:00 2017 -- 6 -- E: com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
    13029 -- Wed Sep 27 09:21:18 GMT+01:00 2017 -- 6 -- E: com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
    13030 -- Wed Sep 27 09:21:18 GMT+01:00 2017 -- 6 -- E: android.app.ActivityThread$StopInfo.run(ActivityThread.java:3810)
    13031 -- Wed Sep 27 09:21:18 GMT+01:00 2017 -- 6 -- E: android.os.Handler.handleCallback(Handler.java:751)
    13032 -- Wed Sep 27 09:21:18 GMT+01:00 2017 -- 6 -- E: android.os.Handler.dispatchMessage(Handler.java:95)
    13033 -- Wed Sep 27 09:21:18 GMT+01:00 2017 -- 6 -- E: android.os.Looper.loop(Looper.java:154)
    13034 -- Wed Sep 27 09:21:19 GMT+01:00 2017 -- 6 -- E: android.app.ActivityThread.main(ActivityThread.java:6186)
    13035 -- Wed Sep 27 09:21:19 GMT+01:00 2017 -- 6 -- E: java.lang.reflect.Method.invoke(Native Method)
    13036 -- Wed Sep 27 09:21:19 GMT+01:00 2017 -- 6 -- E: com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
    13037 -- Wed Sep 27 09:21:19 GMT+01:00 2017 -- 6 -- E: com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
    13038 -- Wed Sep 27 09:21:59 GMT+01:00 2017 -- 3 -- Calling system.client_version with params [ ]
    13039 -- Wed Sep 27 09:22:00 GMT+01:00 2017 -- 3 -- Calling d.multicall2 with params [  main d.hash= d.name= d.state= d.down.rate= d.up.rate= d.peers_connected= d.peers_not_connected= d.... ]
    13040 -- Wed Sep 27 09:23:19 GMT+01:00 2017 -- 3 -- Calling system.client_version with params [ ]
    13041 -- Wed Sep 27 09:23:21 GMT+01:00 2017 -- 3 -- Calling d.multicall2 with params [  main d.hash= d.name= d.state= d.down.rate= d.up.rate= d.peers_connected= d.peers_not_connected= d.... ]
    13042 -- Wed Sep 27 09:23:34 GMT+01:00 2017 -- 6 -- E: java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1012696 bytes
    13043 -- Wed Sep 27 09:23:34 GMT+01:00 2017 -- 6 -- E: android.os.BinderProxy.transactNative(Native Method)
    13044 -- Wed Sep 27 09:23:34 GMT+01:00 2017 -- 6 -- E: android.os.BinderProxy.transact(Binder.java:615)
    13045 -- Wed Sep 27 09:23:34 GMT+01:00 2017 -- 6 -- E: android.app.ActivityManagerProxy.activityStopped(ActivityManagerNative.java:3636)
    13046 -- Wed Sep 27 09:23:34 GMT+01:00 2017 -- 6 -- E: android.app.ActivityThread$StopInfo.run(ActivityThread.java:3802)
    13047 -- Wed Sep 27 09:23:34 GMT+01:00 2017 -- 6 -- E: android.os.Handler.handleCallback(Handler.java:751)
    13048 -- Wed Sep 27 09:23:34 GMT+01:00 2017 -- 6 -- E: android.os.Handler.dispatchMessage(Handler.java:95)
    13049 -- Wed Sep 27 09:23:34 GMT+01:00 2017 -- 6 -- E: android.os.Looper.loop(Looper.java:154)
    13050 -- Wed Sep 27 09:23:34 GMT+01:00 2017 -- 6 -- E: android.app.ActivityThread.main(ActivityThread.java:6186)
    13051 -- Wed Sep 27 09:23:34 GMT+01:00 2017 -- 6 -- E: java.lang.reflect.Method.invoke(Native Method)
    13052 -- Wed Sep 27 09:23:34 GMT+01:00 2017 -- 6 -- E: com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
    13053 -- Wed Sep 27 09:23:34 GMT+01:00 2017 -- 6 -- E: com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
    13054 -- Wed Sep 27 09:23:34 GMT+01:00 2017 -- 6 -- E: android.app.ActivityThread$StopInfo.run(ActivityThread.java:3810)
    13055 -- Wed Sep 27 09:23:34 GMT+01:00 2017 -- 6 -- E: android.os.Handler.handleCallback(Handler.java:751)
    13056 -- Wed Sep 27 09:23:34 GMT+01:00 2017 -- 6 -- E: android.os.Handler.dispatchMessage(Handler.java:95)
    13057 -- Wed Sep 27 09:23:34 GMT+01:00 2017 -- 6 -- E: android.os.Looper.loop(Looper.java:154)
    13058 -- Wed Sep 27 09:23:34 GMT+01:00 2017 -- 6 -- E: android.app.ActivityThread.main(ActivityThread.java:6186)
    13059 -- Wed Sep 27 09:23:34 GMT+01:00 2017 -- 6 -- E: java.lang.reflect.Method.invoke(Native Method)
    13060 -- Wed Sep 27 09:23:34 GMT+01:00 2017 -- 6 -- E: com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:889)
    13061 -- Wed Sep 27 09:23:34 GMT+01:00 2017 -- 6 -- E: com.android.internal.os.ZygoteInit.main(ZygoteInit.java:779)
    13062 -- Wed Sep 27 09:23:36 GMT+01:00 2017 -- 3 -- Calling system.client_version with params [ ]
    13063 -- Wed Sep 27 09:23:38 GMT+01:00 2017 -- 3 -- Calling d.multicall2 with params [  main d.hash= d.name= d.state= d.down.rate= d.up.rate= d.peers_connected= d.peers_not_connected= d.... ]

I'm not sure if this enough information. If any required information is missing let me know and I'll try to dig it up.

**Comment by erickok** [comment]
The upcoming release should fix this, thanks to a PR merged (but not yet release... sorry) a while ago: https://github.com/erickok/transdroid/pull/350

**Comment by djl** [comment]
The newest release still has the same issue. I cannot view individual torrents or switch apps without a crash. The same error appears in the log:

    -- 6 -- E: java.lang.RuntimeException: android.os.TransactionTooLargeException: data parcel size 1281756 bytes
    -- 6 -- E: android.os.BinderProxy.transactNative(Native Method)
    -- 6 -- E: android.os.BinderProxy.transact(Binder.java:764)
    -- 6 -- E: android.app.IActivityManager$Stub$Proxy.activityStopped(IActivityManager.java:4623)
    -- 6 -- E: android.app.ActivityThread$StopInfo.run(ActivityThread.java:3934)
    -- 6 -- E: android.os.Handler.handleCallback(Handler.java:790)
    -- 6 -- E: android.os.Handler.dispatchMessage(Handler.java:99)
    -- 6 -- E: android.os.Looper.loop(Looper.java:164)
    -- 6 -- E: android.app.ActivityThread.main(ActivityThread.java:6494)
    -- 6 -- E: java.lang.reflect.Method.invoke(Native Method)
    -- 6 -- E: com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
    -- 6 -- E: com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
    -- 6 -- E: android.app.ActivityThread$StopInfo.run(ActivityThread.java:3950)
    -- 6 -- E: android.os.Handler.handleCallback(Handler.java:790)
    -- 6 -- E: android.os.Handler.dispatchMessage(Handler.java:99)
    -- 6 -- E: android.os.Looper.loop(Looper.java:164)
    -- 6 -- E: android.app.ActivityThread.main(ActivityThread.java:6494)
    -- 6 -- E: java.lang.reflect.Method.invoke(Native Method)
    -- 6 -- E: com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
    -- 6 -- E: com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)

Although it does load much faster now, so that's nice :smiley:

**Comment by erickok** [comment]
How many torrents do you have? Indeed it crashes because the full list of torrents is put in an Android Parcel and it doesn't fit as it would be more than 1MB...

**Comment by djl** [comment]
Yeah, I have lots of torrents (> 1000). I'm probably in the minority of users.

Crashing when switching apps isn't a big deal. I'm usually finished with whatever I'm doing at that point. Plus, with the new speed increase it's not an issue just to open the app again. The real pain point is not being able to view or interact with individual torrents.

**Comment by erickok** [comment]
Totally a bug, though it goes into the base of how the app currently works (not storing data locally but relying on parcelling of results to give data to the details activity). So for sure needs to be fixed, but in a future refactor.

**Comment by drewbitt** [comment]
Just wanted to put my +1 in since I too get the same issue with a little over 1000. So it's not just djl :) It essentially makes the app unusable since I cant click on any torrents, exit the app or sometimes even open settings without crashes.

**Comment by brokensbone** [comment]
This is also a pain for me.

I basically (can) only use transdroid to add new torrents, which works fine, but it still crashes every time I swap to a different app.

If the full fix involves a major refactor, maybe the app's onPause could at least gracefully fail and just discard the data it wants to bundle, rather than just crashing.

**Comment by amazingdash** [comment]
Hi @erickok, thanks for your work, this app looks great! However, I'm unable to use it because I also have over a thousand torrents and I see the same `android.os.TransactionTooLargeException` as other people.
Do you have any plans to work on this in the near future?

**Comment by dgw** [comment]
I believe this was incorrectly closed by 78dd4bd (which appears to address #463, not this issue).

**Comment by erickok** [comment]
Yeah one commit referred to the wrong (this) issue but regardless indeed it
should be fixed. (hacky... but if it unblocks you, I'm happy)

**Comment by dgw** [comment]
Phone just updated Transdrone. Sweet mother of mochi, it works! I can actually view details again! :tada: :raised_hands: :tada:
