### ISSUE TITLE
Questions about custom ports

### ISSUE THREAD

**Issue by yevision94** [erickok/transdroid#392]
Hi,This software is really easy to use. At present, I have a question in the custom port here is that no matter how trll or aria2 above the use of custom port, whether I was in the LAN or remote can not connect, only the default port. But because the remote vps 8080 port is occupied, I do not know how to solve, or can increase the port settings?

ps: Please forgive my low level of English!

**Comment by erickok** [comment]
Enter the custom port in the Port setting, which is the first under Advanced Settings. (Note that there is no header.)

**Comment by yevision94** [comment]
@erickok ，Really thank you, I just click on the local port number, directly to the port number ignored, really thought it was the title.

**Comment by jeroen7s** [comment]
This is not working for me
I have the qbittorrent web ui behind a custom domain, with https over port 443
Adding "local port" doesn't seem to be correct, it is ignored and it just uses 8080 instead.
![IMG_20201102_212158](https://user-images.githubusercontent.com/10954827/97915310-91c38b00-1d51-11eb-90e3-84a535f247da.jpg)
![IMG_20201102_212116](https://user-images.githubusercontent.com/10954827/97915350-a2740100-1d51-11eb-97b8-4df97e8d136e.jpg)
