### ISSUE TITLE
rTorrent cannot be connected to Transdroid

### ISSUE THREAD

**Issue by Drsela** [erickok/transdroid#393]
Hi

I've searched the web for any guides on how to setup Transdroid with rTorrent and found a couple, But none of them seem to work as intended.

I have rTorrent running at IP_ADRESS:9898 (non https) and at https://IP_ADRESS/ruTorrent. I am using Nginx as webserver and basic HTTP Auth. Nginx redirects port 80 to port 443.

I can connect to IP_ADRESS:9898 with the following settings:
Server Type: rTorrent
IP: IP_ADRESS
User name: UN
Password: PW
Advanced:
- Port Number: 9898
- SCGI mount point: /plugins/httprpc/action.php
When I click the settings button from the main menu it's formatted as such: http://UN@IP_ADRESS:9898/plugins/httprpc/action.php

But I cannot connect to https://IP_ADRESS/ruTorrent with the following settings:
Server Type: rTorrent
IP: IP_ADRESS/ruTorrent
User name: UN
Password: PW
Advanced:
- SCGI mount point: /plugins/httprpc/action.php
- Use SSL: Checked
When I click the settings button from the main menu it's formatted as such: https://UN@IP_ADRESS/ruTorrent:443/plugins/httprpc/action.php.

The problem is that Transdroid adds ':443'.
I can access https://IP_ADRESS/ruTorrent/plugins/httprpc/action.php trough all my browsers (Microsoft Edge, Google Chrome, Opera Next, Firefox), but https://IP_ADRESS/ruTorrent:443/plugins/httprpc/action.php gives me an error ('No input file specified.').

Here's a screenshot. ruLocal is working ruTorrent is not.

![screenshot_20171018-215155](https://user-images.githubusercontent.com/24656557/31739655-e3a737e2-b44e-11e7-832a-cf71fd9330c1.jpg)

How the heck do I remove the ':443'? :)

I'm using Transdroid version 2.5.8.

Best Regards

**Comment by erickok** [comment]
Use the port number setting, which is the first setting under Advanced Settings. (Note there is no header)

**Comment by Drsela** [comment]
The problem is that when I enable SSL, it automatically adds :433 to the url as seen in the screenshot. The port options has no value.

It should go to https://IP_ADRRSS/ruTorrent/.... But it goes to https://IP_ADRESS/ruTorrent:443/....

**Comment by Drsela** [comment]
It seems like I accidently closed the issue.

Here's a screenshot of the port setting, which you can see is undefined. 

https://i.imgur.com/du16o80.png

**Comment by erickok** [comment]
The port is fine (https defaults on port 443) but the problem is that you have set the IP/host name incorrectly. You should ONLY enter the IP there, not append /ruTorrent. And then set the SCGI mount point to /ruTorrent/plugins/httprpc/action.php

**Comment by Drsela** [comment]
Alright, that appears to be working.

Sorry for the issue.

Thanks for the quick response! 

Best Regards.
