### ISSUE TITLE
Feature Request: Seeding Time

### ISSUE THREAD

**Issue by kashifsmalik** [erickok/transdroid#395]
For a selected torrent, we can see the time it has been active since; however, there's no way to see how long it has been seeding. May be you can place this info right under 'since .... ' at the top left corner, and add it as an advanced setting to be turned on (assuming that not everybody would be interested in knowing the seeding duration).

Thanks in advance. Your responses to issues I raised earlier has been quick. Thank you for developing and maintaining a very useful app.

**Comment by erickok** [comment]
I can't remember seeing any client that exposes this info... Do you know of anyone at all?

**Comment by kashifsmalik** [comment]
Apologies for not responding in time. The following screenshot is from Deluge client. This info shows up in thin client as well as thick client.

![2017-11-24_121758](https://user-images.githubusercontent.com/15194335/33818256-af5a1af4-de65-11e7-9bf4-eb6a34966076.jpg)
