### ISSUE TITLE
Allow folder (reverse proxy) setting for Aria2

### ISSUE THREAD

**Issue by qakcn** [erickok/transdroid#397]
I'm using nginx reverse proxy to Transmission to offer HTTPS visiting from internet. And I want to directly accessing Transmission from local network using its own port which doesn't have SSL certificate.
It's better to provide individual SSL settings for local network, and maybe individual dir path settings for local?

PS: Aria2 cannot set dir path, that not's good for nginx reverse proxy.

Thanks for hearing.

**Comment by erickok** [comment]
While I understand your situation, for such a specific setup you might consider just adding two server configurations?

**Comment by qakcn** [comment]
That's a kind of solution, thank you. But support for Aria2 dir path is really needed. I have to set a reverse proxy from `/jsonrpc` to Aria2‘s port 6800 at present. What I want is `/aria2/jsonrpc`.

**Comment by erickok** [comment]
Hmm that is a different issue altogether. I can open up the 'folder' setting for this.
