### ISSUE TITLE
Active and inactive  bug

### ISSUE THREAD

**Issue by asdf12303116** [erickok/transdroid#398]
when turn on the "pref_dormantasinactive"  
Some torrents have upload speed,no download speed. These torrents are considered to be unactive.

**Comment by asdf12303116** [comment]
![screenshot_20171130-003637](https://user-images.githubusercontent.com/14955115/33387498-642b5846-d568-11e7-9396-260c8e4112f3.png)
![screenshot_20171130-003627](https://user-images.githubusercontent.com/14955115/33387499-648fa440-d568-11e7-972e-18a29551684a.png)
like this torrent

**Comment by erickok** [comment]
I cannot reproduce this... are you sure you selected Active and not just Uploading? (Which really should be called Seeding... that is probably the confusion!)
