### ISSUE TITLE
Port number

### ISSUE THREAD

**Issue by snowydane** [erickok/transdroid#400]
Hi there,

I tried setting up transdroid on my phone, but it defaults to port 8112 - while my server is running the deluge daemon on another port. I can't find the option to change it=

**Comment by dsiminiuk** [comment]
normally in apps like these you would put the port number at the end of the hostname like youhost:8113 or whatever.

I'm having a similar problem where whatever port I wish to use in utorrent is appended by :8080. myhost:9999:8080.

You should be able to define your own ports.

**Comment by erickok** [comment]
Use the dedicated port setting, which is the first in Advanced Settings.
