### ISSUE TITLE
Add File Doesn't Work

### ISSUE THREAD

**Issue by alonalbert** [erickok/transdroid#405]
Adding a file doesn't work, at least not on my Nexus 6P running Android O.

I am using the system file picker, not external file manager is installed and it won't let me select an files.

See screenshot:
![add-file-disabled](https://user-images.githubusercontent.com/1660304/34475213-a8d02ce4-ef92-11e7-81f7-0218ab957fe3.png)

The problem seems to be the use of "file/*" as a MIME type in FilePickerHelper.

Changing it to "application/x-bittorrent" fixes it on my device at least though I'm not 100% sure this is the best fix.

This screenshot shows the file enabled after applying the fix:
![add-file-fixed](https://user-images.githubusercontent.com/1660304/34475263-03c5e1a2-ef93-11e7-97f9-daa0b30d4649.png)

I'll submit a pull request shortly.

**Comment by erickok** [comment]
Seems good, though I would have to test on older devices for compatibility.

**Comment by alonalbert** [comment]
SG

FYI, "*/*" also works but accepts any file.

**Comment by erickok** [comment]
Dup of #382

**Comment by erickok** [comment]
Fixed via #406
