### ISSUE TITLE
Add automatically a / when putting a SCGI mount point

### ISSUE THREAD

**Issue by Kcchouette** [erickok/transdroid#412]
In the case of rtorrent:
when adding a scgi mount point, we need to write a `/`, else: 

- the apps crash and do not start (we need to flush all the cache)
- and we see in the **Servers** section: http://xxx@xxxxSCGIENDPOINT (without /)

I purpose to put a `/` if it's not present at the first char of getFolder() here: https://github.com/erickok/transdroid/blob/c09807f191bb36d2eb3c46d5d1043755191182cb/app/src/main/java/org/transdroid/core/app/settings/ServerSetting.java#L243

Thank you

**Comment by erickok** [comment]
The code you point to actually is only what is displayed to the user, not what is practically used. I think this SHOULD indeed reflect the setting used. Contrary, I can see how it's annoying that you manually have to go back and fix it and certainly the app should not crash.

**Comment by erickok** [comment]
Fixed in https://github.com/erickok/transdroid/commit/dbbed95cda99f0b0358a160dfc310697b8ca8942

**Comment by Kcchouette** [comment]
Thank you :)
