### ISSUE TITLE
App Crashes on Orientation Change in PreferenceCompatActivity

### ISSUE THREAD

**Issue by alonalbert** [erickok/transdroid#413]
Repro steps:

Open app
Open Settings
Rotate device.
Crash

Root cause is that PreferenceCompatActivity#onCreate() calls super.onCreate() before creating field acd:

	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		acd = AppCompatDelegate.create(this, this);
		acd.onCreate(savedInstanceState);
	}

And the base class PreferenceActivity#onCreate() ends up calling setTitle() when triggered from an orientation change. 

	@Override
	public void setTitle(CharSequence title) {
		super.setTitle(title);
		acd.setTitle(title);
	}

This of course results in an NPE.

It's not clear to me if the solution is to protect the acd.setTitle() call with a null check or simply remove the PreferenceCompatActivity#setTitle() entirely. It only seems to be called only when a configuration change is made anyway (and crashes) and the title seems to be set regardless.

01-29 12:48:09.032 11234 11234 E AndroidRuntime: Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'android.view.Window$Callback android.view.Window.getCallback()' on a null object reference
01-29 12:48:09.032 11234 11234 E AndroidRuntime: 	at android.support.v7.app.AppCompatDelegateImplBase.<init>(AppCompatDelegateImplBase.java:68)
01-29 12:48:09.032 11234 11234 E AndroidRuntime: 	at android.support.v7.app.AppCompatDelegateImplV7.<init>(AppCompatDelegateImplV7.java:146)
01-29 12:48:09.032 11234 11234 E AndroidRuntime: 	at android.support.v7.app.AppCompatDelegateImplV11.<init>(AppCompatDelegateImplV11.java:28)
01-29 12:48:09.032 11234 11234 E AndroidRuntime: 	at android.support.v7.app.AppCompatDelegateImplV14.<init>(AppCompatDelegateImplV14.java:41)
01-29 12:48:09.032 11234 11234 E AndroidRuntime: 	at android.support.v7.app.AppCompatDelegateImplV23.<init>(AppCompatDelegateImplV23.java:29)
01-29 12:48:09.032 11234 11234 E AndroidRuntime: 	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:188)
01-29 12:48:09.032 11234 11234 E AndroidRuntime: 	at android.support.v7.app.AppCompatDelegate.create(AppCompatDelegate.java:172)
01-29 12:48:09.032 11234 11234 E AndroidRuntime: 	at org.transdroid.core.gui.settings.PreferenceCompatActivity.<init>(PreferenceCompatActivity.java:17)
01-29 12:48:09.032 11234 11234 E AndroidRuntime: 	at org.transdroid.core.gui.settings.MainSettingsActivity.<init>(MainSettingsActivity.java:60)
01-29 12:48:09.032 11234 11234 E AndroidRuntime: 	at org.transdroid.core.gui.settings.MainSettingsActivity_.<init>(MainSettingsActivity_.java:26)
01-29 12:48:09.032 11234 11234 E AndroidRuntime: 	at java.lang.Class.newInstance(Native Method)
01-29 12:48:09.032 11234 11234 E AndroidRuntime: 	at android.app.Instrumentation.newActivity(Instrumentation.java:1174)
01-29 12:48:09.032 11234 11234 E AndroidRuntime: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2669)
01-29 12:48:09.032 11234 11234 E AndroidRuntime: 	... 9 more

**Comment by erickok** [comment]
Seems like it's safe to remove the setTitle call. Titles are already a bit bugged (for sub preference screens). Something to fix some time.
