### ISSUE TITLE
Error when opening downloaded .torrent file in Chrome

### ISSUE THREAD

**Issue by ARS81** [erickok/transdroid#416]
Occasionally If I click a torrent link on my Phone with Chrome, it downloads the torrent file and when I try to open it, Transdroid comes up but then shows a red error in the bottom saying "Internal error building request" (error_jsonrequesterror in strings.xml). Same with Transdroid 2.5.8 and either latest 2.5.9.

Strange that sometimes it works as excepted, sometimes not. I couldn't find out why... It's the same using my phone (OnePlus3, Android 8.0) or wife's Galaxy S7 (Android 7.0). 

Copied from the log it says:
`5160 -- Sat Feb 10 22:35:29 GMT+01:00 2018 -- 3 -- ParsingFailed exception: org.json.JSONException: Value invalid of type java.lang.String cannot be converted to JSONObject`

My server connection is my uTorrent client (3.5.1) running on a Windows 10 machine with web UI enabled on port 8085.

Also interesting (maybe related) when I click on the green add (+) ikon in Transdroid then browse to the Download directory (internal storage), the downloaded .torrent files are there but all of them are grayed, not clickable. Both Chrome and Transdroid has granted access to Storage.

So I used to download with add (+) / url copied, that's works always.
Everything works smooth except this.
Any idea?
Thanks

**Comment by erickok** [comment]
I have seen this before with people using uTorrent. Can you actually add torrents via the uTorrent Web UI's Add by file feature manually? uTorrent seems to send some kind of raw response instead of the expected success JSON. Perhaps an error. Could you send a full log, to see if the token call went okay beforehand? If you totally kill Transdroid and add a torrent by file (effectively making the add command the first to be executed) doe it work? What if you can in the app first and do a list refresh?

**Comment by friskyplatypus** [comment]
I have actually had this problem for a long time.  I also use uTorrent. I've found that if I force close transdroid and then open the torrent file again, it is almost always successful in adding.  As far as the webui, in my case, it is perfectly functional. Transdroid is as well, except in this particular function. I'll also mention that it is independent of browser. As long as transdroid already is running, opening the torrent file with a file explorer still yields the same result. Lately,  I've been using another application that also has the same problem with adding initially but offers the option to refresh the server which successfully adds the torrent so I'm not sure if that might be an option.  

I've used your program for many years and have donated in the past.  I greatly appreciate all your hard work.  Even though I do have that other app, it's set only as the default for opening the files but for everything else your application is far superior.

**Comment by ARS81** [comment]
@erickok I did the Web UI's add by file test you asked. It was OK 4/4 times. Don't know if it helps, but looking at Chrome's DevTools Netwrok tab the JSON response of the "add-file" action was always just:
`{"build":44358}`

With the new version Transdroid 2.5.10 (230) it feels much better but the error still comes up rarely. I'm trying to find a step-by-step situation which leads to this error. I already have some tips but needs more testing. I will get back soon with the results.

Here's the full log right after the error but seems not very usefull:
```
Transdroid 2.5.10 (230)
uTorrent settings: http://***@***.ddns.net:8085

Connection and error log:
5635 -- Wed Feb 28 23:05:19 GMT+01:00 2018 -- 3 -- Creating adapter for ARS-PC of type uTorrent: connected to MBHF24 and configured local network is MBHF24
5636 -- Wed Feb 28 23:06:11 GMT+01:00 2018 -- 3 -- Creating adapter for ARS-PC of type uTorrent: connected to MBHF24 and configured local network is MBHF24
5637 -- Wed Feb 28 23:14:21 GMT+01:00 2018 -- 3 -- Creating adapter for ARS-PC of type uTorrent: connected to MBHF24 and configured local network is MBHF24
5638 -- Wed Feb 28 23:17:36 GMT+01:00 2018 -- 3 -- Creating adapter for ARS-PC of type uTorrent: connected to MBHF24 and configured local network is MBHF24
5639 -- Wed Feb 28 23:17:36 GMT+01:00 2018 -- 3 -- Boot signal received, starting server and rss checker background services
5640 -- Wed Feb 28 23:17:36 GMT+01:00 2018 -- 3 -- Boot signal received, starting app update checker service
5641 -- Wed Feb 28 23:17:36 GMT+01:00 2018 -- 3 -- Creating adapter for ARS-PC of type uTorrent: connected to MBHF24 and configured local network is MBHF24
5642 -- Wed Feb 28 23:17:41 GMT+01:00 2018 -- 3 -- Try to parse Bit**men (http://bit**men.be/personalrss/***.xml)
5643 -- Wed Feb 28 23:17:41 GMT+01:00 2018 -- 3 -- Skip the update service, as we already checked the last 24 hours (or to be exact at Wed Feb 28 22:25:41 GMT+01:00 2018).
5644 -- Wed Feb 28 23:17:41 GMT+01:00 2018 -- 3 -- Bit**men has no unread items
5645 -- Wed Feb 28 23:18:14 GMT+01:00 2018 -- 3 -- Creating adapter for ARS-PC of type uTorrent: connected to MBHF24 and configured local network is MBHF24
5646 -- Wed Feb 28 23:18:35 GMT+01:00 2018 -- 3 -- Creating adapter for ARS-PC of type uTorrent: connected to MBHF24 and configured local network is MBHF24
5647 -- Wed Feb 28 23:18:35 GMT+01:00 2018 -- 3 -- ParsingFailed exception: org.json.JSONException: Value invalid of type java.lang.String cannot be converted to JSONObject
5648 -- Wed Feb 28 23:18:53 GMT+01:00 2018 -- 3 -- Creating adapter for ARS-PC of type uTorrent: connected to MBHF24 and configured local network is MBHF24
```
and

>  If you totally kill Transdroid and add a torrent by file (effectively making the add command the first to be executed) doe it work?

Yes, it was OK 3/3 times. (kill -> add, kill -> add, kill -> add (were always OK))

**Comment by twig** [comment]
This has got me baffled. Something seems to be failing auth?

I've looked up a few implementations and it _looks_ right in comparison.

* https://github.com/twig/webui/blob/master/src/js/main.js
* https://stackoverflow.com/questions/20827861/add-torrent-with-web-api
* https://forum.utorrent.com/topic/77828-add-file-difficulty/
* https://github.com/leeroybrun/node-utorrent-api/blob/master/lib/utorrent.js

Even tried using OkHttp in case it was a bug in the legacy Apache http library and it didn't work.

**Comment by twig** [comment]
Alright, had some time to investigate a bit further and I found the cause for the issue.

* `src/main/java/org/transdroid/daemon/Utorrent/UtorrentAdapter.java` has `httpclient` which is created every time a new adapater is created
* It is missing a CookieStore, set via `httpclient.setCookieStore(new BasicCookieStore())`
* The httpClient and cookie store do not persist because there are many existences of an adapter at any time
* Upon upload, the cookie store is empty (it should contain a GUID, not sure when it's set)
* When I made the `httpClient` or `cookieStore` static, the upload succeeded but crashed afterwards, so I'm assuming I broke something else

I'm not sure what the general practice is on Android for reusing instances of HttpClient, but having a persistent cookie store helps.

This patch seems to fix the upload issue: https://github.com/erickok/transdroid/pull/565
