### ISSUE TITLE
Android 7 - rTorrent "Error during communication; check your connection"

### ISSUE THREAD

**Issue by adrianomatousek** [erickok/transdroid#418]
Hi, I have many friends that also say that this error occurs on Android 7 and above. Is there any way to fix it? I believe this is an http error after reading through source code. It doesn't even load up any items. Just gives the error and doesn't connect.

**Comment by erickok** [comment]
This is a general error. Can you send an Error report via the Help menu in Transdroid?

**Comment by adrianomatousek** [comment]
@erickok Yes, I've now sent the error report

**Comment by erickok** [comment]
I have responded directly to your mail as it seems a config issue.
