### ISSUE TITLE
App notification to download 2.5.10 points to 2.5.9

### ISSUE THREAD

**Issue by masenf** [erickok/transdroid#420]
I'm currently running transdroid 2.5.9 on Android 8.1 and receive notification to download new transdroid 2.5.10.

When I click on notification it downloads 2.5.9.

When I go to the main website and click download .apk it downloads 2.5.9

**Comment by erickok** [comment]
I think this was just temporary while the webserver not yet reloaded. http://transdroid.org/latest points to 2.5.10 now.

**Comment by erickok** [comment]
Nope ti was human error, thanks for the heads up!

**Comment by masenf** [comment]
Thanks for transdroid. It is one of my must-have apps and I appreciate the active development. Consider taking cryptocurrency donations on your website.
