### ISSUE TITLE
internal error building request 

### ISSUE THREAD

**Issue by ermethic** [erickok/transdroid#423]
on Transdrone, since updating to 2.5.10 it cannot connect to my Transmission server anymore. error is "internal error building request".
Never had this issue before, it worked flawlessly until now.

**Comment by ermethic** [comment]
from the error log, I get this over and over (edited out the domain name) :

39129 -- Wed Feb 21 00:15:57 GMT+02:00 2018 -- 3 -- Execute session-get request to https://***.***.info:443/rpc
39130 -- Wed Feb 21 00:15:57 GMT+02:00 2018 -- 3 -- Received content response starting with <!DOCTYPE html>
<html>
	<head>
		<meta http-equiv="Content-Type" content="text/html; charset=utf-8" ...
39131 -- Wed Feb 21 00:15:57 GMT+02:00 2018 -- 3 -- Error: org.json.JSONException: Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject
39132 -- Wed Feb 21 00:15:57 GMT+02:00 2018 -- 3 -- ParsingFailed exception: org.json.JSONException: Value <!DOCTYPE of type java.lang.String cannot be converted to JSONObject

**Comment by erickok** [comment]
Hmm what type of authentication are you using?

**Comment by ermethic** [comment]
It's hosted on nginx with reverse proxy redirect (https://< domain >:443 to < local IP >:9091).
It uses the default transmission rpc authentication... here's an excerpt from the config file :

```
    "rpc-authentication-required": true,
    "rpc-bind-address": "0.0.0.0",
    "rpc-enabled": true,
    "rpc-host-whitelist": "",
    "rpc-host-whitelist-enabled": true,
    "rpc-password": "**********",
    "rpc-port": 9091,
    "rpc-url": "/transmission/",
    "rpc-username": "admin",
    "rpc-whitelist": "127.0.0.1",
    "rpc-whitelist-enabled": false

**Comment by ermethic** [comment]
Here's also the proxy nginx redirect setup, in case it helps.
This one worked for years until now, and it also works for other subdomains, on the same server:

```
server {
	listen 443 ssl;

	root /config/www;
	index index.html index.htm index.php;

	server_name transmission.*;

	ssl_certificate /config/keys/letsencrypt/fullchain.pem;
	ssl_certificate_key /config/keys/letsencrypt/privkey.pem;
	ssl_dhparam /config/nginx/dhparams.pem;
	ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA';
	ssl_prefer_server_ciphers on;

	client_max_body_size 0;

	location / {
		auth_basic off;
		auth_basic_user_file /config/nginx/.htpasswd;
		include /config/nginx/proxy.conf;
		proxy_pass http://192.168.1.100:9091;	
	}
}

**Comment by erickok** [comment]
So what's changed is that I now send the basic authentication credentials
preemptively, which means the network layer doesn't try an unauthenticated
call first. I'm not sure why but it seems that's incompatible with your
reverse proxy. Ironically it was done to fix an issue with reverse proxies.

What is the authorisation type, since you specified

auth_basic off;

?


On 22 Feb 2018 2:06 p.m., "ermethic" <notifications@github.com> wrote:

Here's also the proxy nginx redirect setup, in case it helps.
This one worked for years until now, and it also works for other
subdomains, on the same server:

server {
	listen 443 ssl;

	root /config/www;
	index index.html index.htm index.php;

	server_name transmission.*;

	ssl_certificate /config/keys/letsencrypt/fullchain.pem;
	ssl_certificate_key /config/keys/letsencrypt/privkey.pem;
	ssl_dhparam /config/nginx/dhparams.pem;
	ssl_ciphers 'ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA';
	ssl_prefer_server_ciphers on;

	client_max_body_size 0;

	location / {
		auth_basic off;
		auth_basic_user_file /config/nginx/.htpasswd;
		include /config/nginx/proxy.conf;
		proxy_pass http://192.168.1.100:9091;	
	}
}

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/erickok/transdroid/issues/423#issuecomment-367674735>,
or mute the thread

**Comment by ermethic** [comment]
Auth is specified in transmission settings.json as quoted above, they're the default transmission rpc authentication settings.

**Comment by erickok** [comment]
What I mean is that Transmission uses http basic auth but your reverse proxy specifies auth_basic off, so now I wonder if your reverse proxy setup passes through the credentials or not.
(Your log includes the first characters of what seems to be an html error page of some sorts being returned, except a proper Transmission response.) Can you see in the nginx logs if you see the requests from Transdroid showing up in the error log (or success)?

**Comment by ermethic** [comment]
I eliminated the two 'auth' lines from the proxy settings, but the behaviour stays the same.
No errors in nginx log, and the entries that appear are in access.log like follows:

```
***.***.***.*** - admin [22/Feb/2018:16:51:10 +0200] "POST /transmission/rpc HTTP/1.1" 200 76 "https://***.***.info/transmission/web/" "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/63.0.3239.132 Safari/537.36"

**Comment by erickok** [comment]
Hmm it looks like Transdroid tries to connect to /rpc and after that gets redirected to /transmission/web/. That will respond (incorrectly) with the UI web page. Actually Transdroid should connect to /transmission/rpc (which it will by default). Did you maybe override the folder setting in Transdroid's advanced settings? If so, can you try to clear this or use `/transmission`?

To the best of my knowledge this is an issue with a reverse proxy, and while I hope I can help you, it is a bit beyond what I can do from Transdroid if your specific setup doesn't work with it. (I just tested with a vanilla Transmission web interface and not reverse procy and the basic auth works fine.)

**Comment by ermethic** [comment]
This is the error that gets issued when you access https://***.***.***/transmission/rpc/ :
```
409: Conflict
Your request had an invalid session-id header.

To fix this, follow these steps:

When reading a response, get its X-Transmission-Session-Id header and remember it
Add the updated header to your outgoing requests
When you get this 409 error message, resend your request with the updated header
This requirement has been added to help prevent CSRF attacks.

X-Transmission-Session-Id: cHEAInT93edQ79WiBFz83cnB3jWZsa3MFNs3X03a2nzK0BhU

**Comment by erickok** [comment]
That's normal the first request. Transdroid should pick up the sesison id
and make a new request with the header attached.

**Comment by ermethic** [comment]
Yes, it seems like it... you think it can be resolved in the next version ?

**Comment by erickok** [comment]
I am not even saying there is a bug... Why do you think there is a bug?
I think the original requests that give a 301 response are already incorrect. Can you check the folder setting in Transdroid? Or even export our settings and post them here (anonymised)?

**Comment by ermethic** [comment]
It's not a 301, it's a 409, it requires making a second request with the session id.
Here's the full settings.json of transmission:
```
{
    "alt-speed-down": 50,
    "alt-speed-enabled": false,
    "alt-speed-time-begin": 540,
    "alt-speed-time-day": 127,
    "alt-speed-time-enabled": false,
    "alt-speed-time-end": 1020,
    "alt-speed-up": 50,
    "bind-address-ipv4": "0.0.0.0",
    "bind-address-ipv6": "::",
    "blocklist-enabled": false,
    "blocklist-url": "http://www.example.com/blocklist",
    "cache-size-mb": 4,
    "dht-enabled": true,
    "download-dir": "/downloads/complete",
    "download-queue-enabled": true,
    "download-queue-size": 5,
    "encryption": 1,
    "idle-seeding-limit": 30,
    "idle-seeding-limit-enabled": false,
    "incomplete-dir": "/downloads/incomplete",
    "incomplete-dir-enabled": true,
    "lpd-enabled": false,
    "message-level": 2,
    "peer-congestion-algorithm": "",
    "peer-id-ttl-hours": 6,
    "peer-limit-global": 200,
    "peer-limit-per-torrent": 50,
    "peer-port": 51413,
    "peer-port-random-high": 65535,
    "peer-port-random-low": 49152,
    "peer-port-random-on-start": false,
    "peer-socket-tos": "default",
    "pex-enabled": true,
    "port-forwarding-enabled": true,
    "preallocation": 1,
    "prefetch-enabled": true,
    "queue-stalled-enabled": true,
    "queue-stalled-minutes": 30,
    "ratio-limit": 2,
    "ratio-limit-enabled": true,
    "rename-partial-files": true,
    "rpc-authentication-required": true,
    "rpc-bind-address": "0.0.0.0",
    "rpc-enabled": true,
    "rpc-host-whitelist": "",
    "rpc-host-whitelist-enabled": true,
    "rpc-password": "****************",
    "rpc-port": 9091,
    "rpc-url": "/transmission/",
    "rpc-username": "*******",
    "rpc-whitelist": "127.0.0.1",
    "rpc-whitelist-enabled": false,
    "scrape-paused-torrents-enabled": true,
    "script-torrent-done-enabled": false,
    "script-torrent-done-filename": "",
    "seed-queue-enabled": false,
    "seed-queue-size": 10,
    "speed-limit-down": 500,
    "speed-limit-down-enabled": false,
    "speed-limit-up": 300,
    "speed-limit-up-enabled": true,
    "start-added-torrents": true,
    "trash-original-torrent-files": true,
    "umask": 2,
    "upload-slots-per-torrent": 14,
    "utp-enabled": true,
    "watch-dir": "/watch",
    "watch-dir-enabled": true
}

**Comment by erickok** [comment]
> ***.***.***.*** - admin [22/Feb/2018:17:09:23 +0200] "POST /rpc HTTP/1.1" 301 31 "-" "Transdroid Torrent Connect"
Here you see a 301. That is a redirect. I think because the target is not correct (should be /transmission/rpc). What is your folder setting (in Transdroid under server settings -> Advanced Settings).

**Comment by ermethic** [comment]
Yay, that solved it, the folder setting was empty.  I changed it to /transmission/rpc and now it connects.
Thanks a lot !

**Comment by antongeorgiev** [comment]
I had the same issue after upgrading to 2.5.10. Also connecting to transmission. I don't have a reverse proxy but my setup does some port forwarding using iptables and ip rule packet tagging for outgoing routing.

I also had the folder setting set to empty and I resolved it by changing it to /transmission. 

I never had to do that before version 2.5.10.

Hope this helps someone else.

**Comment by flowolf** [comment]
Had the same issue! Using reverse proxy as well. Setting the folder to /transmission solved it.

**Comment by erickok** [comment]
Seems for some specific reverse proxy setups this explcit folder setting is required. Closing as not really a bug (you can set any fodler required in Transdroid).
