### ISSUE TITLE
problem to connect to rtorrent server

### ISSUE THREAD

**Issue by someuser94** [erickok/transdroid#425]
Yesterday I update transdroid to version 2.5.10 but after that I can't connect to my rtorrent server anymore!
This is the main error in the log:

27953 -- Tue Feb 20 22:51:34 GMT+01:00 2018 -- 3 -- Calling d.multicall2 with params [  main d.hash= d.name= d.state= d.down.rate= d.up.rate= d.peers_connected= d.peers_not_connected= d.... ]
27954 -- Tue Feb 20 22:51:34 GMT+01:00 2018 -- 3 -- de.timroes.axmlrpc.XMLRPCException: Error parsing response.
27955 -- Tue Feb 20 22:51:34 GMT+01:00 2018 -- 3 -- ConnectionError exception: Error making call to d.multicall2 with params [  main d.hash= d.name= d.state= d.down.rate= d.up.rate= d.peers_connected= d.peers_not_connected= d.... ]: de.timroes.axmlrpc.XMLRPCException: Error parsing response.

**Comment by someuser94** [comment]
Yes I came from 2.5.9. I found a solution on web. This is my configuration:

"servers": [
    {
      "name": "server",
      "type": "daemon_rtorrent",
      "host": "xxxxxxxxxx",
      "port": "xxxx",
      "ssl": false,
      "ssl_accept_all": false,
      "folder": "",
      "use_auth": true,
      "username": "xxxxx",
      "password": "xxxxxxxx",
      "download_alarm": false,
      "new_torrent_alarm": false
    }

with this configuration transdroid 2.5.9 works but on 2.5.10 I had to add "folder": "\/rutorrent\/plugins\/httprpc\/action.php"

**Comment by erickok** [comment]
Very odd. The default 'folder' (RPC mount point setting) is /RPC2. If you do not supply one, like it seems from that configuration, it will use the default. Instead you are now switching to the rtorrent httprpc scgi plugin. Nice that it works, but i am not sure how this was related to any code change in the new release... Alas, good you have it working now!
