### ISSUE TITLE
Unable to add torrent to Deluge

### ISSUE THREAD

**Issue by dcabro** [erickok/transdroid#427]
Starting from the latest update, I'm unable to add the torrent (file) to Deluge server.

Android 7.0 
deluged: 1.3.13

Debug log on the daemon side:
[ERROR   ] 10:31:07 rpcserver:306 Exception calling RPC request: add_torrent_file() takes exactly 4 arguments (2 given)
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/deluge/core/rpcserver.py", line 301, in dispatch
    ret = self.factory.methods[method](*args, **kwargs)
TypeError: add_torrent_file() takes exactly 4 arguments (2 given)

From the client:

Transdrone 2.5.10 (230)
Deluge settings: http://osmc@192.168.0.254:8112

Connection and error log:
7081 -- Fri Feb 23 10:17:19 GMT+01:00 2018 -- 3 -- Error: org.apache.http.conn.ConnectTimeoutException: Connect to /192.168.0.254:8112 timed out
7082 -- Fri Feb 23 10:17:19 GMT+01:00 2018 -- 3 -- Error: org.apache.http.conn.ConnectTimeoutException: Connect to /192.168.0.254:8112 timed out
7083 -- Fri Feb 23 10:17:19 GMT+01:00 2018 -- 3 -- ConnectionError exception: org.apache.http.conn.ConnectTimeoutException: Connect to /192.168.0.254:8112 timed out
7084 -- Fri Feb 23 10:17:19 GMT+01:00 2018 -- 3 -- ConnectionError exception: org.apache.http.conn.ConnectTimeoutException: Connect to /192.168.0.254:8112 timed out
7085 -- Fri Feb 23 10:17:32 GMT+01:00 2018 -- 3 -- Success: {"id": 2, "result": {"stats": {"upload_protocol_rate": 2819, "max_upload": 270.0, "download_protocol_rate": 1854, "download_rate": 0, "has_incoming_connections": true, "num_connections": 7, "max_download": 2750.0, "upload_rate": 17176, "dht_nodes": 0, "free_space": 8033673216, "max_num_connections":... (80104 chars)
7086 -- Fri Feb 23 10:17:33 GMT+01:00 2018 -- 3 -- Success: {"id": 2, "result": {"stats": {"upload_protocol_rate": 2878, "max_upload": 270.0, "download_protocol_rate": 1906, "download_rate": 0, "has_incoming_connections": true, "num_connections": 2, "max_download": 2750.0, "upload_rate": 13740, "dht_nodes": 0, "free_space": 8033673216, "max_num_connections":... (80104 chars)
7087 -- Fri Feb 23 10:17:45 GMT+01:00 2018 -- 3 -- Uploading a file to the Deluge daemon: http://192.168.0.254:8112/upload
7088 -- Fri Feb 23 10:17:48 GMT+01:00 2018 -- 3 -- Success: {"id": 2, "result": {"stats": {"upload_protocol_rate": 2073, "max_upload": 270.0, "download_protocol_rate": 1358, "download_rate": 0, "has_incoming_connections": true, "num_connections": 4, "max_download": 2750.0, "upload_rate": 482, "dht_nodes": 0, "free_space": 8033673216, "max_num_connections": 2... (80099 chars)
7089 -- Fri Feb 23 10:17:55 GMT+01:00 2018 -- 3 -- Error: java.net.SocketTimeoutException: Read timed out
7090 -- Fri Feb 23 10:17:55 GMT+01:00 2018 -- 3 -- ConnectionError exception: java.net.SocketTimeoutException: Read timed out
7091 -- Fri Feb 23 10:18:06 GMT+01:00 2018 -- 3 -- Uploading a file to the Deluge daemon: http://192.168.0.254:8112/upload
7092 -- Fri Feb 23 10:18:13 GMT+01:00 2018 -- 3 -- Success: {"id": 2, "result": {"stats": {"upload_protocol_rate": 2158, "max_upload": 270.0, "download_protocol_rate": 1178, "download_rate": 0, "has_incoming_connections": true, "num_connections": 5, "max_download": 2750.0, "upload_rate": 0, "dht_nodes": 0, "free_space": 8033673216, "max_num_connections": 200... (80086 chars)
7093 -- Fri Feb 23 10:18:20 GMT+01:00 2018 -- 3 -- Error: java.net.SocketTimeoutException: Read timed out
7094 -- Fri Feb 23 10:18:20 GMT+01:00 2018 -- 3 -- ConnectionError exception: java.net.SocketTimeoutException: Read timed out
7095 -- Fri Feb 23 10:24:07 GMT+01:00 2018 -- 3 -- ConnectionError exception: Unexpected end of ZLIB input stream
7096 -- Fri Feb 23 10:24:10 GMT+01:00 2018 -- 3 -- ConnectionError exception: Unexpected end of ZLIB input stream
7097 -- Fri Feb 23 10:25:09 GMT+01:00 2018 -- 3 -- ConnectionError exception: Unexpected end of ZLIB input stream
7098 -- Fri Feb 23 10:30:08 GMT+01:00 2018 -- 3 -- ConnectionError exception: Unexpected end of ZLIB input stream
7099 -- Fri Feb 23 10:30:10 GMT+01:00 2018 -- 3 -- ConnectionError exception: Unexpected end of ZLIB input stream
7100 -- Fri Feb 23 10:30:20 GMT+01:00 2018 -- 3 -- ConnectionError exception: Unexpected end of ZLIB input stream
7101 -- Fri Feb 23 10:30:34 GMT+01:00 2018 -- 3 -- ConnectionError exception: Unexpected end of ZLIB input stream
7102 -- Fri Feb 23 10:30:35 GMT+01:00 2018 -- 3 -- ConnectionError exception: Unexpected end of ZLIB input stream
7103 -- Fri Feb 23 10:30:38 GMT+01:00 2018 -- 3 -- Success: {"id": 2, "result": {"stats": {"upload_protocol_rate": 7543, "max_upload": 270.0, "download_protocol_rate": 6597, "download_rate": 0, "has_incoming_connections": true, "num_connections": 129, "max_download": 2750.0, "upload_rate": 0, "dht_nodes": 0, "free_space": 8033673216, "max_num_connections": 2... (80313 chars)
7104 -- Fri Feb 23 10:30:39 GMT+01:00 2018 -- 3 -- Success: {"id": 2, "result": {"stats": {"upload_protocol_rate": 7567, "max_upload": 270.0, "download_protocol_rate": 6424, "download_rate": 0, "has_incoming_connections": true, "num_connections": 134, "max_download": 2750.0, "upload_rate": 0, "dht_nodes": 0, "free_space": 8033673216, "max_num_connections": 2... (80313 chars)
7105 -- Fri Feb 23 10:31:08 GMT+01:00 2018 -- 3 -- Uploading a file to the Deluge daemon: http://192.168.0.254:8112/upload
7106 -- Fri Feb 23 10:31:16 GMT+01:00 2018 -- 3 -- Error: java.net.SocketTimeoutException: Read timed out
7107 -- Fri Feb 23 10:31:16 GMT+01:00 2018 -- 3 -- ConnectionError exception: java.net.SocketTimeoutException: Read timed out

**Comment by erickok** [comment]
Hi,

Did the last (2.5.9) release work fine? Because nothing really changed wrt
the Deluge adapter. Perhaps it is a Deluge version update issue instead?

Eric

**Comment by dcabro** [comment]
I think the previous (if that was 2.5.9) worked fine. Wasn't paying attention if the deluged was updated. Do yo have the 2.5.9 apk so I can try with that one?

**Comment by erickok** [comment]
Yes, get it from https://github.com/erickok/transdroid/releases

**Comment by dcabro** [comment]
Working fine with 2.5.9. 

Connection and error log:
1 -- Fri Feb 23 13:28:31 GMT+01:00 2018 -- 3 -- Success: {"id": 2, "result": {"stats": {"upload_protocol_rate": 4216, "max_upload": 270.0, "download_protocol_rate": 4116, "download_rate": 0, "has_incoming_connections": true, "num_connections": 7, "max_download": 2750.0, "upload_rate": 55040, "dht_nodes": 0, "free_space": 8033583104, "max_num_connections":... (72716 chars)
2 -- Fri Feb 23 13:29:39 GMT+01:00 2018 -- 3 -- Uploading a file to the Deluge daemon: http://192.168.0.254:8112/upload
3 -- Fri Feb 23 13:29:40 GMT+01:00 2018 -- 3 -- Success: {"id": 2, "result": true, "error": null}

4 -- Fri Feb 23 13:29:41 GMT+01:00 2018 -- 3 -- Success: {"id": 2, "result": {"stats": {"upload_protocol_rate": 6349, "max_upload": 270.0, "download_protocol_rate": 5014, "download_rate": 0, "has_incoming_connections": true, "num_connections": 120, "max_download": 2750.0, "upload_rate": 65999, "dht_nodes": 0, "free_space": 8033558528, "max_num_connections... (72765 chars)
5 -- Fri Feb 23 13:29:41 GMT+01:00 2018 -- 3 -- Success: {"id": 2, "result": {"stats": {"upload_protocol_rate": 6349, "max_upload": 270.0, "download_protocol_rate": 5014, "download_rate": 0, "has_incoming_connections": true, "num_connections": 111, "max_download": 2750.0, "upload_rate": 65999, "dht_nodes": 0, "free_space": 8033558528, "max_num_connections... (73241 chars)

**Comment by voytecPL** [comment]
I think there is similar problem with tTorrent. Unable to add torrent to tTorrent via web interface. 
It looks like Transdroid cannot download the torrent. Transdroid used to place downloaded .torrent files in Download folder. Now there is nothing there.
Application display info that file was added but nothing gets added to tTorrent. 
Thanks
Is this expected?

**Comment by alon24** [comment]
This happens also with deluge 1.3.15
Version 2.5.9 works perfect

**Comment by erickok** [comment]
Okay I think it doesn't have anything to do with Deluge, but with the
change in file type support. How are you trying to add the torrent?

**Comment by dcabro** [comment]
I have tried two ways. First from the Chrome downloads directly (.torrent
files are associated with transdroid) and second via + icon and by picking
the downloaded file from Downloads (previously downloaded via Chrome)

**Comment by erickok** [comment]
Thanks. And what Android version?

**Comment by dcabro** [comment]
Android 7.0

**Comment by sviperz** [comment]
The same issue, can't add a torrent file in any way mentioned above plus from file manager. Android 8.1.

**Comment by khrel** [comment]
Can't add torrent file (file mode) with either transdroid 2.5.9 or 2.5.10 on android 6.0.1 or android 5.1.1 devices.
Downgrade to transdroid 2.5.8 on both works with this old version.

**Comment by mike-pt** [comment]
Same problem, Android 8.1.0

**Comment by cmezh** [comment]
Can confirm it happens with Transdroid 2.5.10. With Deluge RPC works fine.

**Comment by arjhun** [comment]
Same problem here... Android 7 have not updated deluge sinds last working version of transdroid!

**Comment by sviperz** [comment]
@erickok is the fix coming?

**Comment by Drsela** [comment]
Facing the exact same issue. Downloading .torrent and opening them with Deluge in Transdroid causes nothing to happen.

OS: Android 8.0
Transdroid 2.5.10
Deluge 1.3.15

**Comment by iZarcon** [comment]
using the newest version on google play store with with `deluge-web -L debug` the following error displays when attempting to add a torrent from my phone:
[DEBUG   ] 11:27:24 json_api:255 json-request: {"method":"core.add_torrent_file","params":[[{"path":"\/tmp\/delugeweb-1oQzMN\/tmp5XY_4u.torrent","options":[]}]],"id":2}
[ERROR   ] 11:27:24 client:391 RPCError Message Received!
--------------------------------------------------------------------------------
RPCRequest: core.add_torrent_file([{u'path': u'/tmp/delugeweb-1oQzMN/tmp5XY_4u.torrent', u'options': []}])
--------------------------------------------------------------------------------
  File "/usr/lib/python2.7/dist-packages/deluge/core/rpcserver.py", line 298, in dispatch
    ret = self.factory.methods[method](*args, **kwargs)

TypeError: add_torrent_file() takes exactly 4 arguments (2 given)

transdrone: version 2.5.10
deluge-web version: 1.3.6

it worked fine before I updated my trandroid

i just installed transdrone 2.5.9 from github with the apk alongside the google play version (2.5.10) that I have and the adding of a torrent worked just fine:
[DEBUG   ] 11:44:56 json_api:255 json-request: {"method":"web.add_torrents","params":[[{"path":"\/tmp\/delugeweb-xdK4wR\/tmpI6ApJP.torrent","options":[]}]],"id":2}
[INFO    ] 11:44:56 json_api:773 Adding torrent from file `tmpI6ApJP.torrent` with options `[]`


notice, it used web.add_torrents instead of core.add_torrent_file

i have no clue other than that

**Comment by Drsela** [comment]
The only difference appears to be 

2.5.10
> "method":"web.add_torrents"
vs.

2.5.9
> "method":"core.add_torrent_file"

What'd happen if it was changed back to "core.add" in 2.5.11?

**Comment by iZarcon** [comment]
@Drsela it is the other way around.

2.5.9 is web.add_torrents and this method works

**Comment by tstackhouse** [comment]
2.5.9 works here as well, attached to a Deluge server, however immediately after adding, I get a communication error, that prevents a proper refresh of the UI. A manual refresh worked afterwards though.

Here is my sanitized log:

1 -- Tue Mar 27 11:36:15 EDT 2018 -- 3 -- Success: {"id": 2, "result": {"stats": {"upload_protocol_rate": 4135, "max_upload": -1.0, "download_protocol_rate": 2255, "download_rate": 0, "has_incoming_connections": true, "num_connections": 3, "max_download": -1.0, "upload_rate": 6389, "dht_nodes": 391, "free_space": 16680061632512, "max_num_connections... (54474 chars)
2 -- Tue Mar 27 11:37:06 EDT 2018 -- 3 -- Uploading a file to the Deluge daemon: http://<server>/upload
3 -- Tue Mar 27 11:37:06 EDT 2018 -- 3 -- Success: {"id": 2, "result": true, "error": null}

4 -- Tue Mar 27 11:37:06 EDT 2018 -- 3 -- Error: java.util.zip.ZipException: Not in GZIP format
5 -- Tue Mar 27 11:37:06 EDT 2018 -- 3 -- ConnectionError exception: java.util.zip.ZipException: Not in GZIP format
6 -- Tue Mar 27 11:37:06 EDT 2018 -- 3 -- Error: java.util.zip.ZipException: Not in GZIP format
7 -- Tue Mar 27 11:37:06 EDT 2018 -- 3 -- ConnectionError exception: java.util.zip.ZipException: Not in GZIP format

**Comment by iZarcon** [comment]
Looking at the methods available in core, add_torrent_files does exist now and it works like web.add_torrents (except web method also handles magnet links) but not in older versions. They just had add_torrent_file (singular) in core.

so seems the options are to revert to web.add_torrents or switch to core.add_torrent_files (plural) and have no backwards compatibility.

I guess could rewrite the way you use core.add_torrent_file (singular) to send the arguments in the way it expects as well

**Comment by tstackhouse** [comment]
I would imagine doing some kind of branching logic based on the API method availability would be do-able without much issue, no?

**Comment by dcabro** [comment]
@erickok any chance that this will be fixed? Thanks!

**Comment by erickok** [comment]
Sorry I do not have time at the moment but obviously I want to look into it
soon.

**Comment by dcabro** [comment]
Ok Eric, no worries. Whenever you find the time. Thanks for the great app and support, we appreciate it.

**Comment by Madj42** [comment]
Any news on if this will be fixed? Currently running into this myself.

**Comment by mosin** [comment]
When I try to add a file to Deluge 1.3.15 my error from the web log is:
`[ERROR   ] 19:38:00 client:391 RPCError Message Received!
--------------------------------------------------------------------------------
RPCRequest: core.add_torrent_file([{u'path': u'/tmp/delugeweb-EqgYTB/tmpQLLwTT.torrent', u'options': []}])
--------------------------------------------------------------------------------
  File "/usr/lib/python2.7/dist-packages/deluge/core/rpcserver.py", line 301, in dispatch
    ret = self.factory.methods[method](*args, **kwargs)

TypeError: add_torrent_file() takes exactly 4 arguments (2 given)
--------------------------------------------------------------------------------`

**Comment by nemethloci** [comment]
Only for the record: As of today, this is still an issue:
- deluge daemon: 1.3.15
- transdrone: 2.5.10
- android: 6.0.1

**Comment by qweluke** [comment]
same here:

deluge deamon 1.3.13
transdrone: 2.5.10
android: 7.0

I can list torrents from deluge server but can't add them... getting connection error :/

**Comment by andrewtjb** [comment]
I'm having the same issue can't add torrents get a communication error. Can add magnet links fine though

Deluge daemon 1.3.13
Transdroid 2.5.10
Android 8.0

Transdroid 2.5.9 works fine.

**Comment by erickok** [comment]
Pushed 2.5.11 release which fixed this issue. OSrry for the big delay.

**Comment by arjhun** [comment]
Thanks Eric for taking the time!

**Comment by YourHuckleberry** [comment]
Awesome!
