### ISSUE TITLE
Unable to connecto to deluge web unless connected first from web or default daemon set by hand to deluged-web conf

### ISSUE THREAD

**Issue by Antoniossss** [erickok/transdroid#428]
So basicly transdroid wont connect to deluge-web. I have to connect to deluge-web from browser and *connect to actual daemon* in order to make it "the default one". From that point, transdroid will connect just fine. I did a workaround and set default daemon by hand in deluged-web config, but it should be handled on transdrod side 

Required:
Handling of additional step: selecting defined deluged daemon to connect to from web (thus from transdroid)

**Comment by mike-pt** [comment]
FYI you can have the web UI auto connect to a running  daemon

i.e.
` "default_daemon": "127.0.0.1:58846",`

**Comment by erickok** [comment]
Yes this is by design. You can easily set up a default daemon to connect to, as per @mike-pt 's suggestion.
