### ISSUE TITLE
Deluge RPC

### ISSUE THREAD

**Issue by kartun83** [erickok/transdroid#432]
I'm trying to connect to deluge rpc, but no luck and no helpfull message provided. Any hints ?

**Comment by amvapor** [comment]
What do you're logs look like server side? I was having trouble with the connection. Turned out to be SSL issues mentioned in the server logs

**Comment by erickok** [comment]
Make sure to set to accept all ssl certificates or, much better, enter the ssl sha-1 hash of the Deluge-generated ssl certificate.
