### ISSUE TITLE
[Feature] Add ability to choose server when opening .torrent-file

### ISSUE THREAD

**Issue by Drsela** [erickok/transdroid#434]
Hi there.

When you open a .torrent-file it will be added to the latest open instance of available servers. I'd like an option for choosing server instead. Some people have several servers available and choosing the specific torrent on add .torrent would be awesome. This is the current Use Case:

Pre-Req[Transdroid open in background and one server selected (out of multiple servers]
1. Download .torrent
2. Open it
3. Torrent will be added to latest open server.

This is the Use Case I desire:

1. Download .torrent
2. Open it
3. Transdroid opens
4. Ask for which server to add .torrent to
5. Torrent will be added to the selected server

**Comment by erickok** [comment]
This already exists. Settings - > Default Server.

**Comment by Drsela** [comment]
Oh yeah I see.

You can mark this issue as Closed/Fixed. :)
