### ISSUE TITLE
Feature Request: Custom URL support

### ISSUE THREAD

**Issue by nebulakl** [erickok/transdroid#435]
I have set up a reverse proxy with nginx to provide ssl connection for Transmission webui which points https://my.domain/trans/ to http://127.0.0.1:9091/
However, the current version does not support subdirectory, and failed to connect to my server.
It would be great to add an option to use custom url and it takes precedence over other options.

**Comment by erickok** [comment]
You can use the 'folder' setting for this. Also make sure to set the port
number to whatever you use (443 from what I can see).

**Comment by nebulakl** [comment]
I put `/trans/` in `Folder` and the url seems correct now, but then I got `Internal error building request`

**Comment by nebulakl** [comment]
Looks like I need to put the full url for transmission rpc there. It works with `/trans/transmission/rpc`
I hope the settings can be clearer.
