### ISSUE TITLE
Caddy reverse proxy and Deluge woes

### ISSUE THREAD

**Issue by Majibear** [erickok/transdroid#442]
Hey all,

A little help with something that has become a real pain here. The problem I'm facing is having Deluge, which is being run behind a Caddy Server reverse proxy, to play nice and operate with Transdroid.

Initially I had issues getting Deluge to even work with Caddy, until I found a solution in this thread: https://forum.deluge-torrent.org/viewtopic.php?t=54135.

So the WebUI works with that code input via the reverse proxy; However it won't play nice with Transdroid; it just won't connect. I've followed the Transdroid FAQ by inputting folders and port 443, and also the steps outlined in this thread: https://github.com/erickok/transdroid/issues/302, but no matter what I do Transdroid just won't connect to Deluge through the reverse proxy. Sonarr and Radarr are finding Deluge at the reverse proxy fine though, which shows it can be recognised. 

I'm wondering if it has something to do with the Caddy code as I'm reading people with NGINX and Apache also have to do workarounds with headers and such , yet I can't find a specific Caddy solution.

Here is how my Caddy Deluge config reads:
	
    	rewrite {
    		if_op or
    		if {>Referer} has /deluge
    		if {>Referer} has mydomain.dns.com/themes/css/
    		if {>Referer} has mydomain.dns.com/css/
    		to /deluge/{path}
    	}
   
    	proxy /deluge http://127.0.0.1:8112 {
    	without /deluge
    	transparent
    	header_upstream X-Forwarded-Host {host}
    	}

Any help and suggestions would be greatly appreciated.

**Comment by erickok** [comment]
I have no particular experience with Caddy, but as long as it just forwards requests, I do not see why it would not work. Can you show me the Transdroid error log (via Help menu)?

**Comment by Majibear** [comment]
Sure thing, here's the error log output.

`Transdroid 2.5.10 (230)
Deluge settings: https://server.net:443/deluge

Connection and error log:
3 -- Thu May 31 20:11:48 GMT+12:00 2018 -- 3 -- Boot signal received, starting server and rss checker background services
4 -- Thu May 31 20:11:48 GMT+12:00 2018 -- 3 -- Boot signal received, starting app update checker service
5 -- Thu May 31 20:12:27 GMT+12:00 2018 -- 3 -- Error: AuthenticationFailure exception: Password error? Server time difference? No (valid) cookie in response and JSON was: {"id": 1, "result": true, "error": null}

6 -- Thu May 31 20:12:28 GMT+12:00 2018 -- 3 -- Local Transdroid is at 230 and the reported latest version is 230
7 -- Thu May 31 20:18:41 GMT+12:00 2018 -- 3 -- Boot signal received, starting server and rss checker background services
8 -- Thu May 31 20:18:41 GMT+12:00 2018 -- 3 -- Boot signal received, starting app update checker service
9 -- Thu May 31 20:18:41 GMT+12:00 2018 -- 3 -- Error: AuthenticationFailure exception: Password error? Server time difference? No (valid) cookie in response and JSON was: {"id": 1, "result": true, "error": null}

10 -- Thu May 31 20:18:41 GMT+12:00 2018 -- 3 -- ConnectionError exception: AuthenticationFailure exception: Password error? Server time difference? No (valid) cookie in response and JSON was: {"id": 1, "result": true, "error": null}

11 -- Thu May 31 20:19:20 GMT+12:00 2018 -- 3 -- Error: AuthenticationFailure exception: Password error? Server time difference? No (valid) cookie in response and JSON was: {"id": 1, "result": true, "error": null}

12 -- Thu May 31 20:19:20 GMT+12:00 2018 -- 3 -- ConnectionError exception: AuthenticationFailure exception: Password error? Server time difference? No (valid) cookie in response and JSON was: {"id": 1, "result": true, "error": null}

13 -- Thu May 31 20:19:39 GMT+12:00 2018 -- 3 -- Skip the update service, as we already checked the last 24 hours (or to be exact at Thu May 31 20:12:28 GMT+12:00 2018).
14 -- Thu May 31 20:19:40 GMT+12:00 2018 -- 3 -- Error: AuthenticationFailure exception: Password error? Server time difference? No (valid) cookie in response and JSON was: {"id": 1, "result": true, "error": null}
`

**Comment by erickok** [comment]
Can you check the server time vs the phone time? (Check also the time zones are correct.) This can cause the Deluge cookie to be invalidated the moment it is set.

**Comment by erickok** [comment]
Other than that, are you using basic auth on your reverse proxy? Then set this in the appropriate advanced username/password fields. Which are NOT the deluge web UI password field.

**Comment by Majibear** [comment]
Both the time zones are correct, and  I've disabled authentication in the Transdroid settings as I'm not currently using basic auth on the reverse proxy.

So I'm not entirely sure what authentication error it is getting...

**Comment by erickok** [comment]
If you have logging, can you see the cookie header being returned?

**Comment by Majibear** [comment]
Sorry I got a little caught up.

I'm assuming you mean logging in Deluge? So I'm on Windows and have enabled logging for Deluge but I'm not seeing any errors in the log file with regard to the header.

I have read in other forum posts while researching this error that the header was an issue with Nginx and they had to adjust the Ngin config code for Transdroid. I'm wondering if it's the same problem with Caddy, but there seems very little info with regard to Caddy and Transdroid anywhere.

**Comment by erickok** [comment]
Yeah I never even heard of Caddy before. I meant the Caddy logging though,
where you can see requests and responses.

**Comment by Majibear** [comment]
Well I went with Caddy for the convenience with how easy it is to set up with LetsEncrypt. All other options seem to be tedious with Windows, and it's working perfectly except for this one issue with Transdroid; It'd be great if I could get it to play nice.

So I've enabled and checked the Caddy logs, but I'm not entirely sure what I'm looking for in the way of reporting here. There doesn't seem to be anything related to Headers anyway.

Here's the log when accessing Deluge through the reverse proxy via the webUI:

    [08/Jun/2018:10:37:12 +1200] "POST /json HTTP/2.0" 200 2554
    221.135.135.68 - - [08/Jun/2018:10:37:14 +1200] "POST /json HTTP/2.0" 200 2557
    221.135.135.68 - - [08/Jun/2018:10:37:14 +1200] "GET /deluge HTTP/2.0" 200 2103
    221.135.135.68 - - [08/Jun/2018:10:37:14 +1200] "POST /json HTTP/2.0" 502 16
    221.135.135.68 - - [08/Jun/2018:10:37:14 +1200] "GET /css/ext-all-notheme.css HTTP/2.0" 200 16734
    221.135.135.68 - - [08/Jun/2018:10:37:14 +1200] "GET /css/ext-extensions.css HTTP/2.0" 200 687
    221.135.135.68 - - [08/Jun/2018:10:37:14 +1200] "GET /css/deluge.css HTTP/2.0" 200 2295
    221.135.135.68 - - [08/Jun/2018:10:37:15 +1200] "GET /js/ext-extensions.js HTTP/2.0" 200 12773
    221.135.135.68 - - [08/Jun/2018:10:37:15 +1200] "GET /gettext.js HTTP/2.0" 200 4928
    221.135.135.68 - - [08/Jun/2018:10:37:15 +1200] "GET /js/ext-base.js HTTP/2.0" 200 10537
    221.135.135.68 - - [08/Jun/2018:10:37:16 +1200] "GET /js/deluge-all.js HTTP/2.0" 200 31711
    221.135.135.68 - - [08/Jun/2018:10:37:16 +1200] "GET /js/ext-all.js HTTP/2.0" 200 198459
    221.135.135.68 - - [08/Jun/2018:10:37:16 +1200] "GET /js/label/label.js HTTP/2.0" 200 3851
    221.135.135.68 - - [08/Jun/2018:10:37:16 +1200] "GET /js/autoremoveplus/autoremoveplus.js 
    HTTP/2.0" 200 6092
    221.135.135.68 - - [08/Jun/2018:10:37:16 +1200] "GET /icons/ok.png HTTP/2.0" 200 928
    221.135.135.68 - - [08/Jun/2018:10:37:17 +1200] "GET /themes/images/gray/toolbar/bg.gif HTTP/2.0" 
    404 14
    221.135.135.68 - - [08/Jun/2018:10:37:17 +1200] "GET /themes/images/gray/button/btn.gif HTTP/2.0" 
    404 14
    221.135.135.68 - - [08/Jun/2018:10:37:17 +1200] "GET /themes/images/default/grid/grid-split.gif 
    HTTP/2.0" 404 14
    221.135.135.68 - - [08/Jun/2018:10:37:17 +1200] "GET /icons/error.png HTTP/2.0" 200 909
    221.135.135.68 - - [08/Jun/2018:10:37:17 +1200] "GET /themes/images/gray/panel/white-top- 
    bottom.gif HTTP/2.0" 404 14
    221.135.135.68 - - [08/Jun/2018:10:37:17 +1200] "GET /themes/images/gray/panel/tool-sprites.gif 
    HTTP/2.0" 404 14
    221.135.135.68 - - [08/Jun/2018:10:37:17 +1200] "GET /icons/logout.png HTTP/2.0" 200 706
    221.135.135.68 - - [08/Jun/2018:10:37:17 +1200] "GET /icons/connection_manager.png HTTP/2.0" 200 
    680
    221.135.135.68 - - [08/Jun/2018:10:37:17 +1200] "GET /themes/images/gray/grid/grid3-hd-btn.gif 
    HTTP/2.0" 404 14
    221.135.135.68 - - [08/Jun/2018:10:37:17 +1200] "GET /themes/images/default/dd/drop-no.gif 
    HTTP/2.0" 404 14
    221.135.135.68 - - [08/Jun/2018:10:37:17 +1200] "GET /themes/images/gray/grid/grid3-hrow2.gif 
    HTTP/2.0" 404 14
    221.135.135.68 - - [08/Jun/2018:10:37:17 +1200] "GET /themes/images/gray/grid/col-move- 
   bottom.gif HTTP/2.0" 404 14
   221.135.135.68 - - [08/Jun/2018:10:37:17 +1200] "GET /themes/images/gray/grid/col-move-top.gif 
    HTTP/2.0" 404 14
    221.135.135.68 - - [08/Jun/2018:10:37:17 +1200] "GET /icons/help.png HTTP/2.0" 200 959
    221.135.135.68 - - [08/Jun/2018:10:37:17 +1200] "GET /images/s.gif HTTP/2.0" 200 57
    221.135.135.68 - - [08/Jun/2018:10:37:17 +1200] "GET /icons/preferences.png HTTP/2.0" 200 935
    221.135.135.68 - - [08/Jun/2018:10:37:17 +1200] "GET /themes/images/gray/tabs/tab-strip-bg.gif 
    HTTP/2.0" 404 14
    221.135.135.68 - - [08/Jun/2018:10:37:17 +1200] "GET /icons/down.png HTTP/2.0" 200 645
    221.135.135.68 - - [08/Jun/2018:10:37:17 +1200] "GET /themes/images/gray/tabs/tabs-sprite.gif 
    HTTP/2.0" 404 14
    221.135.135.68 - - [08/Jun/2018:10:37:17 +1200] "GET /themes/images/gray/progress/progress-bg.gif 
    HTTP/2.0" 404 14
    221.135.135.68 - - [08/Jun/2018:10:37:17 +1200] "GET /themes/images/gray/qtip/bg.gif HTTP/2.0" 404 
    14
    221.135.135.68 - - [08/Jun/2018:10:37:17 +1200] "GET /themes/images/default/grid/loading.gif 
    HTTP/2.0" 404 14
    221.135.135.68 - - [08/Jun/2018:10:37:17 +1200] "GET /icons/up.png HTTP/2.0" 200 641
    221.135.135.68 - - [08/Jun/2018:10:37:17 +1200] "GET /render/tab_status.html HTTP/2.0" 200 346
    221.135.135.68 - - [08/Jun/2018:10:37:17 +1200] "GET /icons/start.png HTTP/2.0" 200 493
    221.135.135.68 - - [08/Jun/2018:10:37:17 +1200] "GET /themes/images/gray/qtip/tip-sprite.gif 
    HTTP/2.0" 404 14
    221.135.135.68 - - [08/Jun/2018:10:37:17 +1200] "GET /themes/images/gray/qtip/tip-anchor-sprite.gif 
    HTTP/2.0" 404 14
    221.135.135.68 - - [08/Jun/2018:10:37:17 +1200] "POST /json HTTP/2.0" 200 759
    221.135.135.68 - - [08/Jun/2018:10:37:17 +1200] "POST /json HTTP/2.0" 200 759
    221.135.135.68 - - [08/Jun/2018:10:37:17 +1200] "GET /icons/pause.png HTTP/2.0" 200 450
    221.135.135.68 - - [08/Jun/2018:10:37:17 +1200] "POST /json HTTP/2.0" 200 760
    221.135.135.68 - - [08/Jun/2018:10:37:17 +1200] "GET /icons/remove.png HTTP/2.0" 200 278
    221.135.135.68 - - [08/Jun/2018:10:37:17 +1200] "GET /icons/deluge.png HTTP/2.0" 200 745
    221.135.135.68 - - [08/Jun/2018:10:37:17 +1200] "GET /icons/add.png HTTP/2.0" 200 536
    221.135.135.68 - - [08/Jun/2018:10:37:17 +1200] "POST /json HTTP/2.0" 200 56
    221.135.135.68 - - [08/Jun/2018:10:37:17 +1200] "GET /icons/deluge.png HTTP/2.0" 200 745
    221.135.135.68 - - [08/Jun/2018:10:37:17 +1200] "POST /json HTTP/2.0" 200 52
    221.135.135.68 - - [08/Jun/2018:10:37:17 +1200] "POST /json HTTP/2.0" 200 52
    221.135.135.68 - - [08/Jun/2018:10:37:17 +1200] "POST /json HTTP/2.0" 200 52
    221.135.135.68 - - [08/Jun/2018:10:37:17 +1200] "POST /json HTTP/2.0" 200 52
    221.135.135.68 - - [08/Jun/2018:10:37:17 +1200] "POST /json HTTP/2.0" 200 56
    221.135.135.68 - - [08/Jun/2018:10:37:17 +1200] "GET /icons/deluge.png HTTP/2.0" 200 745
    221.135.135.68 - - [08/Jun/2018:10:37:17 +1200] "GET /themes/images/default/button/arrow.gif 
    HTTP/2.0" 404 14
    221.135.135.68 - - [08/Jun/2018:10:37:17 +1200] "GET /icons/drive.png HTTP/2.0" 200 457
    221.135.135.68 - - [08/Jun/2018:10:37:17 +1200] "GET /icons/dht.png HTTP/2.0" 200 816
    221.135.135.68 - - [08/Jun/2018:10:37:17 +1200] "GET /icons/traffic.png HTTP/2.0" 200 636
    221.135.135.68 - - [08/Jun/2018:10:37:17 +1200] "GET /icons/downloading.png HTTP/2.0" 200 709
    221.135.135.68 - - [08/Jun/2018:10:37:17 +1200] "GET /icons/seeding.png HTTP/2.0" 200 654
    221.135.135.68 - - [08/Jun/2018:10:37:17 +1200] "GET /icons/connections.png HTTP/2.0" 200 677
    221.135.135.68 - - [08/Jun/2018:10:37:17 +1200] "POST /json HTTP/2.0" 200 2555
    221.135.135.68 - - [08/Jun/2018:10:37:18 +1200] "POST /json HTTP/2.0" 200 177
    221.135.135.68 - - [08/Jun/2018:10:37:18 +1200] "GET /icons/inactive.png HTTP/2.0" 200 618
    221.135.135.68 - - [08/Jun/2018:10:37:18 +1200] "GET /themes/images/gray/grid/grid3-hrow2.gif 
    HTTP/2.0" 404 14
    221.135.135.68 - - [08/Jun/2018:10:37:18 +1200] "GET /themes/images/gray/panel/light-hd.gif 
    HTTP/2.0" 404 14
    221.135.135.68 - - [08/Jun/2018:10:37:18 +1200] "POST /json HTTP/2.0" 200 2558
    221.135.135.68 - - [08/Jun/2018:10:37:18 +1200] "GET /icons/active.png HTTP/2.0" 200 765
    221.135.135.68 - - [08/Jun/2018:10:37:18 +1200] "GET /icons/all.png HTTP/2.0" 200 867
    221.135.135.68 - - [08/Jun/2018:10:37:18 +1200] "GET /themes/images/gray/grid/grid3-hrow- 
    over2.gif HTTP/2.0" 404 14
    221.135.135.68 - - [08/Jun/2018:10:37:18 +1200] "GET /themes/images/default/grid/row-over.gif 
    HTTP/2.0" 404 14
    221.135.135.68 - - [08/Jun/2018:10:37:19 +1200] "POST /json HTTP/2.0" 200 2558
    221.135.135.68 - - [08/Jun/2018:10:37:21 +1200] "POST /json HTTP/2.0" 200 2553
    221.135.135.68 - - [08/Jun/2018:10:37:22 +1200] "POST /json HTTP/2.0" 200 52

**Comment by erickok** [comment]
`/json` is the path that is always appended to every Deluge request. But the logs show requests to that (which I guess are already translated from the `/deluge/json` requests Transdroid will make). So my guess is an incompatibility with Caddy, or a bug/issue therein. Closing because I can';t really support anything more than this.
