### ISSUE TITLE
Unable to set speed limit for Deluge

### ISSUE THREAD

**Issue by cmezh** [erickok/transdroid#443]
Transdroid isn't able to set download/upload speed limit for Deluge.
I guess it may be caused to Deluge update, because it worked well some time ago.
Both Transdroid and Deluge (debug loglevel) logs are clean, no single line related to speed limit.

Versions:
Transdroid 2.5.10
deluged: 1.3.15

**Comment by erickok** [comment]
Just tested and it wrks fine here. Note that you have to set both a downlaod AND an upload speed, or it won't work.
