### ISSUE TITLE
2.5.10: Transdroid causing lots of traffic

### ISSUE THREAD

**Issue by baz357** [erickok/transdroid#445]
Hi, I recently discovered Transdroid. It's really good, thank you!

My biggest issue with it is that it's causing lots of traffic... more than 1 GB per week! That's more than *all* of my other apps combined. I'd be happy if you could reduce that, especially since Transdroid eats up a lot of my 4G data when not at home.

If that's not technically possible, I suggest a new option, something like: 

[ ] automatic torrent checks only when connected to wifi

And please make it so that one could still use the refresh button in the app or widget to trigger a _manual_ update if needed. :)

P.S.: Are you open for more suggestions/ is there a chance to getting them implemented?

**Comment by erickok** [comment]
Actually background checking of torrent is already an option you can enable/disable yourself. 1GB is... a lot. I cannot image how many times you would have to refresh to get to that. Of course the widget WILL refresh automatically, so that might be the culprit.

**Comment by baz357** [comment]
> Actually background checking of torrent is already an option you can enable/disable yourself.

Yes, but doing that manually every time I leave the house (and again when I come back) would surely drive me insane over time, so an automatic solution would be much better. :) I've seen something similar in a podcast player, where downloads can be limited to "connected to wifi" times.


> 1GB is... a lot. I cannot image how many times you would have to refresh to get to that. Of course the widget WILL refresh automatically, so that might be the culprit.

Ah, then it's the widget... I only rarely refresh it manually.
