### ISSUE TITLE
barcode scanner not finding torrents

### ISSUE THREAD

**Issue by sp70** [erickok/transdroid#449]
When using Transdrone or Transdroid, attempting to use the barcode scanner is always returning:

"Can't find torrent link or product information for this barcode"
![screenshot_20180716-165503_transdrone](https://user-images.githubusercontent.com/8812493/42789595-fd06b2e8-891a-11e8-9a15-da070fd7b30a.jpg)

I've attempted scanning directly from the back of various DVD and Blue-ray cases as well as from the PC Monitor.

Barcode Scanner used (prompted / redirected by the app):

https://play.google.com/store/apps/details?id=com.google.zxing.client.android

OS:
Android 8.0

Device:
Galaxy S9+

Example of UPC code attempted:

https://www.upcitemdb.com/upc/25192015229

&

https://www.upcitemdb.com/upc/43396488519

Repro:
1. Press "+" symbol
2. Press barcode scanner icon (this opens barcode scanner)
3. Scan barcode.

Result:
Unable to find torrent.

**Comment by erickok** [comment]
I haven't really tested this for an eternity... I suold check whether the
method of linking barcode to product name is still functional.

**Comment by sp70** [comment]
Any update on this?

**Comment by erickok** [comment]
I am going to remove this feature. It relied on a free to use (Google) web search to find a product name based of the (upc) barcode, but no such free key-less api seems to exist any more.

**Comment by sp70** [comment]
Would the following meet your needs?

https://developers.google.com/vision/android/barcodes-overview

Hoping this very cool feature can be saved.

**Comment by erickok** [comment]
Sorry no, this only scans the barcode, not perform a lookup that matches
the code (a number) to a product name.
