### ISSUE TITLE
All torrents show status unknown on qBittorrent 4.1.1

### ISSUE THREAD

**Issue by liam-maps** [erickok/transdroid#450]
I can connect to the WebUI IP with the user and password, but on the list all the torrents appear in grey color.
When I open one torrent it shows the current speed, but no on the main window.
Also, if I filter by "downloading" it says that there are no active torrents with that filter.

**Comment by erickok** [comment]
I can't reproduce this, just tested with 4.1.3 and everything seems okay. Tried different languages too. Can you try to update?
