### ISSUE TITLE
URL Download Error, Win 10, Qtorrent

### ISSUE THREAD

**Issue by moocower** [erickok/transdroid#451]
When using transdroid search I get an error on Qtorrent everytime I add a torrent. This started bout 2 months ago. I've reinstalled it, tried on different machines etc.. 

The error is: "URL Download Error 'Couldn't Download file at URL: <URL HERE>"

Running on Windows 10 with the latest qtorrent.

**Comment by erickok** [comment]
I can't reproduce. Can you send an eror report via the Help menu if you still experience this? Ideally with the link you are trying to add/start.
