### ISSUE TITLE
move turtle button to the left away from refresh

### ISSUE THREAD

**Issue by lachlan-00** [erickok/transdroid#453]
Can you separate the slow mode and refresh button. Preferably to the very left between the up/down counters.

I've hit it so many times accidentally I've had to set the limits up as I kept hitting the button with my thumb and not realising til days later.

**Comment by erickok** [comment]
The button use the default spacing for 'tool bars' under Android, and since a miss-click is so easy to undo, I don't feel much for moving button just for this. It also impacts other (non-phone) screens negatively. Sorry, hope you understand my decision.
