### ISSUE TITLE
Mandatory port specification breaks reverse proxied web interface

### ISSUE THREAD

**Issue by derpsec** [erickok/transdroid#454]
**Web server port selection should have a default value that can be erased if not needed.**

I use a reverse proxy to access my Deluge server over https.  The proxy takes care of the port redirection.  Adding the port to the request breaks it.

Ex. 

    https://myserv/deluge 
redirects to my internal webserver instance on http://5.5.5.5:8112
    
    https://myserv/deluge:8112
    https://myserv/deluge:443
will not work.   **Specifying a port should never be thought of as mandatory even if it is common.**

**Comment by erickok** [comment]
No TCP connection is possible without a port and I already use default; 8112 being the default for deluge http and 443 for https connections. You are just not entering the settings in the right fields. For a reverse proxy, use the 'host name' field only for your domain or ip (`myserv`) and enter the rest in the Folder setting. Enter the port in Port number (the very first setting under advanced settings).

**Comment by derpsec** [comment]
You are missing the point.  Port needs to be optional otherwise you get a malformed request hitting the proxy.

https://myserv/deluge != https://myserv/deluge:443

If have time later i'll fix it for myself and submit it to show you what i'm talking about.  It's literally as simple as allowing a null port field rather than making the null field return the default port.
________________________________

**Comment by erickok** [comment]
No sorry but it's fine as is. You just have the wrong url formed there. It
should be https://myserv:443/deluge <https://myserv/deluge:443> which
Transdroid constructs just fine if you use the right fields. You have
probably filled in the host name 'myserv/deluge' but that's not correct.
You should only fill in the host name in that field. Put '/deluge' in the
Folder setting.
