### ISSUE TITLE
Problems connecting to Dediseedbox

### ISSUE THREAD

**Issue by Suburbanno** [erickok/transdroid#456]

**Comment by Suburbanno** [comment]
connection problems, asks to check the internet, but everything works ....

**Comment by sinboi** [comment]
Transdrone is not working anymore with deluge. Its gone to worst. It can't connect to my deluge.

**Comment by erickok** [comment]
@sinboi Are you referring to Dediseedbox servers? Or in general? Perhaps you encounter #460 which I already solved and will release very soon.
