### ISSUE TITLE
Aria2 server and RSS feed

### ISSUE THREAD

**Issue by ferrvittorio** [erickok/transdroid#457]
Hi having problems passing correct link from RSS feed to an aria2 server
An 'index.php' is being passed, not .torrent nor .magnet
Thanks

**Comment by ferrvittorio** [comment]
The same link creates no problems on a transmission server

**Comment by erickok** [comment]
Can you send me the RSS feed that is malfunctioning? (Via email if you prefer; transdroid@2312.nl) Depending on the RSS feed used an index.php might be correct.

**Comment by ferrvittorio** [comment]
Hi!
For example this

http://feeds.feedburner.com/ilCorSaRoNero?format=xml

Cannot catch any torrent on this

Thanks

--
Vittorio Ferrando

Il ven 5 ott 2018, 22:02 Eric Kok <notifications@github.com> ha scritto:

**Comment by erickok** [comment]
That site has SSL issues; not properly signed. So your client will likely not accept connections to it. (ilcorsaronero.ch I mean)

**Comment by ferrvittorio** [comment]
Understood. Thanks

--


Il mer 24 ott 2018, 11:54 Eric Kok <notifications@github.com> ha scritto:
