### ISSUE TITLE
2.5.11 can't talk to insecure servers

### ISSUE THREAD

**Issue by bmdixon** [erickok/transdroid#460]
Apps that target Android 9 are prevented from allowing unencrypted connections by default. Most local torrent servers are insecure and securing them is not always straightforward. It's possible to allow insecure connections by modifying the network security config to allow those connections.

See https://android-developers.googleblog.com/2018/04/protecting-users-with-tls-by-default-in.html

**Comment by erickok** [comment]
Yup, I know. Already fixed. Will make a new release.

**Comment by erickok** [comment]
2.5.12 is pushed for release.
