### ISSUE TITLE
Connecting on local network won't work 2.5.12

### ISSUE THREAD

**Issue by rcbravo** [erickok/transdroid#463]
Since 2.5.12 version, when I'm at home connected thru wifi, transdrone can't connect to transmission. I get back to 2.5.10

**Comment by teckel12** [comment]
@deusexcalamus I agree, Android version. Works for me on 8.0 and doesn't work on 8.1. So it sounds like something changed in 8.1.  Maybe the ability to see the Wi-Fi SSID?

If that's the case, I would suggest just doing a fall-back method. Basically, have a primary and if that fails to connect, try thr fallback. That way, even if Android can't see the SSID, it can try both connections.

**Comment by teckel12** [comment]
@deusexcalamus It works for 8.0 but not 8.1 for me.  That's right where it stopped working.

**Comment by erickok** [comment]
cf https://stackoverflow.com/a/47847947/243165

**Comment by teckel12** [comment]
@erickok I don't have a problem turning on location permissions so this feature works. The nice thing about Android is that permissions can be disabled per app. If someone has a problem with this permission, they can disable it (and certain features will of course not work as a result).

In my opinion, just about everyone needs the feature to have local and remote connection settings. How else would it work? Right now (until this is fixed) I need to create two connections, one for local and one remote. Such a pain to always get connection errors then switch to the other connection each time.

Seems like a no-brainer.

**Comment by deusexcalamus** [comment]
Yeah I don't have a problem with this either, Transdroid is more or less the only way I interact with my local rutorrent server.

**Comment by erickok** [comment]
Fair enough, I have some development to do...

**Comment by akpegr** [comment]
@teckel12 thanks for the suggestion! I am having the same issue on the latest version and I was just editing the server on the fly when alternating between WiFi and data. Having different servers is much better.

I wouldn't mind a location permission too :)

**Comment by Nindohana** [comment]
> Fair enough, I have some development to do...

Hello ! Do you have any news about this feature ?
I really love this app and i would gladly help if you need any.
Thanks in advance for your feedback.

**Comment by ryanerwin** [comment]
Do you have any news about this feature ?
Do you have any news about this feature ?
IDo you have any news about this feature ?
> Do you have any news about this feature?

@Nindohana , It may not be possible with your network, but I've been working around it with a combination of Dynamic DNS and relying on a public IP address... With most modern routers, connections for a public IP that is actually on your network route properly (years ago this was often not the case).

Of course on more complex (schools or business) networks, this would be unworkable and you would really need the local IP feature...

Before messing with DynamicDNS, if your on a simple network (home, small business) see if routing via your public IP can get to the torrent listener... If just setup DynamicDNS on your torrent host and update the transdroid host address to the dynamic DNS hostname.

**Comment by Nindohana** [comment]
Thank you, I'll try this :)

**Comment by teckel12** [comment]
@ryanerwin This makes me think about possible solutions. I run a local DNS server (pi-hole). I should be able to specify a local DNS lookup to get around the issue.

What I've beed doing to date is I just have two server settings in Transdroid, one local and one remote. By simply adding a record to my local DNS, the problem for me would go away.

I still think it would be good to have it work inside Transdroid, as most people don't have a local DNS.

**Comment by teckel12** [comment]
BTW, it worked perfectly. For those running pi-hole and a local DNS server, here's the command:

`sudo pihole -a hostrecord <domain> <ip address>`

**Comment by erickok** [comment]
FYI I am working on this at the moment, adding permission request for 'fine location' such that I can access the wifi network name again.

**Comment by Nindohana** [comment]
> FYI I am working on this at the moment, adding permission request for 'fine location' such that I can access the wifi network name again.

Thank you very much.
Please let us now if you need any help to test this function.

**Comment by erickok** [comment]
Fixed by 78dd4bdc57cfe3894e6537ffa3fb4ec90a357945

**Comment by erickok** [comment]
I finally implemented this for the upcoming 2.5.15 release. You might have to enter the 'Local network' configurations setting again for Transdroid to ask for your location permission (which is the permission required to known what network you are connected to).

**Comment by Nindohana** [comment]
Thank you very much! That's an amazing work. Any ideas when will it be released?

**Comment by erickok** [comment]
Tonight

**Comment by teckel12** [comment]
Very nice! Thanks!

**Comment by Nindohana** [comment]
Awesome ! It works perfectly now. Thank you very much.

**Comment by teckel12** [comment]
Yup! Works great! Thanks!
