### ISSUE TITLE
Random crash since 2.5.12

### ISSUE THREAD

**Issue by Ansem93** [erickok/transdroid#467]
Hi everyone,
I have a Sony XZ1 with Android 8. I use it to monitor my deluge server. 
Since the latest update I get random crash. I tried to remove the widget but Transdrone keep crashing randomly even if I'm not connected to my LAN.
does anyone have the same problem? How can I help you more?

**Comment by erickok** [comment]
Try to update to 2.5.13 that I released today; I fixed the crashes in the
background service.

**Comment by lozbrown** [comment]
I've installed 2.5.13 and still get lots of random crashes.

**Comment by erickok** [comment]
@lozbrown Can you send me an error report? That should certainly not be related to this backgroudn service issue as that doesn't exist any more...

**Comment by lozbrown** [comment]
I sent you a error report 16 Nov 2018, 04:53

**Comment by lozbrown** [comment]
@erickok do you still need more info?

**Comment by erickok** [comment]
Please try new 2.5.14 release. Thanks!
