### ISSUE TITLE
Notifications

### ISSUE THREAD

**Issue by plkocev** [erickok/transdroid#468]
Hi,
First of all, thanks for your great job on this app. 
I am currently using v2.5.13 on Android v8. 0.0 and I cannot get the notifications to work. I would love to get notified when a new torrent has been added to my seedbox, but it doesn't happen. I have tried both transdroid and transdrone, unfortunately the result is the same. Please, when you have the time, fix it. Thanks.

**Comment by erickok** [comment]
Are you using Transdroid (form my site) or Transdrone (from the Play Store)? I am not sure yet why on some Android verisons the notification still don't work...

**Comment by plkocev** [comment]
I have tried both.
