### ISSUE TITLE
No connection to HTTPS (SSL) for rTorrent

### ISSUE THREAD

**Issue by Micdu70** [erickok/transdroid#470]
Transdrone log:
```
417 -- Tue Nov 06 23:33:38 GMT+01:00 2018 -- 3 -- Calling d.multicall2 with params [  main d.hash= d.name= d.state= d.down.rate= d.up.rate= d.peers_connected= d.peers_not_connected= d.... ]
418 -- Tue Nov 06 23:33:40 GMT+01:00 2018 -- 3 -- de.timroes.axmlrpc.XMLRPCException: org.apache.http.conn.HttpHostConnectException: Connection to https://myserver.com:443 refused
419 -- Tue Nov 06 23:33:40 GMT+01:00 2018 -- 3 -- ConnectionError exception: Error making call to d.multicall2 with params [  main d.hash= d.name= d.state= d.down.rate= d.up.rate= d.peers_connected= d.peers_not_connected= d.... ]: de.timroes.axmlrpc.XMLRPCException: org.apache.http.conn.HttpHostConnectException: Connection to https://myserver.com:443 refused
```

- Transdrone version is 2.5.13
- Android version is 8.0 (Oreo)
- My phone is an Honor 8

I'm trying to connect to my dedicated server with rtorrent/ruTorrent via HTTPS (I force all HTTP request to redirect to HTTPS, using Nginx webserver) but it seems that transdrone doesn't even try to connect to port 443 (because nothing is logged in Nginx logs). Without HTTPS, I can see error 301 messages in Nginx logs.

If I can avoid to use unsecure HTTP, it's better. :D

**Comment by erickok** [comment]
You should certianly use https. Did you check the https (ssl) option under Advanced Settings?

**Comment by Micdu70** [comment]
I checked HTTPS option of course. I think about TLS version and cipher compatibility. My webserver config only allow TLS 1.2 and 1.3, with a few ciphers.

**Comment by erickok** [comment]
TLS 1.3 is not supported by Android, but normally you should be fine with ciphers.

> Connection to https://myserver.com:443 refused

Looks like Transdroid does try to connect to your server. I am happy to help debug this further if you could give me (via mail perhaps at transdroid@2312.nl) the real url you use. It's probably just a misconfiguration.

**Comment by Micdu70** [comment]
I sent you an e-mail at transdroid@2312.nl.

**Comment by erickok** [comment]
Transdroid is refusing to connect to your HTTPS server.

> Cannot verify hostname: [redacted]

https://github.com/erickok/transdroid/blob/1cd65b80ac7742ad0a35f59bef8f3fb541151f11/app/src/main/java/org/transdroid/daemon/util/TlsSniSocketFactory.java#L141

> Cause: javax.net.ssl.SSLPeerUnverifiedException: No peer certificate

I don't know iuf this is your own server or what but there's something odd with your SSL certificate. (Or some new-ish thing that I do not support, perhaps.)

**Comment by Micdu70** [comment]
Nah... I don't have any issue with my SSL configuration.

I figured out what is wrong: For an unknown reason, when using server hostname, it returns the IPv6 server address. But I disabled IPv6 connectivity on my home router so it can't work (obviously)...

I will investigate more on my side (Configuration from my nameserver provider and from my router).

**Comment by erickok** [comment]
Yes the SSL setup seems fine indeed. I think some (new?) specific SSL feature that Transdroid doesn't support (or Apache HttpClient, by that extend, which I use still in Transdroid). Not sure what to do...

**Comment by erickok** [comment]
Okay that was just me testing on Android 4.4 and your cipher cuits are not supported there... 😌

**Comment by Micdu70** [comment]
Trying the (S)FTP download feature (with AndFTP), it gave me a hint:

![AdGuard local VPN issue](https://i.imgur.com/q2iT7Ad.jpg)

So finally found the cause: "AdGuard" (using a VPN tunnel) app...

To fix it I went into `AdGuard Settings > Advanced > Low level settings`

Checked `pref.vpn.ipv6.bypass` and no more issue! 👍
