### ISSUE TITLE
Update notice > link not working

### ISSUE THREAD

**Issue by preliot** [erickok/transdroid#478]
Whenever i get an update notice on transdroid (or transdroid search) it opens the correct link very briefly in my browser. Right after it resets to the previous opened tabs. Is this transdroid related or something on my phone?

OS: LineageOS (Android 7.1.2)
Browser: Chrome 71

**Comment by erickok** [comment]
That's normal; the link is a redirect. It should still start the download though. Alternatively you can get the download manually from www.transdroid.org

**Comment by preliot** [comment]
Somehow it does not work as intended. I get the alert 'update available', the link works 'see a quick url to transdroid' and then my previous opened tabs are loaded. My alternative is to download them manually.
Perhaps an idea: Instead of a redirect download (which is somehow blocked) a link to the page with the update?

**Comment by erickok** [comment]
Thanks for the suggestion. I think it is your OS, network or browser version that is for some reason not starting the download. I have not yet received similar reports and cannot reproduct the behaviour you describe. Here indeed also the link is 'quickly opened and then I see my tabs' but also a download is initiated. Will act further if I get more/similar reports.

**Comment by preliot** [comment]
I cannot ask for more, thanks @erickkok. Closed for now.
