### ISSUE TITLE
Issue adding torrents from RSS feeds

### ISSUE THREAD

**Issue by SuissoNaBisso9** [erickok/transdroid#485]
Hi !

yesterday evening I added some new RSS feeds to my Transdroid app, already had 3 feeds from another tracker working perfectly both in reading feed and adding torrents to my client.
Since I added these new feeds (for a new tracker), I can still read the various feeds but I can't add any new torrent to my client from all the feeds I have, even the ones that were working previously.

Anything happened on this RSS functionality ?

Thanks

**Comment by erickok** [comment]
Don't know of any issue and nothing really changed. Could you add a log
here (via Help menu in the app)?

**Comment by SuissoNaBisso9** [comment]
issue partially resolved ! could add torrents from Yggtorrent RSS feeds. However for Downloadville feeds I still can't but I figured out why : on this specific tracker it is required to say "thank you" to get the torrent file, so there is a specific button to push first before you receive the .torrent....I guess there is nothing to do for that !

Thanks

**Comment by erickok** [comment]
Yes only direct links to usabled torrent or magnet linsk would work... Thanks for the follow-up.
