### ISSUE TITLE
BitComet开发进度咋样了。。

### ISSUE THREAD

**Issue by 1265578519** [erickok/transdroid#488]
来问下，很久之前就介绍说要出了，到现在还是（即将推出）

**Comment by 1265578519** [comment]
![1](https://user-images.githubusercontent.com/6442439/54127765-89646100-4445-11e9-8818-3b54a877ab4d.png)
看到有了，我试下

**Comment by 1265578519** [comment]
不能用，有BUG，，没办法添加和指定端口

**Comment by 1265578519** [comment]
强制要使用80端口，不能自定义。而且已经完成任务全显示下载中。
![1](https://user-images.githubusercontent.com/6442439/54128548-4c00d300-4447-11e9-8db7-835489c32f43.png)

**Comment by erickok** [comment]
To set a custom port, use the Port number setting, which is the first under Advanced Settings.

Duplicate of #441 (see there for a screenshot; all the way in the top you see the 'Port number' setting)

**Comment by 1265578519** [comment]
@erickok 我参考了他，还是没有任何办法，你能修复下这个BUG？
