### ISSUE TITLE
Active torrents filter displays all torrents

### ISSUE THREAD

**Issue by dpsenner** [erickok/transdroid#490]
## Steps to reproduce

When talking to rtorrent transdrone displays all torrents when selecting "Status"->"Active" instead of just the torrents that are active.

## What would You expect to happen instead?

transdrone should display only the active torrents as reported in rtorrent, ruTorrent, etc.

**Comment by dpsenner** [comment]
Might be related to issue #55.

**Comment by erickok** [comment]
What do you consider an 'active torrent'? Transroid considers all torents active if they are in seeding or downloading state, regardless of any actual transfer (connected peers) going on. If you prefer to only see torrents in this view that are currectly having > 0kB/s up- or download, use the 'Treat dormant torrents as inactive' option under Settings -> System.

**Comment by dpsenner** [comment]
Awesome, a configuration switch that i didn't know it exists. :+1:

**Comment by dpsenner** [comment]
Unfortunately, the configuration option has an unintended negative side effect. Currently there is a torrent being downloaded but it is not shown in "Downloading" because it has no seeders (0Kb/s transfer speed). This is unexpected for me and therefore I am reopening this issue.

**Comment by erickok** [comment]
I'm afraid that you have to be a bit more precise then what you want to see in an 'active torrents' filter. All unfinished torrents AND all seeding torrents ONLY if they are actively having leechters (> 0kB/s)?

**Comment by dpsenner** [comment]
Coming from rtorrent, active torrents are to me torrents that satisfy any of the following conditions:

* Hash checking
* Incomplete (less than total size downloaded)
* Upload speed > 0
* Download speed > 0
* Number of connected peers > 0

**Comment by erickok** [comment]
I decided not to go ahead with this - as it stand users seem very happy with the current sorting and filtering, and as such I am not inclined to change anything. Sorry!

**Comment by dpsenner** [comment]
Thanks for sharing your opinion and the efforts you are donating to the users.
