### ISSUE TITLE
Port number optional

### ISSUE THREAD

**Issue by Tiwing1** [erickok/transdroid#491]
Reverse proxy takes care of port number, would like to just put url and not have 8112 forced at end of url. Cheers

**Comment by erickok** [comment]
It's the very first option under Advanced Settings. (Note there is no header.) Duplicate of #314.

**Comment by supermamie** [comment]
I had the exact same problem and I needed this comment to find that there was a port option.
It is really not visible and looked like a title.
Thanks @erickok :smiley:
