### ISSUE TITLE
比特彗星的进度不会更新，要点刷新按钮。

### ISSUE THREAD

**Issue by 1265578519** [erickok/transdroid#493]
![3](https://user-images.githubusercontent.com/6442439/55479927-ba554180-5651-11e9-9ba7-3ab0927ec16b.png)
![2](https://user-images.githubusercontent.com/6442439/55479929-ba554180-5651-11e9-8c6a-ebf572599179.png)
![QQ图片20190403204500](https://user-images.githubusercontent.com/6442439/55479930-baedd800-5651-11e9-9123-41ac261fd510.png)
比特彗星的进度不会更新，app上要点刷新按钮。
上方的时间也不对，而且进度显示下载中，而不是做种。

**Comment by erickok** [comment]
Alright I have to check this some time - might be that BitComet API changed a bit over the newer releases, or even that there is an translation issue as I remember the times and such being translated rather than un unit time.

**Comment by 1265578519** [comment]
/panel/task_list_xml
/panel/option_set?key=down_rate_max&value=123
/panel/option_set?key=up_rate_max&value=123
/panel/tasklist_action?id=start_all_download
/panel/tasklist_action?id=start_all_seeding
/panel/tasklist_action?id=stop_all
/panel/tasklist_action?id=start_all_download
/panel/tasklist_action?id=suspend_all

http://wiki.bitcomet.com/ajax_interface_for_remote_download

wiki找到的，不知道是否正确，如果不对要联系下比特彗星官方管理员。

**Comment by Vstory** [comment]
@erickok qBittorrent also has this problem.

**Comment by 1265578519** [comment]
请问什么时候可以修复它？我查看task_list_xml是可以正常工作的

**Comment by bwitt** [comment]
> qBittorrent also has this problem.

For me on qBittorrent 4.3.9 seems to update ok with auto updates enabled.
