### ISSUE TITLE
无法使用自定义端口，只能用80端口，无法修改为其他的

### ISSUE THREAD

**Issue by 1265578519** [erickok/transdroid#494]
无法使用自定义端口，只能用80端口，无法修改为其他的
![1](https://user-images.githubusercontent.com/6442439/55480544-21bfc100-5653-11e9-9d52-4814d8a82610.png)
![2](https://user-images.githubusercontent.com/6442439/55480545-21bfc100-5653-11e9-978f-610b9726171f.png)

被Closed掉了，不知道回复能不能看到，，重新发一个吧
https://github.com/erickok/transdroid/issues/488

**Comment by 1265578519** [comment]
我瞎了。。。截图后也找到了port选项。。我关了吧

**Comment by DrEastex** [comment]
> 我瞎了。。。截图后也找到了port选项。。我关了吧

我为什么没看到呢-。-？另一个是本地端口啊
