### ISSUE TITLE
Missing italian translation for widget

### ISSUE THREAD

**Issue by Ansem93** [erickok/transdroid#496]
Hi everyone,
Can someone tell my how can I help adding the correct translation at the missing voice in the screenshot?
![immagine](https://user-images.githubusercontent.com/6626218/56082514-e161ff00-5e19-11e9-8b02-80cecece7ed1.png)
I don't know which file should I edit :( Or if you tell me the english words I will write here the correct translation.

**Comment by erickok** [comment]
The Italian translations are here: https://github.com/erickok/transdroid/blob/master/app/src/main/res/values-it/strings.xml

**Comment by Ansem93** [comment]
<string name="action_sort_alpha">Nome</string>
  <string name="action_sort_status">Stato</string>
  <string name="action_sort_done">Data fine</string>
  <string name="action_sort_added">Data inserimento</string>
  <string name="action_sort_percent">Percentuale scaricata</string> -> Missing
  <string name="action_sort_downspeed">Velocità di download</string> -> Missing
  <string name="action_sort_upspeed">Velocità di upload</string> -> This is a better translation
  <string name="action_sort_ratio">Rapporto</string>
<string name="action_sort_size">Dimensione</string> -> Missing

From what I can understand, it only display 6 sorts out of 9, so it complete the missing 3 with the default one:
<string name="action_sort_alpha">Nome</string>

I?m not sure why it doesn't display action_sort percent,downspeed and size :(

**Comment by erickok** [comment]
Oh wow you just discovered a bug that was in there since 2013. 🤪

Fixed! 👯‍♀️
