### ISSUE TITLE
Cannot connect

### ISSUE THREAD

**Issue by cableghost** [erickok/transdroid#498]
Although I can connect to my qbittorrent client with Transdrone, I cannot using Transdroid. I can successfully search, but not connect to download.

All the settings are the same... I'm at a loss as why this is happening.

Note I completely cleared data and started fresh.

**Comment by erickok** [comment]
Well that's beyond weird, it's the exact same code base. Perhaps you get
get a connection log via Settings > Help > Send error report?

**Comment by cableghost** [comment]
Here's the log...

Transdroid 2.5.14 (234)
qBittorrent settings: http://admin@domain.net:8183

Connection and error log:
106 -- Sat Apr 27 10:06:36 CDT 2019 -- 3 -- Creating adapter for TORRENTS of type qBittorrent: connected to <unknown ssid> and configured local network is SSID
107 -- Sat Apr 27 10:06:36 CDT 2019 -- 3 -- Schedule server checker job
108 -- Sat Apr 27 10:06:36 CDT 2019 -- 3 -- Schedule periodic jobInfo success, request{id=1, tag=server_checker, transient=false}, interval 03:00:00, flex 03:00:00
109 -- Sat Apr 27 10:06:36 CDT 2019 -- 3 -- Schedule rss checker job
110 -- Sat Apr 27 10:06:36 CDT 2019 -- 3 -- Schedule periodic jobInfo success, request{id=2, tag=rss_checker, transient=false}, interval 03:00:00, flex 03:00:00
111 -- Sat Apr 27 10:06:36 CDT 2019 -- 3 -- Creating adapter for TORRENTS of type qBittorrent: connected to <unknown ssid> and configured local network is SSID
112 -- Sat Apr 27 10:06:36 CDT 2019 -- 3 -- Error: org.apache.http.conn.HttpHostConnectException: Connection to http://domain.net:8183 refused
113 -- Sat Apr 27 10:06:36 CDT 2019 -- 3 -- qBittorrent API version is 1
114 -- Sat Apr 27 10:06:36 CDT 2019 -- 3 -- Error: org.apache.http.conn.HttpHostConnectException: Connection to http://domain.net:8183 refused
115 -- Sat Apr 27 10:06:36 CDT 2019 -- 3 -- Error: org.apache.http.conn.HttpHostConnectException: Connection to http://domain.net:8183 refused
116 -- Sat Apr 27 10:06:36 CDT 2019 -- 3 -- Error: org.apache.http.conn.HttpHostConnectException: Connection to http://domain.net:8183 refused
117 -- Sat Apr 27 10:06:36 CDT 2019 -- 3 -- Run job, request{id=2, tag=rss_checker, transient=false}, waited 00:00:00, interval 03:00:00, flex 03:00:00
118 -- Sat Apr 27 10:06:36 CDT 2019 -- 3 -- Run job, request{id=1, tag=server_checker, transient=false}, waited 00:00:00, interval 03:00:00, flex 03:00:00
119 -- Sat Apr 27 10:06:36 CDT 2019 -- 3 -- Executing request{id=2, tag=rss_checker, transient=false}, context PlatformJobService
120 -- Sat Apr 27 10:06:36 CDT 2019 -- 3 -- ConnectionError exception: org.apache.http.conn.HttpHostConnectException: Connection to http://domain.net:8183 refused
121 -- Sat Apr 27 10:06:36 CDT 2019 -- 3 -- Executing request{id=1, tag=server_checker, transient=false}, context PlatformJobService
122 -- Sat Apr 27 10:06:36 CDT 2019 -- 3 -- Finished job{id=2, finished=true, result=SUCCESS, canceled=false, periodic=true, class=RssCheckerJob, tag=rss_checker}
123 -- Sat Apr 27 10:06:36 CDT 2019 -- 3 -- ConnectionError exception: org.apache.http.conn.HttpHostConnectException: Connection to http://domain.net:8183 refused
124 -- Sat Apr 27 10:06:36 CDT 2019 -- 3 -- Creating adapter for TORRENTS of type qBittorrent: connected to <unknown ssid> and configured local network is SSID
125 -- Sat Apr 27 10:06:36 CDT 2019 -- 3 -- Finished job, request{id=2, tag=rss_checker, transient=false} SUCCESS
126 -- Sat Apr 27 10:06:36 CDT 2019 -- 3 -- Error: org.apache.http.conn.HttpHostConnectException: Connection to http://domain.net:8183 refused
127 -- Sat Apr 27 10:06:36 CDT 2019 -- 3 -- qBittorrent API version is 1
128 -- Sat Apr 27 10:06:36 CDT 2019 -- 3 -- Error: org.apache.http.conn.HttpHostConnectException: Connection to http://domain.net:8183 refused
129 -- Sat Apr 27 10:06:36 CDT 2019 -- 3 -- Error: org.apache.http.conn.HttpHostConnectException: Connection to http://domain.net:8183 refused
130 -- Sat Apr 27 10:06:36 CDT 2019 -- 3 -- Finished job{id=1, finished=true, result=SUCCESS, canceled=false, periodic=true, class=ServerCheckerJob, tag=server_checker}
131 -- Sat Apr 27 10:06:36 CDT 2019 -- 3 -- Finished job, request{id=1, tag=server_checker, transient=false} SUCCESS
132 -- Sat Apr 27 10:06:38 CDT 2019 -- 3 -- Error: org.apache.http.conn.HttpHostConnectException: Connection to http://domain.net:8183 refused
133 -- Sat Apr 27 10:06:38 CDT 2019 -- 3 -- qBittorrent API version is 1
134 -- Sat Apr 27 10:06:39 CDT 2019 -- 3 -- Error: org.apache.http.conn.HttpHostConnectException: Connection to http://domain.net:8183 refused
135 -- Sat Apr 27 10:06:39 CDT 2019 -- 3 -- Error: org.apache.http.conn.HttpHostConnectException: Connection to http://domain.net:8183 refused
136 -- Sat Apr 27 10:06:39 CDT 2019 -- 3 -- Error: org.apache.http.conn.HttpHostConnectException: Connection to http://domain.net:8183 refused
137 -- Sat Apr 27 10:06:39 CDT 2019 -- 3 -- ConnectionError exception: org.apache.http.conn.HttpHostConnectException: Connection to http://domain.net:8183 refused
138 -- Sat Apr 27 10:06:39 CDT 2019 -- 3 -- ConnectionError exception: org.apache.http.conn.HttpHostConnectException: Connection to http://domain.net:8183 refused
139 -- Sat Apr 27 10:06:57 CDT 2019 -- 3 -- Creating adapter for TORRENTS of type qBittorrent: connected to <unknown ssid> and configured local network is SSID
140 -- Sat Apr 27 10:07:48 CDT 2019 -- 3 -- Creating adapter for TORRENTS of type qBittorrent: connected to <unknown ssid> and configured local network is SSID
141 -- Sat Apr 27 10:07:51 CDT 2019 -- 3 -- Error: org.apache.http.conn.HttpHostConnectException: Connection to http://domain.net:8183 refused
142 -- Sat Apr 27 10:07:51 CDT 2019 -- 3 -- qBittorrent API version is 1
143 -- Sat Apr 27 10:07:51 CDT 2019 -- 3 -- Error: org.apache.http.conn.HttpHostConnectException: Connection to http://domain.net:8183 refused
144 -- Sat Apr 27 10:07:51 CDT 2019 -- 3 -- Error: org.apache.http.conn.HttpHostConnectException: Connection to http://domain.net:8183 refused
145 -- Sat Apr 27 10:07:51 CDT 2019 -- 3 -- Error: org.apache.http.conn.HttpHostConnectException: Connection to http://domain.net:8183 refused
146 -- Sat Apr 27 10:07:51 CDT 2019 -- 3 -- ConnectionError exception: org.apache.http.conn.HttpHostConnectException: Connection to http://domain.net:8183 refused
147 -- Sat Apr 27 10:07:51 CDT 2019 -- 3 -- ConnectionError exception: org.apache.http.conn.HttpHostConnectException: Connection to http://domain.net:8183 refused

**Comment by cableghost** [comment]
I neglected to mention one observation...I notice Transdrone requires access to device location for SSID identification, but Transdroid does not, or at least I don't recall seeing that request.

**Comment by erickok** [comment]
What version of Transdroid do you have?

**Comment by erickok** [comment]
I see you're still on 2.5.14 but try 2.5.15 whicg fixed the location
permission thing.

**Comment by cableghost** [comment]
Working again, upon updating. Thanks.
