### ISSUE TITLE
Transmission preemptive auth breaks digest negotiation

### ISSUE THREAD

**Issue by eahamberg** [erickok/transdroid#499]
The update enforcing preemptive basic authentication does not allow for negotiation of other authentication methods (specifically digest auth) supported by reverse proxy configurations.

**Comment by eahamberg** [comment]
Apologies for being unclear. This report applies to the Transmission module.

**Comment by erickok** [comment]
Right - it's clear. Probably related to the issue where a 409 is kept being
thrown if using a reverse proxy.

**Comment by eahamberg** [comment]
The reverse proxy sees the statically added "Authorization" http request header, populated with an auth scheme of "HTTP Basic" and the base64 user:pass string, and simply responds with a 401, rather than allowing the httpclient class to automatically negotiate a digest handshake for authentication. Removing the static header from the TransmissionAdapter class (comment lines 423-426) and the authentication works with non-basic-auth proxies, as well. Might you add a "preemptive basic authentication" boolean toggle for use in the conditional on line 423?
I've been working around this by building the app using the previous commit of TransmissionAdapter.java, FWIW.

**Comment by eahamberg** [comment]
Your update works perfectly, and the http client code is once again able to negotiate between http basic and http digest authentication. Thank you, sir!
