### ISSUE TITLE
"Internal error building request" on qbittorrent 4.1.6 with Traefik

### ISSUE THREAD

**Issue by kamilmirza** [erickok/transdroid#500]
getting "Internal error building request" on qbittorrent 4.1.x with Traefik (reverse proxy)
port is set to 0 (works for Traefik) 
have the exact same settings with deluge server and it works fine
everything is on docker

**Comment by erickok** [comment]
It's hard for me to check now, but a port 0 sounds very weird. Did you try
to set this in Transdroid (under Port number in Advanced Settings)?

**Comment by kamilmirza** [comment]
if I use port 80 or 443 or it says "Error during communication; check your connections" when using Traefik 
i have the exact same config with deluge server (port 0, traefik) and it works 
yes I am referring to Port Number in Advanced Settings

**Comment by erickok** [comment]
Can you reach the qBittorrent web interface from your mobile browser?

**Comment by kamilmirza** [comment]
yes of course

**Comment by erickok** [comment]
And that connects to which port?

**Comment by kamilmirza** [comment]
qb.domain.com
Traefik handles redirects 80 to 443

**Comment by erickok** [comment]
The if you use SSL, use port number 443, otherwise port 80. Sorry I can
give only limited support for reverse proxy setups as really there are too
many to know about all of them. In the end as long as Transdroid can
connect to the right endpoint it will work. You might need to set up the
'folder' setting (perhaps to /)

**Comment by kamilmirza** [comment]
i have resolved this issue by disabling this on qbittorrent 
**qBittorrent > Options > Web UI > Enable Host header validation**

**Comment by lukasmrtvy** [comment]
@erickok can confirm, browser (chrome) works ok, transdroid nor qBittorrent  controller does not work unless  Enable Host header validation in qBittorrent is unchecked.
There must be something wrong with User Agent, Request headers...
