### ISSUE TITLE
Deluge WebUI/reverse proxy behind HTTPS

### ISSUE THREAD

**Issue by XmemphistoX** [erickok/transdroid#501]
I have a reverse proxy setup for deluge webui and when I enter in the information on transdroid, it always auto appends port 8112.  IE) https://domain/deluge:8112 

 I don't see anyway to remove this.  Accessing the reverse proxy webui works https://domain/deluge

**Comment by erickok** [comment]
Enter the port in the port number settings, which is the first under
Advanced Settings. Use 80 for http and 443 for https.

**Comment by XmemphistoX** [comment]
adding :443 to the url in a web browser unfortunately makes the site unaccessible even though its https with 443 as the port.

https://domain/deluge:443 doesn't properly pull up the page.

**Comment by erickok** [comment]
You have to figure our first what port your are running on. Then set this in Transdroid - use the dedicated setting for that, do NOT appenmd it to the IP (or domain) setting. The Port number is the very first setting under Advanced Settings.
