### ISSUE TITLE
Deluge 2.x seems to have broken RPC support

### ISSUE THREAD

**Issue by Sanaki** [erickok/transdroid#502]
I've had Deluge working for ages now on 1.3.16. Finally decided to update to 2.0.3 and I now can't connect using the exact same settings. I've checked to verify the obvious issues, nothing stands out. SSL cert's the same, port's the same, users and passwords haven't changed, etc. If anyone has insight, I'd love to hear it. Otherwise, seems it may need updates on the app side of things.

**Comment by RobertSmits** [comment]
RPC in deluge 2.x has definitely changed, can't even connect Deluge 1.x client to 2.x daemon
