### ISSUE TITLE
Search is returning 0 results for "LimeTorrents" and "The Pirate Bay (proxied)"

### ISSUE THREAD

**Issue by WardenHDresden** [erickok/transdroid#503]
In the last week or two, I've noticed that the Transdroid Search returns 0 results from "LimeTorrents" and "The Pirate Bay (proxied)", regardless of what search terms I use.  I've done test searches for simply "friends" and received 0 results from both site.

**Comment by MB52** [comment]
The problem seems to persist.
Have experienced the same problem in recent months.

**Comment by erickok** [comment]
Yeah TPB doesn't work any more with scraping... See https://github.com/erickok/transdroid-search/issues for issues with search providers.
