### ISSUE TITLE
Transdroid internal error buidling request with apache reverse proxy

### ISSUE THREAD

**Issue by Luticus** [erickok/transdroid#504]
I'm running Debian Buster with qbittorrent-nox 4.1.5-1 and transdroid 2.5.15.  I'm trying to connect to qbittorrent through an apache 2.4 proxy.  This used to work when I was using the Debian Stretch version of qbittorrent.  Now for some reason I can connect directly, but not through the proxy when using transdriod.  It says internal error building request.  I happen to know that qbittorrent-nox webui works through the GUI and so does a firefox plugin I use.  So the proxy does still work.  I feel like something about the way transdroid connects may be breaking in the proxy now?  Not sure.

My apache logs contain entries like these:
173.197.1.184 - - [30/Jun/2019:15:16:27 -0400] "POST /sync/maindata?rid=0 HTTP/1.1" 302 4811 "-" "Transdroid Torrent Connect"
173.197.1.184 - - [30/Jun/2019:15:16:27 -0400] "GET /index.php/login HTTP/1.1" 200 10198 "-" "Transdroid Torrent Connect"
173.197.1.184 - - [30/Jun/2019:15:16:28 -0400] "POST /json/events HTTP/1.1" 302 1039 "-" "Transdroid Torrent Connect"

Please let me know if there are any suggestions or if there is anything that can be done. 

Thanks!

**Comment by Luticus** [comment]
After some research, unchecking the host header validation in qbittorrent fixes this issue.  I'm not sure this should close the ticket as that seems like an important security feature and I'm sure people will want to put their qbittorrent behind a reverse proxy, however, it does at least give a starting point.  

Apache log item that clued me in:
173.197.1.184 - - [25/Oct/2019:00:29:09 -0400] "POST /json/events HTTP/1.1" 401 654 "-" "Transdroid Torrent Connect"
401 is unauthorized which lead to me check security settings in qbittorret as the possible culprit.  

Well at least it works now.

**Comment by erickok** [comment]
To the best of my knowledge this is a problem onyl because the reverse proxy sets the referrer header to something and that something is not 'correct'. I don't set the header at all from Transdroid and it 'just works' - without a proxy of course - leading me to believe it is not a requirement for the initial call. Could you check the next release where I do preemptive authorication (to support qBittorrent 4.2) and see if that resolves your issue?
