### ISSUE TITLE
Download files from server

### ISSUE THREAD

**Issue by ksga** [erickok/transdroid#507]
Not really an issue, but more a nooob question.
I'm trying to download a file from an already downloaded torrent to my device.
Long pressing the file brings up the download icon, but pressing it generates the error:
"No app found that can download..."

What apps are supported?
I've tried adding as much information as possible to the server setup as possible.
I'm using Turbo Client on Android 9, and rTorrent on the server.

Best regards

**Comment by erickok** [comment]
You have an FTP or similar set up? ANy app that supports ftp:// links shoud work. https://play.google.com/store/apps/details?id=nl.nl2312.ftplinkdownloader is one, though very, very simple.  AndFTP is technically supported as well, though a bit of a pain to set up.
