### ISSUE TITLE
Deluge 2 RPC : Magnet is not supported.

### ISSUE THREAD

**Issue by nemonein** [erickok/transdroid#508]
I'm using Deluge 2 (2.0.3) on Ubuntu, and Transdroid 2.5.16.
When I tried to add magnet link in Transdroid, I get this message.

```Your torrent client does not support this operation.```

.torrent file works fine, but magnet does not.
Is magnet not supported yet?

**Comment by erickok** [comment]
It's a bug - https://github.com/erickok/transdroid/blob/master/app/src/main/java/org/transdroid/daemon/Daemon.java#L365 should include Deluge2Rpc also.

**Comment by nemonein** [comment]
Thanks.
I'll wait for the next release.
