### ISSUE TITLE
deluge issue with reverse proxy

### ISSUE THREAD

**Issue by SSoft7** [erickok/transdroid#513]
Hi,

I am trying to connect using deluge RPC method but the connection fails.

> Deluged: 1.3.15

Error log:

```
Transdroid 2.5.16 (236)
DelugeRpc settings: https://demouser@test12345.myserver.com:443/myapps/deluge/

Connection and error log:
2 -- Fri Nov 22 23:20:46 GMT+05:30 2019 -- 3 -- ConnectionError exception: incorrect header check
3 -- Fri Nov 22 23:21:26 GMT+05:30 2019 -- 3 -- ConnectionError exception: incorrect header check
```

I could not find anything in the webserver log (nginx). The reverse proxy is working fine through web browser and it does not have any additional authentication. I recall that this worked a while ago (maybe few months).
I also tried appending /json to the folder path in settings, But its all same. SSL is not an issue.

**Comment by erickok** [comment]
You seem to confuse the rpc protocol with the web interface. In rpc there
is no path, so no /json. And there is no browser either. If you mean a
reverse proxy with rpc communication, that also doesn't really make sense.
Deluge rpc doesn't use http...

Op vr 22 nov. 2019 19:38 schreef SSoft7 <notifications@github.com>:

**Comment by SSoft7** [comment]
Ok, 
So RPC here means direct communication with the deluge daemon. got it.
Actually, transmission have /rpc in its URL which is why I thought deluge's /json endpoint would be something similar.
It is working fine with daemon port. just need to ticket accept all SSL.
