### ISSUE TITLE
Connection to qBittorrent 4.2.0 not possible

### ISSUE THREAD

**Issue by Fischy667** [erickok/transdroid#516]
With version 4.2.0 qBittorrent is using PBKDF2 to store the WebUI password. Therefore it is not possible to connect to qBittorrent 4.2.0 with Transdroid.

**Comment by convexshiba** [comment]
Showing "Internal error building request" with 4.2.0 on Windows, not sure if it's related.

**Comment by co5mo** [comment]
same here

**Comment by pigr8** [comment]
yes, here too.

```
Transdrone 2.5.15 (235)
qBittorrent settings: http://uuuu@xx.xx.xx.xx:pppp

Connection and error log:
1 -- Fri Dec 06 19:51:57 GMT+01:00 2019 -- 3 -- qBittorrent API version is 1
2 -- Fri Dec 06 19:51:58 GMT+01:00 2019 -- 3 -- ParsingFailed exception: org.json.JSONException: End of input at character 0 of 
3 -- Fri Dec 06 19:51:58 GMT+01:00 2019 -- 3 -- ParsingFailed exception: org.json.JSONException: End of input at character 0 of 
```

**Comment by xrosellbcn** [comment]
qbittorrent 4.20 drop support for old WebUI API (QBitTorrent release notes -> WEBUI: Drop legacy WebAPI support (glassez)):

https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-Documentation

Now only supports Web API versión 2.X: 

https://github.com/qbittorrent/qBittorrent/wiki/Web-API-Documentation

There's some changes needed on "QBittorrentAdapter.java" to support new calls.

Better stay on 4.1.9 for now.

**Comment by fbrav** [comment]
same here

**Comment by erickok** [comment]
@H3mul has shown interest to work on fixing this. Myself I don't have time at the moment, I am very sorry. But once I do, I will post here.

**Comment by dausruddin** [comment]
I never coded in Java nor for Android and I am not an expert in programming either, but this is my first try.
I have made changes by my own in https://github.com/dausruddin/transdroid/commit/548e866d2020227a7704381644fb7c310d1cb3f8
There are a few unnecessary lines that I used to debug and I am too lazy to remove it as I have it working now.
I have tested some basic functions like adding, deleting, listing, and they are working.

I am not sure what should I do now, but here I have built them for you using my own key. So I don't think you can install it on-top of the original app.

Hopefully it help someone until we get an official fix
[app-full-release.zip](https://github.com/erickok/transdroid/files/3962027/app-full-release.zip)
[app-lite-release.zip](https://github.com/erickok/transdroid/files/3962028/app-lite-release.zip)

**Comment by layanto** [comment]
I had a quick look at @dausruddin changes, looks good - only noticed one typo (double ;) on line 226. Can @dausruddin changes be merged into this project and tag a new release?

**Comment by H3mul** [comment]
I found a few bugs after a cursory glance. For instance, `/api/v2/torrents/resume` expects `hashes` instead of `hash`, so @dausruddin 's version cant resume correctly. Ill review all implemented commands, test and submit a pull request by next week if someone doesn't beat me to it :)

**Comment by erickok** [comment]
That'd be very welcome.

Op za 14 dec. 2019 21:26 schreef Phil Dykman <notifications@github.com>:

**Comment by dausruddin** [comment]
So, I fixed the URL parameters and fixed pausing functions too in https://github.com/dausruddin/transdroid/commit/d1facac2c1e86ae7a305ff061f655fc2dabcad08
tested and working fine now.


[app-lite-release-2.zip](https://github.com/erickok/transdroid/files/3965370/app-lite-release-2.zip)
[app-full-release-2.zip](https://github.com/erickok/transdroid/files/3965371/app-full-release-2.zip)

**Comment by tazeat** [comment]
Parsing a version to float for versions seems sketchy... Seems like it should be parsed similar to how the client version parser works with a split and parsing each component as an int

**Comment by khat17** [comment]
Looking forward to fix and official update. Until then I've rolled back QBT and will run 4.1.x until this is done.

**Comment by Ansem93** [comment]
I really hope for an update of transdroid :(

**Comment by H3mul** [comment]
Apologies for the hiatus, I was hoping to get this done before a move on New Years eve and didnt have the time :)

**Comment by khat17** [comment]
That's fine. Holidays and all that. We appreciate all that is done on this project by all participants. Keep up the good work!

**Comment by erickok** [comment]
I have tested the PR #523 and made some additional fixes, simplifications and updates. I have tested with qb versions 3.3.16, 4.1.9 and the (lastest) 4.2.1. 

Technically, it will use the v2 api when you are on qBittorrent 4.1 or higher. I'd love some testing, but without negative results I will try to release tomorrow.

**Comment by Ansem93** [comment]
I can test with qBittorrent 4.2.1 as soon as I'm home and give a feedback :)

**Comment by erickok** [comment]
Released as version 2.5.17

**Comment by Ansem93** [comment]
please update it on f-droid too!

**Comment by erickok** [comment]
I am not the maintainer on the project on F-Droid, but 'they' can just rebuild from the master branch.

**Comment by bwitt** [comment]
f-droid updates should happen automatically but they can take a number of days for it to work through their pipeline.

**Comment by layanto** [comment]
I kept getting Access denied (please check your settings). This errors comes and goes. Hit refresh and it says Connected, meaning username and password is correct. Anyone else have the same issue? I use nginx as https termination before proxy to qbittorrent.

**Comment by stevenflesch** [comment]
> I kept getting Access denied (please check your settings). This errors comes and goes. Hit refresh and it says Connected, meaning username and password is correct. Anyone else have the same issue? I use nginx as https termination before proxy to qbittorrent.

I see it as well, using `caddy` as an https proxy.

**Comment by layanto** [comment]
Noticed that the docs for qbittorrent and nginx proxy config was changed recently - https://github.com/qbittorrent/qBittorrent/wiki/NGINX-Reverse-Proxy-for-Web-UI
After updating my nginx proxy conf, haven't had Access denied yet. Will keep checking in next few days and report back here.

**Comment by hoistedPetard** [comment]
Getting the same here, "Access Denied" in Transdroid 2.5.1.7 against QBT 4.2.1 64bit.

**Comment by awsms** [comment]
Damn.. I wish I knew about this issue before upgrading to 4.2.1 :(

**Comment by khat17** [comment]
> Damn.. I wish I knew about this issue before upgrading to 4.2.1 :(

Just install an older version. Your settings should be retained. It will just validate existing files.

**Comment by zaggash** [comment]
I think it is because of the "version" API call being behind authentication.
See here:
https://github.com/qbittorrent/qBittorrent/wiki/Web-API-Documentation#general-information
```
    All API methods are under /api/v2/APIName/methodName, where APIName is a certain subgroup of API methods whose functionality is related.
    Either GET or POST can be used as the request type for all API methods.
    All API methods require authentication (except the /api/v2/auth/login method itself, obviously).
```
And in the Transdroid code, the version check is done unauthenticated.
Hence the Access Denied we have.
