### ISSUE TITLE
custom auto sync time for rss

### ISSUE THREAD

**Issue by BADA-187** [erickok/transdroid#519]
I'm using this for my seedbox with rss feed from a private torrent (IPT) and i think 15 minutes is way to long for the shortest rss feed refresh.

with shorter times we can add the torrents faster and achieve higher share ratios as example.

i was thinking maybe you guys could add 1minute and 5minutes rss refresh.
or even better, allow us to set a custom refresh time with seconds as value.

was also thinking of a keyword filter for rss feed if possible  so we receive notifications from only given key words. and/or also a blacklist keyword filter. so feeds with specific words dont receive notifications

thanks in advance :)

**Comment by erickok** [comment]
Sorry but the way background jobs work on Android nowadays doesn't allow
for shorter periods than 15 minutes.

Op vr 20 dec. 2019 03:16 schreef BADA-187 <notifications@github.com>:

**Comment by BADA-187** [comment]
even if we remove the app from battery optimization? cus i did install other rss apps from the play store and found ine with 2 minutes sync time. and it actuallh worked.
only down side about that app is it doesnt allow IPT feeds it just errors.

im on Android 10 btw.

**Comment by erickok** [comment]
You can with a foreground service, for example. Or by setting hard fixed times instead of allowing batching, but that is a (very) bad practise and a hack.

From [the official documentation](https://developer.android.com/topic/libraries/architecture/workmanager/how-to/recurring-work):

> Note: The minimum repeat interval that can be defined is 15 minutes (same as the JobScheduler API).
