### ISSUE TITLE
Dark Theme

### ISSUE THREAD

**Issue by grravity** [erickok/transdroid#521]
First off suggesting an actual dark theme, not an amoled black theme which it already has. Also something truly consistent throughout the app. I'd honesty just suggest allowing the user to select whatever colors they want (Similar to how Simple Mobile Tools apps allow theirs)

~~Secondly, "active" I'd expect to show stuff that is actually being connected too and uploading or downloading. Not all the torrents that are "unpaused". This is kinda annoying, I'd appreciate a change here.~~

edit: this was achieved by enabling 'Treat dormant torrents as inactive'.
leaving this up for dark theme request though.

**Comment by erickok** [comment]
For the 'active isn't active' suggestion you can try the option 'Treat dormant torrents as inactive'.

I'm not sure wht you mean by a true dark theme, but yes the dark theme implementation stems from a time long before the platform had dark theme support so it's not (for example) automatically changing by the time of the day or anything.

**Comment by Z3ROGRAV1TYx** [comment]
> I'm not sure wht you mean by a true dark theme
I mean not amoled black (which is what it is currently). 
Dark generally means a dark gray, black generally refers to amoled black (turning off the pixels).
Personally amoled black fucks with my eyes quite a bit, but it's still better than light. I generally go for dark gray themes if possible.

>Also something truly consistent throughout the app

Because it's not consistent. For example, you have a "dark theme" but then a fairly light gray at the bottom (upload/download speeds, filter, etc), then a dark gray for settings. Ideally, the "dark" theme should be renamed to black or amoled black. Then make the settings menu and the download/upload speeds changed to be consistent. 
And then create a seperate theme and label it "dark" and set it as a dark gray (similar to how settings is currently.)

>Treat dormant torrents as inactive

Ah this is what I was looking for with this. Didn't know this is what that did. Thank you.

**Comment by erickok** [comment]
So really what you'd like is the background to be dark grey instead of black?

I'm not going to make the colors configurable TBH... I don't see enough users requiring that to justify this feature.

**Comment by grravity** [comment]
Yeah, most apps usually have the black theme like you have now and label it either Black or AMOLED Black (Because pixels off on oled), and then they have a dark theme which is dark grey

**Comment by kevin-stuart** [comment]
After updating to 2.5.18 today, it seems that the black has been changed to grey. Is there a way to get the black background back for AMOLED displays? I vastly preferred black. Also, I got used to it over the years.

**Comment by XxAcielxX** [comment]
> After updating to 2.5.18 today, it seems that the black has been changed to grey. Is there a way to get the black background back for AMOLED displays? I vastly preferred black. Also, I got used to it over the years.

I also totally agree, grey is not out preference. Add option for all the, White, Grey & AMOLED Black.

**Comment by erickok** [comment]
It's a regression from #529 as we now use the day/night theme default. I guess we shoudl add an AMOLED black theme now.

**Comment by kevin-stuart** [comment]
I hope this bug gets recognized as absolutely crictical and gets a quick new release to fix this ;-).

BTW, there seem to be different dark themes: The grey in the Google Play Store is significantly darker than the one used in Transdroid. I noticed it this morning, because Transdroid was quite bright even with the dark theme now.

**Comment by erickok** [comment]
Critical is a bit harsh but yes. For the next version I will introduce separate dark and black themes, as people are quite divided on this. That way, everyone van choose. 

The black widget also has a regression and needs to be fixed.

**Comment by ChriZathens** [comment]
After I downloaded the last (2.5.18) and installing it, I could not select the black theme option for the widget, so reverted back to 2.5.17. Is this because of the regression you mentioned above?

**Comment by twig** [comment]
Apologies for the loss of true black background theme colour, I didn't realise it was a regression when using DayNight theme from Android SDK.

@erickok I think subclassing the DayNight dark theme and setting the background colour to black should require the least amount of work (could be wrong though)

**Comment by erickok** [comment]
Yes, though some actually like the dark grey, so I guess it makes sense to have white, grey and black themes.

**Comment by erickok** [comment]
I checked by the dark grey was so close to black that 2 separate themes doesn't make sense imho. I changed the background to black again in 90e59c54201c3087af1de1ced0e5ff67302f372c.

**Comment by grravity** [comment]
@erickok you removed the dark grey and just kept the amoled black? Bleh I liked it lmao

**Comment by erickok** [comment]
Yeah sorry ... In the end we can't please everyone and this seems a reasonable compromise. At least the theme will be properly used, even in settings.

**Comment by grravity** [comment]
I honestly didn't understand the issue with just leaving the dark theme in? If people preferred the amoled they just use that instead, but ok? Idk.

**Comment by erickok** [comment]
It's just much more work to get another theme is, figure out how this affects the auto day/night theme, making this understandable in the UI... I am sorry but I learned the hard way to just put in more features and options - in the end, is a dark grey or true black going to be impacting your app usage?

**Comment by grravity** [comment]
Quite honestly would probably make me less desierable to do stuff in the app, amoled gives me headaches, but for quick stuff I guess i'll live with it.
Thanks for trying though

**Comment by ChriZathens** [comment]
Just as a heads up, the download link for the latest apk at https://transdroid.org/latest gives a 404 error (there is a typo ; v2.5.19 should be v.2.5.19)

**Comment by erickok** [comment]
Ah thanks for letting me know - fixed!
