### ISSUE TITLE
setting up transdroid and rtorrent/flood

### ISSUE THREAD

**Issue by jdarias** [erickok/transdroid#522]
I am trying to set transDroid to manage my rtorrent installation but from my understanding it seems that transDroid only manages rtorrent installations with rutorrent. I have flood (another gui) instead.

I tried the port from rtorrent's RPC interface (it's 5000) but i get access denied.

Tried the port flood uses (8090) and i get error during communication: check your settings.

Is it possible to set transdroid to work with rtorrent/flood?

Edit: clarity

**Comment by erickok** [comment]
Yes, Transdroid communicates with rTorrent via it's rpc point so the (web)
UI isn't important. You should check though if the scgi mount point is open
for access from outside the localhost, as a web interface wouldn't need
that but Transdroid obviously does.

Op vr 27 dec. 2019 04:24 schreef jdarias <notifications@github.com>:

**Comment by jdarias** [comment]
> 
> You should check though if the scgi mount point is open for access from outside the localhost, as a web interface wouldn't need that but Transdroid obviously does. 

How can I check this? I thought about something like that and changed the SCGI ip from 127.0.0.1 to 0.0.0.0. Even so, transdroid refuses to connect. What do I need to do?
This is my rtorrent.rc file:
`
# Where rTorrent saves the downloaded files
directory.default.set = /media/downloads

# Where rTorrent saves the session
session.path.set = /media/downloads/.session

# Which ports rTorrent can use (Make sure to open them in your router)
network.port_range.set = 53978-53978
network.port_random.set = no

# Check the hash after the end of the download
pieces.hash.on_completion.set = yes

# Enable DHT (for torrents without trackers)
dht.mode.set = auto
dht.port.set = 6881
protocol.pex.set = yes

# Authorize UDP trackers
trackers.use_udp.set = yes

# Enable encryption when possible
protocol.encryption.set = allow_incoming,try_outgoing,enable_retry

# Run rTorrent as a daemon, controlled via XMLRPC.
system.daemon.set = true

# SCGI port, used to communicate with Flood
network.scgi.open_port = "0.0.0.0:5000"
`

**Comment by erickok** [comment]
It's your webserver config where you change this.

Op vr 27 dec. 2019 14:59 schreef jdarias <notifications@github.com>:
