### ISSUE TITLE
[Question] Unpause?

### ISSUE THREAD

**Issue by grravity** [erickok/transdroid#524]
How exactly do I unpause torrents?
I see I can pause them.

**Comment by erickok** [comment]
Use the resume button. Either in the bottom of the details screen or long
press a torrent in overview.

Op do 9 jan. 2020 23:10 schreef Gravity <notifications@github.com>:

**Comment by Z3ROGRAV1TYx** [comment]
>Use the resume button. 
Ah, I see the issue. I had pressed that before (I wasn't sure if that was actually a resume button) because when I clicked it, the list refreshed, but it still had all the torrents marked as paused after the page refresh. So I see though, I have to manually refresh it. Thanks.

**Comment by erickok** [comment]
Yes depending on your client and the speed of everything, the auto refresh
can come in before the resuming has finished, in which case you need a
manual refresh.
