### ISSUE TITLE
Update to 2.5.17 breaks labels.

### ISSUE THREAD

**Issue by CypherMK** [erickok/transdroid#525]
When I updated to 2.5.17, I can't see any labels anymore. So previous labels are not visible and newly made labels aren't visible either. When I change back to 2.5.16, everything works as expected. 
I use qbittorrent 3.3.7 on my raspberry pi 3b+.

**Comment by erickok** [comment]
Hmm technically I should still support that but the support for the 4.2 qBittorent might have broken setting labels. Is it possible for you to update qB? I will have to check it out.

**Comment by CypherMK** [comment]
I'm not sure if and how I can update. I would rather not update at the moment, because it works flawlessly.
But I will look into it when I got the time. the
