### ISSUE TITLE
Cannot manually customize the remote download path Absolute status cannot be filled

### ISSUE THREAD

**Issue by BH1NBN** [erickok/transdroid#528]
Cannot manually customize the remote download path Absolute status cannot be filled

**Comment by erickok** [comment]
What torrent client do you use? Not every client support setting the download path.

**Comment by BH1NBN** [comment]
@erickok 
android9 
The place to set the download path is grayed out! Setting cannot be operated.
![QQ截图20200129184130](https://user-images.githubusercontent.com/47279146/73349898-fe8f8d80-42c6-11ea-9496-0f7fe3704498.jpg)

**Comment by erickok** [comment]
That setting is just to determine the FTP download url - you can ignore this.

Actually setting the download directory for all torrents is not possible with Transdroid. You can (for some torrent clients) set the download location for individual torrents via the torrent details screen. It is a little disk icon at the bottom.
