### ISSUE TITLE
Seedbox Problem

### ISSUE THREAD

**Issue by dabonz** [erickok/transdroid#531]
Greetings,

I have configured my seedbox in Transdroid and I keep getting Error during communication check you connection I have entered the server address and user ID and password I have tried 2 times to connect but still the same problem...any feedback would be greatly appreciated

**Comment by erickok** [comment]
Hi,

Can you send an error report from the Help menu in the app? That'll provide
some connection logs.

Best,
Eric

Op ma 24 feb. 2020 01:30 schreef dabonz <notifications@github.com>:

**Comment by dabonz** [comment]
Ok I will do that thank you 

Regards 
Marko

**Comment by dabonz** [comment]
I sent you the error logs has you requested 

Regards 
Marko
