### ISSUE TITLE
crash

### ISSUE THREAD

**Issue by phillipao** [erickok/transdroid#537]
Happened to notice this in my logs:

03-23 15:33:54.867 E/AndroidRuntime( 7149): FATAL EXCEPTION: main
03-23 15:33:54.867 E/AndroidRuntime( 7149): Process: org.transdroid.lite, PID: 7149
03-23 15:33:54.867 E/AndroidRuntime( 7149): java.lang.NullPointerException: Attempt to invoke interface method 'int java.util.List.size()' on a null object reference
03-23 15:33:54.867 E/AndroidRuntime( 7149): 	at org.transdroid.daemon.TorrentDetails.writeToParcel(TorrentDetails.java:3)
03-23 15:33:54.867 E/AndroidRuntime( 7149): 	at android.os.Parcel.writeParcelable(Parcel.java:1801)
03-23 15:33:54.867 E/AndroidRuntime( 7149): 	at android.os.Parcel.writeValue(Parcel.java:1707)
03-23 15:33:54.867 E/AndroidRuntime( 7149): 	at android.os.Parcel.writeArrayMapInternal(Parcel.java:928)
03-23 15:33:54.867 E/AndroidRuntime( 7149): 	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1584)
03-23 15:33:54.867 E/AndroidRuntime( 7149): 	at android.os.Bundle.writeToParcel(Bundle.java:1253)
03-23 15:33:54.867 E/AndroidRuntime( 7149): 	at android.os.Parcel.writeBundle(Parcel.java:997)
03-23 15:33:54.867 E/AndroidRuntime( 7149): 	at android.app.FragmentState.writeToParcel(FragmentState.java:122)
03-23 15:33:54.867 E/AndroidRuntime( 7149): 	at android.os.Parcel.writeTypedObject(Parcel.java:1634)
03-23 15:33:54.867 E/AndroidRuntime( 7149): 	at android.os.Parcel.writeTypedArray(Parcel.java:1614)
03-23 15:33:54.867 E/AndroidRuntime( 7149): 	at android.app.FragmentManagerState.writeToParcel(FragmentManager.java:619)
03-23 15:33:54.867 E/AndroidRuntime( 7149): 	at android.os.Parcel.writeParcelable(Parcel.java:1801)
03-23 15:33:54.867 E/AndroidRuntime( 7149): 	at android.os.Parcel.writeValue(Parcel.java:1707)
03-23 15:33:54.867 E/AndroidRuntime( 7149): 	at android.os.Parcel.writeArrayMapInternal(Parcel.java:928)
03-23 15:33:54.867 E/AndroidRuntime( 7149): 	at android.os.BaseBundle.writeToParcelInner(BaseBundle.java:1584)
03-23 15:33:54.867 E/AndroidRuntime( 7149): 	at android.os.Bundle.writeToParcel(Bundle.java:1253)
03-23 15:33:54.867 E/AndroidRuntime( 7149): 	at android.app.IActivityTaskManager$Stub$Proxy.activityStopped(IActivityTaskManager.java:4505)
03-23 15:33:54.867 E/AndroidRuntime( 7149): 	at android.app.servertransaction.PendingTransactionActions$StopInfo.run(PendingTransactionActions.java:145)
03-23 15:33:54.867 E/AndroidRuntime( 7149): 	at android.os.Handler.handleCallback(Handler.java:883)
03-23 15:33:54.867 E/AndroidRuntime( 7149): 	at android.os.Handler.dispatchMessage(Handler.java:100)
03-23 15:33:54.867 E/AndroidRuntime( 7149): 	at android.os.Looper.loop(Looper.java:214)
03-23 15:33:54.867 E/AndroidRuntime( 7149): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
03-23 15:33:54.867 E/AndroidRuntime( 7149): 	at java.lang.reflect.Method.invoke(Native Method)
03-23 15:33:54.867 E/AndroidRuntime( 7149): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
03-23 15:33:54.867 E/AndroidRuntime( 7149): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

Sorry, don't know what I was doing at the time. This is a Pixel 3a running transdroid 2.5.17.

**Comment by erickok** [comment]
Cheers! Fixed by 540
