### ISSUE TITLE
Unable to import/export settings 2.5.17

### ISSUE THREAD

**Issue by Explosion85** [erickok/transdroid#543]
Using a OnePlus 8 Pro running Oxygen OS 10.5.5, I attempted to import my settings to my new phone like I have done several times before. Exporting always generates the error, "Can't write to the settings file”. Importing always generates the error, ”The settings file could not be found.” I verified permissions and reinstalled more times than I care to count. The log file was empty, so I did not include it.

The only solution was to downgrade to 2.5.16, import my settings, then upgrade to 2.5.17 where the settings are still intact.

**Comment by erickok** [comment]
Yes, I can reproduce. This is due to (yet again) storage system changes since Android 10.
