### ISSUE TITLE
Wrong format for port number and ip address

### ISSUE THREAD

**Issue by Aspire1Inspire2** [erickok/transdroid#544]
![edited](https://user-images.githubusercontent.com/12798470/81949602-056db200-95d1-11ea-97a7-19733cded8a2.jpg)

My ip address is reverse proxyed.
The resolved ip address by the app is:
https://xx.xxx.xx.xxx/transmission:portnumber
This is wrong. Correct format is:
https://xx.xxx.xx.xxx:portnumber
/transmission

**Comment by erickok** [comment]
You should not enter the full URL in the host name field but only your hostname or ip address. There are separate options for port number (if non standard) or folder (for example when using a reverse proxy).
