### ISSUE TITLE
Can't connect to Transmission

### ISSUE THREAD

**Issue by arnauldb** [erickok/transdroid#547]
Hello,
I can't connect to my Transmission on my Yunohost server.
Here are the infos I have:
In 'IP or hostname' I put (the web interface of my Transmission): https://xxxxx.com/torrent/transmission/web/
Username
Psswd
But then I have a communication error message and when I look in the set up I have this:
![Screenshot_20200601-141500_Transdroid](https://user-images.githubusercontent.com/13196747/83408586-63d4c600-a402-11ea-8b92-cb0044ab85c7.png)

Also, in my Transmission server settings I use the port 51410, where should I put this?

Thank you.

**Comment by erickok** [comment]
You should enter only your IP (or hostname) in the 'IP or hostname' field. Not a full url. Transdroid constructs the full url to connect to itself.

If you need to set a path (folder), such as in your case where likely a reverse proxy is used, then use the 'Folder' setting. To choose a post number, use the 'Port number' settings. These are both found under 'Advanced settings'.
