### ISSUE TITLE
qBittorrent changing file priority issue

### ISSUE THREAD

**Issue by XxAcielxX** [erickok/transdroid#549]
Hello,

I'm not sure if anyone else have reported this issue or not, but here it is:

When I select multiple files and try to change their priority, it doesn't apply to all the selected ones, but only to the 1st file that I select not the rest.

qbittorrent-nox is installed on the server side.

Only way to change multiple is to do them 1 by 1, which is kinda a annoying as it takes too much time + the in app notifications which appears at the bottom covers the menu buttons (change the notifications to top or buttons to top).

Regards~

Edit 1: I have also noticed that priority colour doesn't reflect in the file list section, always is light green even on High Priority.

@erickok

**Comment by xifer** [comment]
I too have encountered these bugs.  I think https://github.com/erickok/transdroid/blob/master/app/src/main/java/org/transdroid/daemon/adapters/qBittorrent/QBittorrentAdapter.java#L378 should be 1,6,7 for Normal, High, Maximum (not 1,2,7).  

Likewise for https://github.com/erickok/transdroid/blob/master/app/src/main/java/org/transdroid/daemon/adapters/qBittorrent/QBittorrentAdapter.java#L898 ?

This is according for:
version >=30200: 
  https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-v3.2.0-v4.0.4)#get-torrent-contents
  https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#get-torrent-contents

But the current 1,2,7 was correct for 3.1.x: https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-v3.1.x)#get-torrent-contents

Maybe the other issue with trying to change multiple file priorities at once will go away once that's fixed?

**Comment by XxAcielxX** [comment]
This issue has been fixed. You can change multiple files priority now and it works good. About the Priority Colours, didn't pay much attention to them.

**Comment by xifer** [comment]
Ah I'll create a different issue then if the multiple file priority one is fixed.
