### ISSUE TITLE
Dark mode for widget appears to be missing in 2.5.18 

### ISSUE THREAD

**Issue by AshleyMaggard** [erickok/transdroid#555]
I just updated and I can't find where to change the widget to dark mode. As I recall it's an option when you create the widget but it's not there. No issue changing the main ui to dark mode.

**Comment by ChriZathens** [comment]
I have the same issue and have mentioned it in another issue 
https://github.com/erickok/transdroid/issues/521#issuecomment-644761882
As I wrote there I reverted to 2.5.17, however what I haven't tried is changing my phone to dark mode and verify if the widget remains white..
Can you perhaps try it and see if it makes any difference?

**Comment by AshleyMaggard** [comment]
> changing

I keep my phone on dark mode. Just tried changing to light and back to dark, did not affect the widget.

**Comment by ChriZathens** [comment]
I see... thanks for testing ..

**Comment by erickok** [comment]
Yeah this was removed in https://github.com/erickok/transdroid/commit/f109a49a6def4aba116ce02b3de1fbd472cbf247 which, to be honest, I never intended but I wasn't paying attention when merging https://github.com/erickok/transdroid/pull/529 😞 I will try to reinstate this option.

**Comment by ChriZathens** [comment]
Thanks for the fix!
Are you planning on re-releasing 2.5.18 with the fixes including, or you will release a 2.5.19 version?

**Comment by erickok** [comment]
Yes I will release a new version soon-ish. But I'm also improving the theming a bit, especially in settings.
