### ISSUE TITLE
qBittorrent: how to set up double user/pass auth

### ISSUE THREAD

**Issue by piramiday** [erickok/transdroid#556]
I'm playing around with Transdrone and qBittorrent, which is installed on a server with a reverse proxy.

I cannot wrap my head around the double user/pass issue -- **how can I authenticate both**:
- the user/pass for the **basic HTTP auth** of the reverse proxy server, and
- the user/pass for the **webUI** for qBittorrent?

**Comment by erickok** [comment]
qBittorrent uses a login request to send user/pass, which, upon successfull validation, will set a cookie that authenticates you. Transdroid will subsequently send this cookie in any request. A reverse proxy, on the other hand, will likely use http basic auth. Now, Transdroid will happily set the basic auth headers even for Qbittorrent requests, but it will use the same user/pass as for the web UI. So unless they match, there is no way to instruct Transdroid fully into authenticating.

Why do you think setting an additional reverse proxy with basic auth is better than a direct connection to qBittorrent?

**Comment by piramiday** [comment]
thanks for the explanation!
I have setup the webUI user/pass to correspond to the basic http auth user/pass combo, and I confirm it works. :+1: 
now that I think of it, I also could have added my webUI user/pass as a second authentication user for the http basic auth.

I came up empty-handed in my searches for this solution -- unless it's my fault and it's already written somewhere, it might be better to add such detail to the docs.

in particular, I am currently discovering the wonderful world of docker images.
in such a world, it's a lot easier to setup a **single** reverse proxy on HTTPS with basic authentication exposed to the internet, leaving the rest of the ecosystem to interact in the otherwise-locked-down container network.

in general, though, I have some trouble trusting and exposing to the world a basic webUI of a client which is not even in the security business! :wink:
