### ISSUE TITLE
Deluge Label non-latin letter issue.

### ISSUE THREAD

**Issue by nemonein** [erickok/transdroid#557]
Hello. Thank you for your great effort.
I'm using Deluge 2.0.3 on Ubuntu as a server(deluged) and thin client.

There's a problem on label, on which I could not make a label with non latin characters.
Korean letters, Chinese letters, and Japanese letters are impossible to use. I tried to make labels on Deluge, but it just ignored.

However I could make it possible by editing the label.conf(`/var/lib/deluge/.config/deluge/label.conf`), something like this.

```
        "음악": {
            "apply_max": false,
            "apply_move_completed": true,
            "apply_queue": false,
            "auto_add": false,
            "auto_add_trackers": [],
            "is_auto_managed": false,
            "max_connections": -1,
            "max_download_speed": -1.0,
            "max_upload_slots": -1,
            "max_upload_speed": -1.0,
            "move_completed": true,
            "move_completed_path": "/Torrent/음악",
            "prioritize_first_last": false,
            "remove_at_ratio": false,
            "stop_at_ratio": false,
            "stop_ratio": 2.0
        },
```

I'm sorry, it's not related to Transdroid, but I had to tell you about it. (I must file this to Deluge developer, but I have not yet.)

Even though I could manage the label issue on Deluge, and it works fine on Deluge thin client, Transdroid do not allow label a torrent file when the label is non-latin charaters.
Korean/Chinese/Japanese label can be seen on Transdroid(Deluge server), but it cannot be labeled.

So, I have two questions.
First, can you fix this?
Or, is it possible to use [LabelPlus](https://github.com/bdutro/deluge-labelplus/releases) on Transdroid?

Thank you for reading.

**Comment by erickok** [comment]
I tested this against rTorrent and it works, and indeed with Deluge I display them properly. I'm afraid Deluge's web interface API doesn't handle them correctly and there isn't anything I can do. Sorry.

**Comment by nemonein** [comment]
Thanks.
I might ask this to Deluge team.

**Comment by nemonein** [comment]
I report this to [Deluge team](https://forum.deluge-torrent.org/viewtopic.php?f=8&t=56074&p=234213#p234213).
I'm sorry but there's one thing I forgot to tell you.
I don't use deluge web ui. I use RPC.

**Comment by nemonein** [comment]
Deluge team says, transdroid does nothing when a label is non-latin character.
Could please read the thread I mentioned before?

BTW, is there a debug mode for transdroid or to turn on the log?
I wish to know what was going on when I set a label on a torrent.
