### ISSUE TITLE
A little advice.

### ISSUE THREAD

**Issue by 123336-mike** [erickok/transdroid#562]
Can developers add a function that starts or stops all？I think this is useful。Thanks

**Comment by erickok** [comment]
If you long-press a torrent in the main listing, you get a new top bar. You can now select more individual torrents or use the top selector to select all. After that, press start, pause, delete, etc. all those (selected) torrents.

**Comment by 123336-mike** [comment]
> 如果您在主列表中长按torrent，则会显示一个新的顶部栏。您现在可以选择更多单个种子，也可以使用顶部选择器选择所有种子。之后，按开始，暂停，删除等所有（选定的）种子。

Ok i have found it, thank you very much
