### ISSUE TITLE
Transdrone failed to connect qBittorrent 4.2.5 with CSRF protection enabled

### ISSUE THREAD

**Issue by mnixry** [erickok/transdroid#568]
I'm using qBittorrent behind reverse proxy with `caddy`
If CSRF protection enabled,it will failed to connect and shows `Access denied`.

I observed the access log of caddy and it shows qBittorrent API returned 401.
```
[16/Sep/2020:00:36:10 +0800] "POST /api/v2/auth/login HTTP/1.1" 401 0
[16/Sep/2020:00:36:11 +0800] "POST /login HTTP/1.1" 404 0
```
If I disabled CSRF protection in options, it will work properly.

**Comment by erickok** [comment]
I'll have to check how qBittorrent does csrf prevention but it's probably the cookie variant, which would be easy to implement.

**Comment by erickok** [comment]
Actually with CSRF enabled in qBittorrent it works hust fine - I think it is your caddy config that causes the issue? Does it strip cookies/headers maybe?
