### ISSUE TITLE
Nothing happens when a file or link is added in Transdroid

### ISSUE THREAD

**Issue by PapaPowerbomb** [erickok/transdroid#569]
Displays about torrents being added are displayed. That's it. I can't even choose labels or anything, and then I can't find anything at all.

Connection and error log:
13 -- Mon Sep 28 14:03:52 GMT+02:00 2020 -- 3 -- Calling system.client_version with params [ ]
14 -- Mon Sep 28 14:03:52 GMT+02:00 2020 -- 3 -- Schedule server checker job
15 -- Mon Sep 28 14:03:52 GMT+02:00 2020 -- 3 -- Schedule periodic jobInfo success, request{id=1, tag=server_checker, transient=false}, interval 03:00:00, flex 03:00:00
16 -- Mon Sep 28 14:03:52 GMT+02:00 2020 -- 3 -- Schedule rss checker job
17 -- Mon Sep 28 14:03:52 GMT+02:00 2020 -- 3 -- Schedule periodic jobInfo success, request{id=2, tag=rss_checker, transient=false}, interval 03:00:00, flex 03:00:00
18 -- Mon Sep 28 14:03:52 GMT+02:00 2020 -- 3 -- Schedule app update checker job
19 -- Mon Sep 28 14:03:52 GMT+02:00 2020 -- 3 -- Schedule periodic jobInfo success, request{id=3, tag=app_update_checker, transient=false}, interval 00:00:00 (+1 day), flex 00:00:00 (+1 day)
20 -- Mon Sep 28 14:03:53 GMT+02:00 2020 -- 3 -- Run job, request{id=1, tag=server_checker, transient=false}, waited 00:00:00, interval 03:00:00, flex 03:00:00
21 -- Mon Sep 28 14:03:53 GMT+02:00 2020 -- 3 -- Run job, request{id=2, tag=rss_checker, transient=false}, waited 00:00:00, interval 03:00:00, flex 03:00:00
22 -- Mon Sep 28 14:03:53 GMT+02:00 2020 -- 3 -- Run job, request{id=3, tag=app_update_checker, transient=false}, waited 00:00:00, interval 00:00:00 (+1 day), flex 00:00:00 (+1 day)
23 -- Mon Sep 28 14:03:53 GMT+02:00 2020 -- 3 -- Executing request{id=1, tag=server_checker, transient=false}, context PlatformJobService
24 -- Mon Sep 28 14:03:53 GMT+02:00 2020 -- 3 -- Executing request{id=2, tag=rss_checker, transient=false}, context PlatformJobService
25 -- Mon Sep 28 14:03:53 GMT+02:00 2020 -- 3 -- Executing request{id=3, tag=app_update_checker, transient=false}, context PlatformJobService
26 -- Mon Sep 28 14:03:53 GMT+02:00 2020 -- 3 -- Finished job{id=2, finished=true, result=SUCCESS, canceled=false, periodic=true, class=RssCheckerJob, tag=rss_checker}
27 -- Mon Sep 28 14:03:53 GMT+02:00 2020 -- 3 -- Calling system.client_version with params [ ]
28 -- Mon Sep 28 14:03:53 GMT+02:00 2020 -- 3 -- Finished job, request{id=2, tag=rss_checker, transient=false} SUCCESS
29 -- Mon Sep 28 14:03:53 GMT+02:00 2020 -- 3 -- Calling d.multicall2 with params [  main d.hash= d.name= d.state= d.down.rate= d.up.rate= d.peers_connected= d.peers_not_connected= d.... ]
30 -- Mon Sep 28 14:03:53 GMT+02:00 2020 -- 3 -- Calling d.multicall2 with params [  main d.hash= d.name= d.state= d.down.rate= d.up.rate= d.peers_connected= d.peers_not_connected= d.... ]
31 -- Mon Sep 28 14:03:53 GMT+02:00 2020 -- 3 -- Local Transdroid is at 239 and the reported latest version is 239
32 -- Mon Sep 28 14:03:53 GMT+02:00 2020 -- 3 -- Finished job{id=3, finished=true, result=SUCCESS, canceled=false, periodic=true, class=AppUpdateJob, tag=app_update_checker}
33 -- Mon Sep 28 14:03:53 GMT+02:00 2020 -- 3 -- Finished job, request{id=3, tag=app_update_checker, transient=false} SUCCESS
34 -- Mon Sep 28 14:03:53 GMT+02:00 2020 -- 3 -- box: Retrieved torrent listing
35 -- Mon Sep 28 14:03:53 GMT+02:00 2020 -- 3 -- box: 0 new torrents, 0 newly finished torrents.
36 -- Mon Sep 28 14:03:53 GMT+02:00 2020 -- 3 -- Finished job{id=1, finished=true, result=SUCCESS, canceled=false, periodic=true, class=ServerCheckerJob, tag=server_checker}
37 -- Mon Sep 28 14:03:53 GMT+02:00 2020 -- 3 -- Finished job, request{id=1, tag=server_checker, transient=false} SUCCESS
38 -- Mon Sep 28 14:03:58 GMT+02:00 2020 -- 3 -- Calling system.client_version with params [ ]
39 -- Mon Sep 28 14:03:59 GMT+02:00 2020 -- 3 -- Calling network.xmlrpc.size_limit.set with params [  2098432 ]
40 -- Mon Sep 28 14:03:59 GMT+02:00 2020 -- 3 -- Calling load.raw_start with params [  [B@1927ca1 ]
41 -- Mon Sep 28 14:03:59 GMT+02:00 2020 -- 3 -- Calling system.client_version with params [ ]
42 -- Mon Sep 28 14:03:59 GMT+02:00 2020 -- 3 -- Calling system.client_version with params [ ]
43 -- Mon Sep 28 14:03:59 GMT+02:00 2020 -- 3 -- Calling d.multicall2 with params [  main d.hash= d.name= d.state= d.down.rate= d.up.rate= d.peers_connected= d.peers_not_connected= d.... ]
44 -- Mon Sep 28 14:03:59 GMT+02:00 2020 -- 3 -- Calling d.multicall2 with params [  main d.hash= d.name= d.state= d.down.rate= d.up.rate= d.peers_connected= d.peers_not_connected= d.... ]
45 -- Mon Sep 28 14:04:02 GMT+02:00 2020 -- 3 -- Calling load.start with params [  *link to file*]
46 -- Mon Sep 28 14:04:02 GMT+02:00 2020 -- 3 -- Calling d.multicall2 with params [  main d.hash= d.name= d.state= d.down.rate= d.up.rate= d.peers_connected= d.peers_not_connected= d.... ]
47 -- Mon Sep 28 14:04:02 GMT+02:00 2020 -- 3 -- Calling d.multicall2 with params [  main d.hash= d.name= d.state= d.down.rate= d.up.rate= d.peers_connected= d.peers_not_connected= d.... ]
48 -- Mon Sep 28 14:17:13 GMT+02:00 2020 -- 3 -- Calling system.client_version with params [ ]
49 -- Mon Sep 28 14:17:14 GMT+02:00 2020 -- 3 -- Calling network.xmlrpc.size_limit.set with params [  2098432 ]
50 -- Mon Sep 28 14:17:14 GMT+02:00 2020 -- 3 -- Calling load.raw_start with params [  [B@d01f67a ]
51 -- Mon Sep 28 14:17:14 GMT+02:00 2020 -- 3 -- Calling d.multicall2 with params [  main d.hash= d.name= d.state= d.down.rate= d.up.rate= d.peers_connected= d.peers_not_connected= d.... ]
52 -- Mon Sep 28 14:17:14 GMT+02:00 2020 -- 3 -- Calling d.multicall2 with params [  main d.hash= d.name= d.state= d.down.rate= d.up.rate= d.peers_connected= d.peers_not_connected= d.... ]
53 -- Mon Sep 28 14:17:17 GMT+02:00 2020 -- 3 -- Calling load.start with params [  Please describe your problem:

Transdroid 2.5.19 (239)
rTorrent settings: *action file*]
54 -- Mon Sep 28 14:17:17 GMT+02:00 2020 -- 3 -- Calling d.multicall2 with params [  main d.hash= d.name= d.state= d.down.rate= d.up.rate= d.peers_connected= d.peers_not_connected= d.... ]
55 -- Mon Sep 28 14:17:17 GMT+02:00 2020 -- 3 -- Calling d.multicall2 with params [  main d.hash= d.name= d.state= d.down.rate= d.up.rate= d.peers_connected= d.peers_not_connected= d.... ]
56 -- Mon Sep 28 14:18:16 GMT+02:00 2020 -- 3 -- Calling system.client_version with params [ ]
57 -- Mon Sep 28 14:18:17 GMT+02:00 2020 -- 3 -- Calling network.xmlrpc.size_limit.set with params [  2098432 ]
58 -- Mon Sep 28 14:18:17 GMT+02:00 2020 -- 3 -- Calling load.raw_start with params [  [B@68f32ee ]
59 -- Mon Sep 28 14:18:17 GMT+02:00 2020 -- 3 -- Calling d.multicall2 with params [  main d.hash= d.name= d.state= d.down.rate= d.up.rate= d.peers_connected= d.peers_not_connected= d.... ]
60 -- Mon Sep 28 14:18:17 GMT+02:00 2020 -- 3 -- Calling d.multicall2 with params [  main d.hash= d.name= d.state= d.down.rate= d.up.rate= d.peers_connected= d.peers_not_connected= d.... ]
61 -- Mon Sep 28 14:18:20 GMT+02:00 2020 -- 3 -- Calling load.start with params [  *link* ]
62 -- Mon Sep 28 14:18:21 GMT+02:00 2020 -- 3 -- Calling d.multicall2 with params [  main d.hash= d.name= d.state= d.down.rate= d.up.rate= d.peers_connected= d.peers_not_connected= d.... ]
63 -- Mon Sep 28 14:18:21 GMT+02:00 2020 -- 3 -- Calling d.multicall2 with params [  main d.hash= d.name= d.state= d.down.rate= d.up.rate= d.peers_connected= d.peers_not_connected= d.... ]

**Comment by erickok** [comment]
I don't know of any issues with rTorrent and most users are using rTorrent... 

If a torrent doesn't actually get added, it is most likely you are trying to add it by url but it is a pricate site so your rTorrent server can not actually resolve the data. Is that what happened?

**Comment by PapaPowerbomb** [comment]
Hello,

Thanks for the feedback! No, it's when i open a local torrent file in the app.
________________________________
