### ISSUE TITLE
Please add category and uploaded amount in the main list

### ISSUE THREAD

**Issue by zhufeng** [erickok/transdroid#571]
Please add category and uploaded amount in the main list for qbittorrent.

there is no uploaded amount for downloading torrent.

and no category shown in the torrent list.

thank you.

**Comment by erickok** [comment]
This has been a deliberate decision and I don't think I will change this now. If I even do a UI overhaul than I might add this data, but for now I will close this as 'won't implement'. Sorry for this, it's just that everybody likes their data presented in different ways and I can't satisfy everyone.
