### ISSUE TITLE
Transdrone does not connect to Delugue web server until authenticated manually via a web browser.

### ISSUE THREAD

**Issue by mubbery** [erickok/transdroid#573]
Transdrone gives me an error when I hit refresh. The error message in Deluge says "Web itnerface not connected to a running Daemon" with obviously suggest a problem on the server side, however the server is running fine and the web client for deluge works ok in a browser on my PC and on the phone.

If I open a web browser on my phone and login to the deluge web client, then try Transdrone again it works fine. It looks to me like transdrone is failing to authenticate or just doesnt understand how to talk to the current Deluge web client.

My Deluge server is version 1.3.15 running on a Raspberry Pi 4

/Updated

**Comment by erickok** [comment]
This is by design. Your web interface  needs to be connected to a
running daemon.
You can configure Deluge to autoconnect, such that you never have to
manually do so via the web browser.

Op zo 18 okt. 2020 02:32 schreef mubbery <notifications@github.com>:

**Comment by mubbery** [comment]
You misunderstand. The web interface works fine. The Deluge app is just not working with it.

I have configured the deluge app to use the deluge password and to autoconnect but it fails. Deluge thinks the web interface is not working but i know it is because I can use it in a browser perfectly fine.

**Comment by erickok** [comment]
I can;t reproduce any bug here. Even if the web interface is running, it still needs to be (manually or via config on server side) connected to a running server daemon. This is by design.

**Comment by mubbery** [comment]
Sirry man, the problem still exists for me. Here is how I reproduce it.

1 - Restart the deluged and delugeweb services
2 - Try to access the service from the Transdome app - Get the error - "Web
interface not connected to a running Daemon

To fix this all I have to do it open the deluge web interface and connect
to the service which is a prompt that appears when you first open the
deluge web page. This connection has a timeout which I can change but maxes
out to 99999 seconds, which is about 27days but if reboot the Pi or restart
the deluge services for any reason I have to remember to open the deluge
admin page and connect first before Transdome will work.

Seem like this is not really a transdome issue as such but it would be
great if the service connection can be a prompt in transdome instead of
needing to go a browser first.

If you want to chat about this hit me up on discord - Lollington_Bear#8568

Thanks
Andy

**Comment by erickok** [comment]
You are probably best off configuring Deluge to autoconnect to the daemon. You can do so in the Deluge config files.

**Comment by mubbery** [comment]
Did not know that. Have googled and found out what default_daemon does.
Thanks
That seems to have fixed it :)

Andy
