### ISSUE TITLE
No custom port option (except "Local") 

### ISSUE THREAD

**Issue by jeroen7s** [erickok/transdroid#575]
There seems to be no way to set the port to anything else than 8080 for qbittorrent. Even common ports like 80 or 443(for https)

Setting this value in "local ports" also doesn't work.

**Comment by erickok** [comment]
It's the first option under Advanced Settings. Let me know if you need more help. Cheers.

**Comment by jeroen7s** [comment]
How did I completely miss it after looking at advanced settings 5 times :D
It is indeed an option right above the "Local Network" setting
my bad, thanks a lot :D
