### ISSUE TITLE
Latest Deluge 2.x doesn't work with Deluge 2 RPC

### ISSUE THREAD

**Issue by frosty5689** [erickok/transdroid#576]
Looks like Deluge 2.x changed their RPC protocol again? Can't connect with Transdroid no matter what I tweak. I made sure the port is set to the right one and the password works fine with the desktop thin client.

**Comment by bwitt** [comment]
What version of Deluge 2?  I'm using Transdroid 2.5.18 with Deluge 2.0.3 RPC (which is the latest I think?) and it's working fine.

**Comment by frosty5689** [comment]
I'm using Deluge 2.0.4 dev38. That's really odd. I wonder if there is a way
to see the error message from the connection request...

**Comment by erickok** [comment]
Yes, via the Help menu -> Send error report

**Comment by frosty5689** [comment]
This is the error message from the logs that seems relevant

24467 -- Fri Nov 20 10:40:05 PST 2020 -- 3 -- ConnectionError exception:
Deluge RPC Adapter must have SSL enabled
24468 -- Fri Nov 20 10:40:06 PST 2020 -- 3 -- ConnectionError exception:
Deluge RPC Adapter must have SSL enabled
24469 -- Fri Nov 20 10:40:07 PST 2020 -- 3 -- ConnectionError exception:
Deluge RPC Adapter must have SSL enabled
24470 -- Fri Nov 20 10:41:41 PST 2020 -- 3 -- ConnectionError exception:
Deluge RPC Adapter must have SSL enabled

I tried enabling SSL but same error, after ticking allow all certs it works
now. Wondering if this is Transdroid requiring SSL or Deluge? Since I'm
connecting via IP its not a valid cert by any means. I could connect
through the reverse proxy, but seems odd SSL is a must with Deluge 2 RPC.

**Comment by erickok** [comment]
This is a Deluge RPC protocol requirement, as far as I remember. It does not have to be a valid certificate if (such as for local networking) you do not care about that.

**Comment by frosty5689** [comment]
I guess this goes back to something from two years ago. Setup isn't clear.
https://github.com/erickok/transdroid/issues/440 maybe mention SSL is
required when Deluge RPC is selected? If not enabling it by default...
