### ISSUE TITLE
Can't set a server port number for Deluge 2 RPC

### ISSUE THREAD

**Issue by smurfix** [erickok/transdroid#577]
My Deluge server is on a nonstandard port. Setting the port number and trying to connect results in an immediate "check your connection" error (or whatever the English error message is); no actual connection attempt is made (I checked with Wireshark on my router).

Switching the protocol to Deluge HTTP "worked" insofar as Transdroid attempted to connect to the port. It failed of course but I did see the attempt in the router.

**Comment by erickok** [comment]
Did you set the port number under Advanced Settings (the first option)?

**Comment by smurfix** [comment]
Yes.

**Comment by erickok** [comment]
Looks like it uses the port setting just fine... https://github.com/erickok/transdroid/blob/c1527cb36df99aa94499c26224f0a75af1f60c44/app/src/main/java/org/transdroid/daemon/adapters/deluge/DelugeRpcClient.java#L191 I don't know what to say...
