### ISSUE TITLE
Screenshots for F-Droid

### ISSUE THREAD

**Issue by mondlicht-und-sterne** [erickok/transdroid#579]
You can add Screenshots for F-Droid, too, if you want.

https://f-droid.org/en/docs/All_About_Descriptions_Graphics_and_Screenshots/

https://gitlab.com/snippets/1895688

**Comment by Korb** [comment]
> @mondlicht-und-sterne ne closed this as completed on Feb 11. 2021

Home and Settings screen screenshots are missing or never appear on F-Droid.
