### ISSUE TITLE
Can't access Deluge

### ISSUE THREAD

**Issue by pdario** [erickok/transdroid#58]
What steps will reproduce the problem?
Start deluged on server
Start degluge-web on serer
Start transdroid on phone
Try access stored deluge server on LAN: it says there's a network error
Access deluge-web from PC
Enter deluge password and see download list
Start trandroid on phone
Try access stored deluge server on LAN: access OK

What version of the product are you using?
2.0.1

What torrent client are you using?
Deluge 1.3.6 on Debian 6

**Comment by crossRT** [comment]
Having the same issue. 
Can't connect deluge with Transdroid when the server booted.

**Comment by jelies** [comment]
Thanks, http://dev.deluge-torrent.org/wiki/Faq#HowdoIauto-connecttoaspecificdaemon instructions did the trick ;)
