### ISSUE TITLE
QBittorrent modify categories

### ISSUE THREAD

**Issue by JeremieBergeron** [erickok/transdroid#590]
Hi,
I saw this issues: https://github.com/erickok/transdroid/issues/571

If I understand, you will not add the option for the listing view.

But, is there a way to edit the categorie of a torrent or not?

Thank you

**Comment by erickok** [comment]
It depends on your torrent client but labelling should be supported for qBittorrent. Does it not work for you?

**Comment by JeremieBergeron** [comment]
I am talking about categories, not label.

It is 2 different things for qbittorent.

**Comment by moi15moi** [comment]
Oh, I just understand the problem.

If a **category has no assigned torrent**, we can not see it in transdone!

**Comment by JeremieBergeron** [comment]
Oh, I just understand the problem.

**If a category has no assigned torrent**, we can not see it in transdone!

**Comment by bwitt** [comment]
I think https://github.com/erickok/transdroid/pull/625 should fix this

**Comment by bwitt** [comment]
@JeremieBergeron this should be fixed in the latest version; can you confirm?

**Comment by JeremieBergeron** [comment]
Yes, it is!
