### ISSUE TITLE
Add transdroid to F-droid repo

### ISSUE THREAD

**Issue by ddarwish** [erickok/transdroid#60]
Add transdroid to F-droid repo.

https://f-droid.org/forums/topic/adding-apps-with-git/

**Comment by licaon-kter** [comment]
@erickok Help https://f-droid.org/wiki/page/org.transdroid.full/lastbuild_232 ?

**Comment by erickok** [comment]
Seems it (AndroidAnnotations, to be precise) can't find the AndroidManifest.xml file. This is references via the `androidManifestFile` config: https://github.com/erickok/transdroid/blob/master/app/build.gradle#L18
Perhaps the build tools are not up-to-date on F-Droid?
