### ISSUE TITLE
Transdroid widget can no longer be created on Android 12

### ISSUE THREAD

**Issue by pluusla** [erickok/transdroid#609]
Since the update to Android 12 (Oppo Find X3 Pro), it is no longer possible to create/place the Transdroid widget.

Although it can be selected and the Transdroid-internal menu for customizing the widget appears - but as soon as you want to add the widget, it is simply not placed.

The problem did not exist our Android 11

**Comment by erickok** [comment]
Fixed in ae09a0602b6f392f26dc0d54177a93354d59047c for Transdroid 2.5.22
