### ISSUE TITLE
Configure Freebox Delta

### ISSUE THREAD

**Issue by Foul** [erickok/transdroid#610]
HI ! 
I'm trying to configure Transdroid with my Freebox Delta (box from French provider)

Error connecting, even with right ports, SSL ect.. 

Need help !

French message when trying to connect is : Erreur de requête interne.

**Comment by erickok** [comment]
Which type of torrent client is running on it?

**Comment by Foul** [comment]
Transmission

**Comment by erickok** [comment]
If it is a normal Transmission client AND it runs the Transmission web UI then you can use the same credentials and IP address (and port, if this is non-standard) which you'd use to connect to the Transmission web UI.

**Comment by Foul** [comment]
Freebox : 
https://img.super-h.fr/images/206fed66dc66e274ff7bf0a58818b9c6.png
https://img.super-h.fr/images/943ad64fe3929163585daa5c253b9135.jpg

port for UI is 40297 and for torrent is 50864
my config : https://img.super-h.fr/images/f775fe819ba0754f3a31c326c49b3b84.jpg
name and password are correct.

what's wrong ?

**Comment by erickok** [comment]
Ok I see it has 54442 configured as http port and 40297 for https. Is the normal Transmission web UI actually running there on the normal path (/transmission/web)? Or is it using some custom path? Easiest is to try connect via the mobile web UI first and then just use those settings (where you should not the /web part of the url).

**Comment by Foul** [comment]
normal ou custom path.. i don't know at all :(

**Comment by erickok** [comment]
Could you mail the fill url you use to connect (the url that works on your phone's browser)? Than maybe I can deduce from this the settings you need. However, this is highly specific to your personal setup and if that Freebox Delta is using some custom access control (such as a proxy) you'd had to figure our the details yourself, or even if the Transmiussion web API is available at all.

**Comment by Foul** [comment]
https://foul.freeboxos.fr:40297/  to access the Freebox OS/Interface... and then there is a Download section to access torrent ..

**Comment by erickok** [comment]
As I have no access to such a box I'm afraid I can't really know how to connect to it. If it supports the Transmission web API then yes, but there is no way for me to know, sorry.

**Comment by Foul** [comment]
no prob, thx anyway.. i will keep you informed if i succeed ;)
