### ISSUE TITLE
Spaces in path replaced by + symbol

### ISSUE THREAD

**Issue by harristom** [erickok/transdroid#611]
With qBittorrent running on Linux moving a torrent in Transdroid causes the spaces in the path turn into +. e.g. the torrent is downloading to /media/pi/Seagate Backup Plus Drive/Downloads and I change it to /media/pi/Seagate Backup Plus Drive/Distros it will actually save to /media/pi/Seagate+Backup+Plus+Drive/Distros (creating a new directory in the process). Suspect this is related to the fix in https://github.com/erickok/transdroid/issues/558 as this only started happening recently.

**Comment by bwitt** [comment]
Hmm I can't seem to reproduce this; is it still happening for you?  I'm on qBittorrent 4.3.9 on Linux.
