### ISSUE TITLE
Cannot set single banwidth limit

### ISSUE THREAD

**Issue by j4ckp0t85** [erickok/transdroid#612]
I don't know if this is an expected behavior or not. Anyway: if i try to set for example an upload limit and don't specify any value for download limit, i get an error (please specify a positive value).

It would be useful if the values could be pre-propulated for active limits setted on the client, but i don't know if it's possible for all clients handled.

Ps: i use transdroid interfacing with an rtorrent instance

**Comment by bwitt** [comment]
related to https://github.com/erickok/transdroid/issues/481

**Comment by erickok** [comment]
Yes dup of 481. Not sure if I will ever 'fix' this as it is so client-specific.
