### ISSUE TITLE
qBittorrent - list all available categories

### ISSUE THREAD

**Issue by Generator** [erickok/transdroid#614]
## Description
qBittorrent only show current category (not to confuse with tags) or none if not set. 
Changing category need to be typed.  
On Deluge it shows all labels (called labels not categories), useful for quick changing.

## Examples
**Deluge**  (shows all labels)
![transdroid-deluge-1](https://user-images.githubusercontent.com/44146/166564715-789683dc-6c42-464c-9895-75f4db9aba63.png)

**qBittorrent** (only show current category, others aren't present)
![transdroid-qbittorrent-1](https://user-images.githubusercontent.com/44146/166564776-b5fdb29f-8f60-42fe-961c-e4e0fc0437a5.png)

### Docs
qBittorrent WEB API: 
* [Get all categories](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#get-all-categories)
* [Set torrent category](https://github.com/qbittorrent/qBittorrent/wiki/WebUI-API-(qBittorrent-4.1)#set-torrent-category)   

Possible related issues #590 #570

**Info:**
Transdroid: 2.5.22
qBittorrent: 4.4.2

**Comment by Matth7878** [comment]
Badly needed, because of that I am using transdoid only as a magnet handler and for it's RSS feature.
To actually manage torrent I rely on an alternate webui (mobile friendly) because I can easily set categories with it. Now it's my main solution to also pause, delete. Still I would prefer to use Transdroid. 😕

**Comment by JeremieBergeron** [comment]
_qBittorrent (only show current category, others aren't present)_
That's not totally true. It seems to show the category that are currently been used.
