### ISSUE TITLE
pull621

### ISSUE THREAD

**Issue by 1265578519** [erickok/transdroid#622]
https://github.com/erickok/transdroid/pull/621

**Comment by 1265578519** [comment]
https://github.com/erickok/transdroid/blob/master/app/src/main/java/org/transdroid/daemon/adapters/bitComet/BitCometAdapter.java#L173
```
                    // Request to add a torrent by URL
                    String magnetUrl = ((AddByMagnetUrlTask) task).getUrl();
                    makeUploadUrlRequest(log, "/panel/task_add_httpftp_result", magnetUrl);
                    return new DaemonTaskSuccessResult(task);
```
/panel/task_add_magnet

**Comment by bwitt** [comment]
I think you meant change that line to be `makeUploadUrlRequest(log, "/panel/task_add_magnet_result", magnetUrl);` but I can't seem to find API docs for bitComet and I don't have an instance to test. do you know where the docs are?

**Comment by 1265578519** [comment]
> I think you meant change that line to be but I can't seem to find API docs for bitComet and I don't have an instance to test. do you know where the docs are?`makeUploadUrlRequest(log, "/panel/task_add_magnet_result", magnetUrl);`

f12
![image](https://user-images.githubusercontent.com/6442439/200133667-92071369-efac-40ee-9d4b-c28ce93d4f00.png)

![image](https://user-images.githubusercontent.com/6442439/200133679-3c3f552c-4fa4-4a2a-850a-0d02792e7682.png)

![image](https://user-images.githubusercontent.com/6442439/200133722-a3a91311-cc88-4af4-9982-f3bce609643a.png)

**Comment by bwitt** [comment]
@1265578519 sorry I didn't ask earlier: what was the issue you were reporting here?  what's not working?  is it that adding magnet links to bitcomet doesn't work?  do you have an example link that doesn't work?

**Comment by 1265578519** [comment]
> @1265578519 sorry I didn't ask earlier: what was the issue you were reporting here? what's not working? is it that adding magnet links to bitcomet doesn't work? do you have an example link that doesn't work?

I use torrent url, it not work
```
https://dl.dmhy.org/2022/10/21/febe71baebff2ae0d7b6478c795ae37c5bbcac21.torrent

```

**Comment by bwitt** [comment]
thanks!
