### ISSUE TITLE
qbittorrent slow get list of 200+ torrents

### ISSUE THREAD

**Issue by MyGitHub5** [erickok/transdroid#623]
Each torrent have ~150 trackers list

The connections speed are fast
Server 1000 Mbps
Client 100 Mbps

It's take time to see the list...
Maybe the code make too many requests instead of 1?!

qbittorrent v4.4.5
transdroid v2.5.22

**Comment by bwitt** [comment]
How long does it take?  On mine with ~300 torrents (qbittorrent v4.3.9) it takes 2-4 seconds, but most only have ~5 trackers.  Could you try with qbittorrent 4.3?  It may be a performance regression with v4.4.

**Comment by erickok** [comment]
Is the web interface (much) faster? Transdroid makes one call to get all torrents but yes with large amounts this can be quite some data. I've seen 1000s or torrents in Transdroid though, being retrieved in a couple of seconds, so it also depends on your server and torrent client.

**Comment by MyGitHub5** [comment]
I update qbittorrent to 4.4.5 with Libtorrent 1.2.18 & restart
Now it's take ~5s
Before 15-20s or error and not refresh

Thank You ❤️
This app help a lot :)
