### ISSUE TITLE
bitcomet stop button is broken, pause is available

### ISSUE THREAD

**Issue by 1265578519** [erickok/transdroid#634]
bitcomet stop button is broken, pause is available
![777](https://user-images.githubusercontent.com/6442439/200139697-9045b0cf-bf07-4dde-8380-30b18709f32b.png)
![6666](https://user-images.githubusercontent.com/6442439/200139709-26eeae9b-ae75-4593-93dd-db3592af3b3b.png)

**Comment by bwitt** [comment]
looks like the pause button is actually doing a stop on the bitcomet side.  I guess the stop button should do the same thing as pause then?

**Comment by bwitt** [comment]
or maybe we should remove the pause button, and just have stop

**Comment by bwitt** [comment]
easier to just have the stop button work, and the resume button either work or not!

**Comment by bwitt** [comment]
or, could have no stop button at all and just have pause

**Comment by bwitt** [comment]
the easiest thing is to do https://github.com/erickok/transdroid/pull/635
