### ISSUE TITLE
Latest version for F-Droid

### ISSUE THREAD

**Issue by FZXizzbKv7jg** [erickok/transdroid#646]
Could you please provide v 2.5.22 for F-Droid?

**Comment by bwitt** [comment]
version 2.5.22 is already in fdroid but looks like it got disabled at some point

https://gitlab.com/fdroid/fdroiddata/-/blob/9c75727cd5ebee07881e50199e0fb7605d1180ed/metadata/org.transdroid.full.yml#L244

due to https://github.com/erickok/transdroid/issues/616 ?

**Comment by bwitt** [comment]
[fdroid has the latest version (2.5.23)](https://f-droid.org/en/packages/org.transdroid.full/); this issue can be closed.

**Comment by licaon-kter** [comment]
it didn't... it does now: https://gitlab.com/fdroid/fdroiddata/-/commit/f9d72ebc42d572d4e34562b97810d2c6e891de52 


/close this
