### ISSUE TITLE
Make new release: 2.5.23

### ISSUE THREAD

**Issue by bwitt** [erickok/transdroid#652]
Might be time to do a release, 2.5.23.  May I suggest considering merging the fixes for these first?

https://github.com/erickok/transdroid/issues/616 - Migrate away from `android-job` so it builds on F-Droid again
https://github.com/erickok/transdroid/issues/593 - Fix labels support in qBittorrent
https://github.com/erickok/transdroid/issues/634 - Dont show stop button for bitComet
https://github.com/erickok/transdroid/issues/645 - Dont crash on bad password for bitComet

**Comment by clach04** [comment]
Looks like this can be closed, link tickets closed and https://github.com/erickok/transdroid/releases/tag/v2.5.23 available.
