### ISSUE TITLE
Access is refused

### ISSUE THREAD

**Issue by Pavelprof** [erickok/transdroid#656]
Hi, I am using transdroid in my ugoose x4q tv box and managing torrents in uTorrent windows 10. At first it was working correctly, but later I started getting an error, that the access is refused when I try to add a new torrent. App still shows correct list of torrents and their status. I tried to reinstall, buy it didn't help. Could you help me? Here is report.

Transdroid 2.5.22 (242)
uTorrent settings: http://admin@192.168.1.105:8080

Connection and error log:
857 -- Tue May 30 23:45:50 GMT+03:00 2023 -- 3 -- Schedule server checker job
858 -- Tue May 30 23:45:50 GMT+03:00 2023 -- 3 -- Found pending job request{id=13, tag=server_checker, transient=false}, canceling
859 -- Tue May 30 23:45:50 GMT+03:00 2023 -- 3 -- Schedule periodic jobInfo success, request{id=16, tag=server_checker, transient=false}, interval 03:00:00, flex 03:00:00
860 -- Tue May 30 23:45:50 GMT+03:00 2023 -- 3 -- Schedule rss checker job
861 -- Tue May 30 23:45:50 GMT+03:00 2023 -- 3 -- Found pending job request{id=14, tag=rss_checker, transient=false}, canceling
862 -- Tue May 30 23:45:50 GMT+03:00 2023 -- 3 -- Schedule periodic jobInfo success, request{id=17, tag=rss_checker, transient=false}, interval 03:00:00, flex 03:00:00
863 -- Tue May 30 23:45:50 GMT+03:00 2023 -- 3 -- Schedule app update checker job
864 -- Tue May 30 23:45:51 GMT+03:00 2023 -- 3 -- Found pending job request{id=15, tag=app_update_checker, transient=false}, canceling
865 -- Tue May 30 23:45:51 GMT+03:00 2023 -- 3 -- Schedule periodic jobInfo success, request{id=18, tag=app_update_checker, transient=false}, interval 00:00:00 (+1 day), flex 00:00:00 (+1 day)
866 -- Tue May 30 23:45:51 GMT+03:00 2023 -- 3 -- AuthenticationFailure exception: Response was 'invalid request' instead of a proper JSON object (and we used auth token 'G_mdBd0zFTPRcHpw73RZR26AypscIsV-_VLlP11NlyR7jD0htZ08J3lgdmQAAAAA')
867 -- Tue May 30 23:45:51 GMT+03:00 2023 -- 3 -- Run job, request{id=16, tag=server_checker, transient=false}, waited 00:00:00, interval 03:00:00, flex 03:00:00
868 -- Tue May 30 23:45:51 GMT+03:00 2023 -- 3 -- Run job, request{id=17, tag=rss_checker, transient=false}, waited 00:00:00, interval 03:00:00, flex 03:00:00
869 -- Tue May 30 23:45:51 GMT+03:00 2023 -- 3 -- Run job, request{id=18, tag=app_update_checker, transient=false}, waited 00:00:00, interval 00:00:00 (+1 day), flex 00:00:00 (+1 day)
870 -- Tue May 30 23:45:51 GMT+03:00 2023 -- 3 -- Executing request{id=17, tag=rss_checker, transient=false}, context PlatformJobService
871 -- Tue May 30 23:45:51 GMT+03:00 2023 -- 3 -- Executing request{id=16, tag=server_checker, transient=false}, context PlatformJobService
872 -- Tue May 30 23:45:51 GMT+03:00 2023 -- 3 -- Finished job{id=17, finished=true, result=SUCCESS, canceled=false, periodic=true, class=RssCheckerJob, tag=rss_checker}
873 -- Tue May 30 23:45:51 GMT+03:00 2023 -- 3 -- Executing request{id=18, tag=app_update_checker, transient=false}, context PlatformJobService
874 -- Tue May 30 23:45:51 GMT+03:00 2023 -- 3 -- Finished job, request{id=17, tag=rss_checker, transient=false} SUCCESS
875 -- Tue May 30 23:45:51 GMT+03:00 2023 -- 3 -- Skip the update service, as we already checked the last 24 hours (or to be exact at Tue May 30 22:32:59 GMT+03:00 2023).
876 -- Tue May 30 23:45:51 GMT+03:00 2023 -- 3 -- 192.168.1.105: Retrieved torrent listing
877 -- Tue May 30 23:45:51 GMT+03:00 2023 -- 3 -- Finished job{id=18, finished=true, result=RESCHEDULE, canceled=false, periodic=true, class=AppUpdateJob, tag=app_update_checker}
878 -- Tue May 30 23:45:51 GMT+03:00 2023 -- 3 -- 192.168.1.105: 0 new torrents, 0 newly finished torrents.
879 -- Tue May 30 23:45:51 GMT+03:00 2023 -- 3 -- Finished job, request{id=18, tag=app_update_checker, transient=false} RESCHEDULE
880 -- Tue May 30 23:45:51 GMT+03:00 2023 -- 3 -- Finished job{id=16, finished=true, result=SUCCESS, canceled=false, periodic=true, class=ServerCheckerJob, tag=server_checker}
881 -- Tue May 30 23:45:51 GMT+03:00 2023 -- 3 -- Finished job, request{id=16, tag=server_checker, transient=false} SUCCESS

**Comment by erickok** [comment]
I see an authentication in your log, which might mean that the uTorrent web UI is rejecting the requests. I have seen this more in the past, specifically with adding files to uTiorrent, and typically a reinstall of uTorrent fixed this. 
By the way I recommend against using uTorrent and using a non-closed client such as qBittorrent instead.

**Comment by erickok** [comment]
Closing until I have more info.
