### ISSUE TITLE
adding item from search silently fails with v2.5.23, fine with v2.5.22

### ISSUE THREAD

**Issue by clach04** [erickok/transdroid#660]
1. Installed https://github.com/erickok/transdroid/releases/tag/v2.5.23
2. Search for something.
3. Try and add single or multiple items appears to work...
4. ...but does not show in list, even after refresh.
5. Reverting to previous v2.5.22 works fine.

Any logs, etc. that I can generate to progress?

**Comment by bwitt** [comment]
what torrent client are you connecting to?

**Comment by clach04** [comment]
I should have thought of that! It's rutorrent.

**Comment by erickok** [comment]
Logs would be great. Via Help menu -> error report

**Comment by SheepmanBR** [comment]
> I should have thought of that! It's rutorrent.

I am on Qbittorrent and it also has this same issue.

**Comment by erickok** [comment]
Hmm I tried this but perhaps the debug build didn't have the issue, due to install order. Let's see.

**Comment by cregkly** [comment]
I have the same problem but reverting to the previous version didn't help.

Not sure when it broke, but my transmission container auto updated two days ago as well.

**Comment by erickok** [comment]
2.5.24 should fix this!

**Comment by clach04** [comment]
> 2.5.24 should fix this!

Confirmed for me. Thank you! 🙏
