### ISSUE TITLE
"This app does not send notifications" on Android 14

### ISSUE THREAD

**Issue by peterjanes** [erickok/transdroid#661]
Transdroid 2.5.23 (243)
Pixel 6a running Android 14

Since upgrading to 2.5.23 from 2.5.22 I noticed that the app is no longer sending notifications for new torrents in RSS feeds or completed torrents.  I've disabled and reenabled the notification settings and changed the check interval with no change in behaviour.  I finally decided to check in the Android notification settings and it claims that Transdroid "does not send notifications" which means they can't be enabled there.

Unfortunately there seems to be no relevant information in the error log, just a list of feeds showing that there have been new items (which I also see when I look through the feeds screen).

**Comment by bwitt** [comment]
With the recent sdk bump maybe we now need to have this permission in the manifest and also request it?
```
<uses-permission android:name="android.permission.POST_NOTIFICATIONS"/>
```
https://stackoverflow.com/a/76628335/5373984

**Comment by erickok** [comment]
Ugh I though I tested this... will re-test and update.

**Comment by j4ckp0t85** [comment]
Same issue on Android 13 (Samsung)

**Comment by erickok** [comment]
2.5.24 should fix this!

**Comment by bwitt** [comment]
@erickok did you mean for [the Fix notifications on Android 13+ by asking permission
 commit](https://github.com/erickok/transdroid/commit/2083d9811894d9e7f07ed735cc2a1593e0bb6499) to be part of the release?  it looks like the tag is on [the commit just before that](https://github.com/erickok/transdroid/commit/77d785c66beaac8943c220bf7ae4224da0472ac7)

**Comment by erickok** [comment]
Yes you are right, the tag is misplaced as I forgot to push the commits before creating the tag on Github. 🤦 But the release actually has the changes.
I giess F-Droid builds from the tag so that's annoying. I can create a new tag for them, though.

**Comment by achilleas-k** [comment]
> I giess F-Droid builds from the tag so that's annoying. I can create a new tag for them, though.

Did this happen?  I'd rather not install the APK attached to the release directly since it requires uninstalling the F-Droid version (app conflict) and I'd prefer to keep the app installed through F-Droid for future updates as well.
