### ISSUE TITLE
In-app download not getting latest version

### ISSUE THREAD

**Issue by dsiminiuk** [erickok/transdroid#662]
On the mobile device, the previous version 2.5.22 tries to download from an update notification from http://transdroid.org/latest but gets the same version. I had to come to github to get the 2.5.23 version that was mentioned in the autoupdate notification.

http://transdroid.org/latest also doesn't produce a download file in Chrome.

**Comment by twig** [comment]
Yep, was confused when I downloaded and installed the "same update" multiple times

**Comment by erickok** [comment]
Thanks for reporting this. I just fixed it.
