### ISSUE TITLE
Transdroid requires read access to your file storage

### ISSUE THREAD

**Issue by fexofenadine** [erickok/transdroid#663]
"Transdroid requires read access to your file storage in order to read local .torrent files" appears now when trying to add a torrent file through the internal functionality or via a file manager. It does not request the access from the OS, and doesnt appear in the app's permissions properties (no permissions allowed, no permissions denied).

Has been happening since the new version (2.5.23), both the github and fdroid build seem affected, on Android 14. Fresh install does not help (may be what caused the perms to be wiped actually, as i uninstalled the fdroid build to install the github one initially).

**Comment by fexofenadine** [comment]
small update: 2.5.21 definitely, correctly asks for storage permissions

**Comment by erickok** [comment]
2.5.24 should fix this!
