### ISSUE TITLE
RSS notifications no longer work

### ISSUE THREAD

**Issue by s7sost** [erickok/transdroid#666]
Ever since the latest version (2.5.24), I no longer get RSS notifications the way I used to for my subscriptions. I hadn't made any changes to the configuration, so I know it started happening after the recent update.

Furthermore, the notifications area in the Android App Settings is greyed out (see screenshots), so even though they're activated in the app, I no longer get a notification when a new RSS feed item shows up.

I'm on **Android 13**, Xiaomi HyperOS **1.0.2.0**.

![Screenshot_2024-03-13-21-47-58-210_org transdroid full-edit](https://github.com/erickok/transdroid/assets/7074667/7148e9af-d17f-4262-8ca4-1c75564bdf22)
![Screenshot_2024-03-13-21-41-54-584_com android settings](https://github.com/erickok/transdroid/assets/7074667/d1efae05-0f90-4fe6-9fb2-575e4c30a491)
![Screenshot_2024-03-13-21-41-41-666_com miui securitycenter-edit](https://github.com/erickok/transdroid/assets/7074667/f12d8ea8-3ede-41a4-ad79-e9dcfb48d450)

**Comment by bwitt** [comment]
How do you get your app; do you get it via f-droid?  if so you [may be affected by this](https://github.com/erickok/transdroid/issues/661#issuecomment-1909664690)

**Comment by s7sost** [comment]
> How do you get your app; do you get it via f-droid? if so you [may be affected by this](https://github.com/erickok/transdroid/issues/661#issuecomment-1909664690)

Yes, that is correct! I am taking a look at the thread now, What would be the next step, wait until a new commit tag is created for the F-Droid repository? I tried to install it directly from the .apk available in here, but it said the package conflicted with the installed version (despite being the same, technically).

**Comment by bwitt** [comment]
Yes, the easiest thing is probably @erickok making a new release to fix this.

**Comment by erickok** [comment]
I don't control the F-Droid releases though. Is there anything I can do to get them to release it?

**Comment by erickok** [comment]
> I don't control the F-Droid releases though. Is there anything I can do to get them to release it?

Ah I see the mistagged release. Yes I will fix it.

**Comment by erickok** [comment]
I made a new release that should work. (It might take a bit of time for F-Droid to pick it up.)
