### ISSUE TITLE
Question : in RSS feeds, what does the "D" icon on the left mean ?

### ISSUE THREAD

**Issue by christop69** [erickok/transdroid#669]
![Screenshot_2024-05-31-19-13-24-00_97e8863a0b6406289fb7cc4c8c9f578c](https://github.com/erickok/transdroid/assets/55764547/c6625475-5845-4d0a-857a-840eb96ff08c)

**Comment by erickok** [comment]
Nothing, really. It's either the site's favicon or a substitude made out of the site name's first letter, using the https://besticon-demo.herokuapp.com/icon?url=[url_here]&size=72 service.
