### ISSUE TITLE
Add support to new stop/start instead of pause/resume

### ISSUE THREAD

**Issue by MyGitHub5** [erickok/transdroid#672]
https://github.com/qbittorrent/qBittorrent/commit/5d1c2496063b41874e85af0145b153e006fc92d3

**Comment by erickok** [comment]
Am I correct in that this change has landed in qBittorrent 5.0? (Looking at the code and https://www.qbittorrent.org/news)

**Comment by PoulGrym** [comment]
yes

> Am I correct in that this change has landed in qBittorrent 5.0? (Looking at the code and https://www.qbittorrent.org/news)

yes, issue remains android v2.5.24

**Comment by MyGitHub5** [comment]
yes.
if /api/v2/app/version >= v5 then use stop/start else pause/resume

**Comment by erickok** [comment]
It's merged in, but I still wanted to test to make sure everything else is still working.

**Comment by bwitt** [comment]
the start/stop button isn't showing up in the command bar at the bottom of the torrent view; there's some sort of logic to make that appear, right?
![Screenshot from 2024-10-11 21-00-05](https://github.com/user-attachments/assets/3da2622e-5a74-48bd-8223-a204ec2ac33b)
