### ISSUE TITLE
ruTorrent with httprpc plugin defective with 2.1.1+

### ISSUE THREAD

**Issue by THEDARKK** [erickok/transdroid#77]
Hello, since maj.
rTorrent does not work.
I use httprpc.
cordially

**Comment by fravia1** [comment]
Where do you add this config , I mean which file?

Sorry a bit noob here.

P.S. I followed your suggestion and made it ask authorization. Now it works. Here's part of my config:

         location ~ /rutorrent/.*\.php$ {
             auth_basic            "Restricted";
             auth_basic_user_file  /var/www/localhost/.htpasswd;

**Comment by webknjaz** [comment]
>Where do you add this config , I mean which file?

This is config of NginX web-server. Perhaps you're looking for `nginx.conf` or one of `*.conf` files in your `sites-enabled` folder.

**Comment by fravia1** [comment]
can you give  a example of the file location?

**Comment by webknjaz** [comment]
All nginx configuration files are typically located under `/etc/nginx/`
